"use client"
import { useState } from 'react'
import { ArrowRight, ArrowUpRight, FileSearch, ScanLine } from 'lucide-react'
import { Button } from '@/components/coss/button'
import { Card } from '@/components/coss/card'
import { Badge } from '@/components/prism-next/badge'
import { Dialog, DialogPopup, DialogHeader, DialogTitle, DialogDescription, DialogPanel } from '@/components/coss/dialog'
import { teacherCases, parsingCases, parsingStages } from './data'

export function TeacherUseCases() {
 const [selected,setSelected] = useState<string>('parsing')
 const [compact,setCompact] = useState(false)
 const current = teacherCases.find(c=>c.id===selected)!
 return <div className="mx-auto max-w-6xl space-y-10 px-5 py-8 sm:px-8 sm:py-10">
  <header className="space-y-3"><div className="flex flex-wrap items-center gap-3"><p className="text-sm text-muted-foreground">OLE · 教师业务设计</p><Badge variant="outline" size="lg">v0.1 · 待评审</Badge></div><div className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-semibold tracking-tight">教师用例与流程验证</h1><Button render={<a href="/next/use-cases/parsing"/>}>从解析开始<ArrowUpRight/></Button></div><p className="max-w-3xl text-base leading-7 text-muted-foreground">先明确教师要完成的工作，再验证每一步如何开始、核对和结束。本轮展开解析；后续业务先明确目标与衔接。</p></header>
  <section aria-labelledby="teacher-cases-title" className="space-y-5"><h2 id="teacher-cases-title" className="text-xl font-semibold">教师的 7 类主要工作</h2><div className="flex flex-wrap gap-2" role="group" aria-label="教师主要用例">{teacherCases.map(c=><Button key={c.id} variant={selected===c.id?'secondary':'ghost'} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)}>{c.title}</Button>)}</div><Card className="p-6 sm:p-7"><div className="flex flex-wrap items-center gap-3"><span className="text-sm tabular-nums text-muted-foreground">{current.code}</span><h3 className="text-xl font-semibold">{current.title}</h3><Badge variant={current.id==='parsing'?'info':'outline'} size="lg">{current.id==='parsing'?'本轮展开':'用例已梳理'}</Badge></div><p className="mt-3 text-base leading-7">{current.goal}</p><dl className="mt-6 grid gap-6 text-sm leading-7 sm:grid-cols-2"><div><dt className="font-medium">从什么开始</dt><dd className="mt-1 text-muted-foreground">{current.input}</dd></div><div><dt className="font-medium">完成后得到什么</dt><dd className="mt-1 text-muted-foreground">{current.output}</dd></div><div><dt className="font-medium">教师在哪里做决定</dt><dd className="mt-1 text-muted-foreground">{current.control}</dd></div><div><dt className="font-medium">如何接续其他工作</dt><dd className="mt-1 text-muted-foreground">{current.next}</dd></div></dl><p className="mt-6 text-sm leading-7 text-info-foreground">{current.flow}</p></Card><p className="text-sm leading-7 text-muted-foreground">固定入口与 Agent 进入同一项业务。后续任务继承已确认的材料与范围，各项工作也能独立开始。</p></section>
  <section aria-labelledby="parsing-cases-title" className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="parsing-cases-title" className="text-xl font-semibold">先验证解析 · 6 个教师场景</h2><Badge variant="info" size="lg">图片 / PDF / 扫描材料</Badge></div><div className="grid gap-4 lg:grid-cols-2">{parsingCases.map(c=><Card key={c.id} className="gap-4 p-5 sm:p-6"><div className="flex items-start gap-3">{c.id==='scan'?<ScanLine className="mt-1 size-5 text-info-foreground"/>:<FileSearch className="mt-1 size-5 text-info-foreground"/>}<div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">{c.code} · {c.source}</p><h3 className="mt-1 text-lg font-semibold">{c.title}</h3></div></div><p className="text-sm leading-7">{c.goal}</p><dl className="space-y-3 text-sm leading-6"><div><dt className="font-medium">必要时询问</dt><dd className="text-muted-foreground">{c.question}</dd></div><div><dt className="font-medium">预期结果</dt><dd className="text-muted-foreground">{c.result}</dd></div><div><dt className="font-medium">异常与接续</dt><dd className="text-muted-foreground">{c.exception}</dd></div></dl><Button className="mt-auto self-start" variant="outline" render={<a href={`/next/use-cases/parsing?case=${c.id}`}/>}>验证此用例<ArrowRight/></Button></Card>)}</div></section>
  <section className="space-y-5" aria-labelledby="validation-title"><h2 id="validation-title" className="text-xl font-semibold">同一条流程，验证不同分支</h2><ol className="grid gap-4 sm:grid-cols-5">{parsingStages.map((s,i)=><li key={s} className="space-y-2"><span className="text-sm tabular-nums text-info-foreground">0{i+1}</span><p className="font-medium">{s}</p><p className="text-sm leading-6 text-muted-foreground">{['检查可读性、页序与材料类型','补齐影响处理的条件','显示阶段与已处理数量','原稿定位、直接编辑与复核','明确目标与版本，保存后可接续'][i]}</p></li>)}</ol><div className="grid gap-6 pt-3 sm:grid-cols-2"><div><h3 className="font-medium">本轮通过的标准</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-muted-foreground"><li>无需编写提示词即可开始；可查看本次任务指令。</li><li>部分失败保留成功成果；只重试失败页。</li><li>修改材料或题目后，相关核对结论重新确认。</li><li>示例进度可在本机恢复；执行结束、核对完成与保存分开。</li></ul></div><div><h3 className="font-medium">设计范围与演示边界</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">流程使用明确标注的固定示例；未连接 OCR、扫描设备或真实题库。选择的本地图片可预览，PDF 可登记；真实文件不会被发送或假装解析。Word、Excel 属于 Step2 规划。用例与流程不计入通用组件数量。</p></div></div></section>
 <section className="space-y-3"><h2 className="text-xl font-semibold">检查窄屏阅读与操作</h2><p className="text-sm leading-7 text-muted-foreground">使用同一个解析流程，检查原稿与编辑区域的切换、导航收纳和按钮可达性。</p><Button variant="outline" onClick={()=>setCompact(true)}>打开窄屏流程预览</Button></section>
 <Dialog open={compact} onOpenChange={setCompact}><DialogPopup className="max-w-[392px]" closeProps={{'aria-label':'关闭窄屏预览'}}><DialogHeader><DialogTitle>窄屏流程预览</DialogTitle><DialogDescription>同一解析页面 · 示例进度在本机共享</DialogDescription></DialogHeader><DialogPanel className="p-0"><iframe title="窄屏解析流程" src={compact?'/next/use-cases/parsing?case=single':undefined} className="h-[650px] max-h-[72dvh] w-full border-0"/></DialogPanel></DialogPopup></Dialog>
 </div>
}
