"use client"
import { useId,type ReactNode } from "react"
import { ArrowUp,Check,Circle,Square } from "lucide-react"
import { Button } from "@/components/coss/button"
import { Label } from "@/components/coss/label"
import { Textarea } from "@/components/coss/textarea"
import { Spinner } from "@/components/coss/spinner"
export function AgentComposer({value,onChange,running=false,onSubmit,onStop,label="任务",placeholder="描述需要完成的任务…",submitLabel="运行",maxLength=1000}:{value:string;onChange:(value:string)=>void;running?:boolean;onSubmit:()=>void;onStop?:()=>void;label?:string;placeholder?:string;submitLabel?:string;maxLength?:number}){const id=useId();const submit=()=>{if(!running&&value.trim())onSubmit()};return <form className="space-y-3" onSubmit={e=>{e.preventDefault();submit()}}><Label htmlFor={id}>{label}</Label><Textarea id={id} value={value} onChange={e=>onChange(e.target.value)} disabled={running} placeholder={placeholder} maxLength={maxLength} onKeyDown={e=>{if(e.key==="Enter"&&(e.metaKey||e.ctrlKey)&&!e.nativeEvent.isComposing){e.preventDefault();submit()}}}/><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{value.length} / {maxLength} · Ctrl / ⌘ + Enter</span>{running?<Button type="button" variant="outline" disabled={!onStop} onClick={onStop}><Square/>停止</Button>:<Button type="submit" disabled={!value.trim()}><ArrowUp/>{submitLabel}</Button>}</div></form>}
export function AgentTaskProgress({steps,actions}:{steps:{id:string;label:string;state:"done"|"running"|"pending"|"error"}[];actions?:ReactNode}){return <div><ol className="space-y-3 border-l pl-4 py-4 text-sm">{steps.map(step=><li key={step.id} className="flex items-center gap-3">{step.state==="done"?<Check className="size-4 text-success-foreground"/>:step.state==="running"?<Spinner/>:<Circle className="size-3 text-muted-foreground"/>}<span className={step.state==="pending"?"text-muted-foreground":""}>{step.label}</span><span className="ml-auto text-xs text-muted-foreground">{{done:"完成",running:"进行中",pending:"未完成",error:"失败"}[step.state]}</span></li>)}</ol>{actions}</div>}
