"use client"
import { useId, type ReactNode } from "react"
import { Check } from "lucide-react"
import { Button } from "@/components/coss/button"
import { Progress } from "@/components/coss/progress"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/coss/table"
import { compositionSummary,formatChartValue,isChartValue } from "@/lib/prism-next/chart-options"
import { QuestionSelect } from "./question-controls"

export function MetricSummary({items,onSelect}:{items:{id:string;label:string;value:ReactNode;detail?:ReactNode}[];onSelect?:(id:string)=>void}){return <dl className="analytics-metrics">{items.map(item=><div key={item.id}><dt className="text-ui-hint text-muted-foreground">{item.label}</dt><dd className="analytics-value">{item.value}</dd>{item.detail&&<dd className="text-ui-hint text-muted-foreground">{item.detail}</dd>}{onSelect&&<dd className="mt-2"><Button variant="ghost" size="sm" onClick={()=>onSelect(item.id)}>查看{item.label}明细</Button></dd>}</div>)}</dl>}
export function GoalComparison({baseline,current,target,unit="",labels=["基线","当前","目标"],status,children}:{baseline:number|null;current:number|null;target:number|null;unit?:string;labels?:[string,string,string];status?:ReactNode;children?:ReactNode}){
 const progress=baseline!==null&&current!==null&&target!==null&&Number.isFinite(baseline+current+target)&&target>baseline?Math.max(0,Math.min(100,(current-baseline)/(target-baseline)*100)):null
 return <div className="space-y-4"><dl className="analytics-goal-values">{[baseline,current,target].map((value,i)=><div key={i}><dt className="text-ui-hint text-muted-foreground">{labels[i]}</dt><dd className="mt-2 text-section-title tabular-nums">{value===null?"—":`${value}${unit}`}</dd></div>)}</dl>{progress!==null&&<Progress value={progress} aria-label="基线至目标的数值进展"/>}{status}{children}</div>
}
export function StatusComposition({items,onSelect,selectedId,unit="",label="状态组成"}:{items:{id:string;label:string;value:number|null;color?:string}[];onSelect?:(id:string)=>void;selectedId?:string;unit?:string;label?:string}){
 const colored=items.map((item,i)=>({...item,color:item.color??(i%6===5?"var(--muted-foreground)":`var(--chart-${i%6+1})`)}))
 const {total,invalid,missing}=compositionSummary(items)
 const summary=(item:typeof items[number])=>`${item.label}：${item.value===null?"缺测":!isChartValue(item.value)||item.value<0?"无效数值":`${formatChartValue(item.value,unit)} · ${total?`${Math.round(item.value/total*1000)/10}%`:"占比 —"}`}`
 return <div className="space-y-4" role="group" aria-label={label}>
 {total>0?<div className="flex h-8 gap-px overflow-hidden rounded-md">{colored.filter(x=>isChartValue(x.value)&&x.value>0).map(item=>onSelect?<button key={item.id} type="button" aria-label={summary(item)} aria-pressed={selectedId===item.id} title={summary(item)} onClick={()=>onSelect(item.id)} className="min-w-0 cursor-pointer outline-offset-[-3px] focus-visible:outline-2 focus-visible:outline-foreground" style={{flex:item.value!,background:item.color,opacity:selectedId&&selectedId!==item.id?0.55:1}}/>:<span key={item.id} aria-label={summary(item)} style={{flex:item.value!,background:item.color}}/>)}</div>:<p className="rounded-md bg-muted px-4 py-3 text-ui-hint text-muted-foreground">{!items.length?"暂无分类数据。":missing===items.length?"所有分类均缺测。":"有效数量合计为 0。"}</p>}
 <ul className="space-y-1">{colored.map(item=><li key={item.id}>{onSelect?<Button variant="ghost" aria-pressed={selectedId===item.id} className="h-auto min-h-9 w-full flex-wrap justify-between gap-x-3 gap-y-1 whitespace-normal px-3 py-2 text-left" onClick={()=>onSelect(item.id)}><span className="flex min-w-0 items-center gap-2"><span aria-hidden className="size-2.5 shrink-0 rounded-sm" style={{background:item.color}}/>{item.label}</span><span className="ml-auto inline-flex items-center gap-2 font-normal tabular-nums">{selectedId===item.id&&<Check className="size-3.5" aria-hidden="true"/>}{summary(item).split('：').slice(1).join('：')}</span></Button>:<div className="flex items-center justify-between gap-3 py-1 text-ui-body"><span className="flex items-center gap-2"><span aria-hidden className="size-2.5 shrink-0 rounded-sm" style={{background:item.color}}/>{item.label}</span><span className="tabular-nums">{summary(item).split('：').slice(1).join('：')}</span></div>}</li>)}</ul>
 {invalid>0&&<p role="alert" className="text-ui-body text-destructive">{invalid} 项数量无效，未计入合计和比例。</p>}{missing>0&&<p className="text-ui-hint text-muted-foreground">缺测 {missing} 项；比例仅按有效数量计算。</p>}
 </div>
}
export type FilterField={id:string;label:string;options:{value:string;label:string}[]}
export function FilterBar({fields,value,onChange,onReset}:{fields:FilterField[];value:Record<string,string>;onChange:(value:Record<string,string>)=>void;onReset?:()=>void}){const id=useId();return <div className="flex flex-wrap items-end gap-3">{fields.map(field=><label key={field.id} className="grid gap-2 text-ui-body" htmlFor={`${id}-${field.id}`}>{field.label}<QuestionSelect id={`${id}-${field.id}`} label={field.label} value={value[field.id]??""} items={field.options} onChange={next=>onChange({...value,[field.id]:next})}/></label>)}{onReset&&<Button variant="ghost" onClick={onReset}>重置筛选</Button>}</div>}
export function DataRecordTable<T extends {id:string}>({rows,columns,onSelect,selectedId,rowLabel,empty="暂无记录"}:{rows:T[];columns:{id:string;label:string;numeric?:boolean;align?:"left"|"right";render:(row:T)=>ReactNode}[];onSelect?:(id:string)=>void;selectedId?:string;rowLabel?:(row:T)=>string;empty?:string}){return <div className="overflow-x-auto"><Table><TableHeader><TableRow>{columns.map(c=><TableHead key={c.id} className={c.numeric||c.align==="right"?"text-right":undefined}>{c.label}</TableHead>)}{onSelect&&<TableHead>操作</TableHead>}</TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id} data-state={selectedId===row.id?"selected":undefined}>{columns.map(c=><TableCell key={c.id} className={c.numeric?"text-right tabular-nums":c.align==="right"?"text-right":undefined}>{c.render(row)}</TableCell>)}{onSelect&&<TableCell><Button variant="ghost" size="sm" aria-label={`查看 ${rowLabel?.(row)??row.id}`} onClick={()=>onSelect(row.id)}>查看</Button></TableCell>}</TableRow>)}</TableBody></Table>{!rows.length&&<p className="py-8 text-center text-ui-hint text-muted-foreground">{empty}</p>}</div>}
