"use client"
import { useId, type ReactNode } from "react"
import { Button } from "@/components/coss/button"
import { Progress } from "@/components/coss/progress"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/coss/table"
import { QuestionSelect } from "./question-controls"

export function MetricSummary({items,onSelect}:{items:{id:string;label:string;value:ReactNode;detail?:ReactNode}[];onSelect?:(id:string)=>void}){return <dl className="analytics-metrics">{items.map(item=><div key={item.id}><dt className="text-sm text-muted-foreground">{item.label}</dt><dd className="analytics-value">{item.value}</dd>{item.detail&&<dd className="text-sm leading-6 text-muted-foreground">{item.detail}</dd>}{onSelect&&<dd className="mt-2"><Button variant="ghost" size="sm" onClick={()=>onSelect(item.id)}>查看{item.label}明细</Button></dd>}</div>)}</dl>}
export function GoalComparison({baseline,current,target,unit="",labels=["基线","当前","目标"],status,children}:{baseline:number|null;current:number|null;target:number|null;unit?:string;labels?:[string,string,string];status?:ReactNode;children?:ReactNode}){
 const progress=baseline!==null&&current!==null&&target!==null&&Number.isFinite(baseline+current+target)&&target>baseline?Math.max(0,Math.min(100,(current-baseline)/(target-baseline)*100)):null
 return <div className="space-y-4"><dl className="analytics-goal-values">{[baseline,current,target].map((value,i)=><div key={i}><dt className="text-sm text-muted-foreground">{labels[i]}</dt><dd className="mt-2 text-xl font-semibold tabular-nums">{value===null?"—":`${value}${unit}`}</dd></div>)}</dl>{progress!==null&&<Progress value={progress} aria-label="基线至目标的数值进展"/>}{status}{children}</div>
}
export function StatusComposition({items,onSelect}:{items:{id:string;label:string;value:number;color?:string}[];onSelect?:(id:string)=>void}){const colored=items.map((item,i)=>({...item,color:item.color??`var(--chart-${i%5+1})`}));const total=items.reduce((sum,item)=>sum+Math.max(0,item.value),0);return <div className="space-y-4"><div className="flex h-3 overflow-hidden rounded-sm" aria-hidden="true">{colored.filter(x=>x.value>0).map(item=><span key={item.id} style={{flex:item.value,background:item.color}}/>)}</div><ul className="space-y-2">{colored.map(item=><li key={item.id} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><span className="size-2.5 rounded-sm" style={{background:item.color}}/>{item.label}</span>{onSelect?<Button variant="ghost" size="sm" onClick={()=>onSelect(item.id)}>{item.value} · {total?Math.round(item.value/total*100):0}%</Button>:<span>{item.value} · {total?Math.round(item.value/total*100):0}%</span>}</li>)}</ul></div>}
export type FilterField={id:string;label:string;options:{value:string;label:string}[]}
export function FilterBar({fields,value,onChange,onReset}:{fields:FilterField[];value:Record<string,string>;onChange:(value:Record<string,string>)=>void;onReset?:()=>void}){const id=useId();return <div className="flex flex-wrap items-end gap-3">{fields.map(field=><label key={field.id} className="grid gap-2 text-sm" htmlFor={`${id}-${field.id}`}>{field.label}<QuestionSelect id={`${id}-${field.id}`} label={field.label} value={value[field.id]??""} items={field.options} onChange={next=>onChange({...value,[field.id]:next})}/></label>)}{onReset&&<Button variant="ghost" onClick={onReset}>重置筛选</Button>}</div>}
export function DataRecordTable<T extends {id:string}>({rows,columns,onSelect,selectedId,empty="暂无记录"}:{rows:T[];columns:{id:string;label:string;render:(row:T)=>ReactNode}[];onSelect?:(id:string)=>void;selectedId?:string;empty?:string}){return <div className="overflow-x-auto"><Table><TableHeader><TableRow>{columns.map(c=><TableHead key={c.id}>{c.label}</TableHead>)}{onSelect&&<TableHead>操作</TableHead>}</TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id} data-state={selectedId===row.id?"selected":undefined}>{columns.map(c=><TableCell key={c.id}>{c.render(row)}</TableCell>)}{onSelect&&<TableCell><Button variant="ghost" size="sm" aria-label={`查看 ${row.id}`} onClick={()=>onSelect(row.id)}>查看</Button></TableCell>}</TableRow>)}</TableBody></Table>{!rows.length&&<p className="py-8 text-center text-sm text-muted-foreground">{empty}</p>}</div>}
