"use client"
import { useState } from 'react'
import { useTheme } from 'next-themes'
import { motion } from 'motion/react'
import { Check, Info, Search } from 'lucide-react'
import { Button } from '@/components/coss/button'
import { Input } from '@/components/coss/input'
import { Badge } from '@/components/coss/badge'
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from '@/components/coss/table'
import { DemoSection, Labeled, MaterialSelect } from '@/components/prism-next/demo-parts'
import { RootFormula } from '@/components/prism-next/math-content'
import { themeOptions, themePalette, brandColors, COSS_COMMIT } from '@/lib/prism-next/config'
const roles=[['background','正文背景'],['secondary','次级背景'],['surface','浮层表面'],['border','分割与边框'],['foreground','正文与公式'],['heading','标题'],['muted','次要文字'],['disabled','禁用文字'],['link','文字链接']] as const
export function Foundations(){const{setTheme}=useTheme();const[moved,setMoved]=useState(false);return <div className="prism-content"><header className="prism-page-heading"><p>FOUNDATIONS / v1.2</p><h1>基础规范</h1><span>清晰的内容层级、成套的主题配对、coss 原始组件与克制的动效。</span></header>
  <DemoSection title="三个主题，同一套语义" description="背景切换时，文字、图标、边框、状态与弹出层一起切换。"> <div className="grid gap-5 lg:grid-cols-3">{themeOptions.map(t=><section key={t.value} className="overflow-hidden rounded-xl border" style={{background:themePalette[t.value].background,color:themePalette[t.value].foreground,borderColor:themePalette[t.value].border}}><div className="space-y-3 p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">{t.label}</h3><Search className="size-4"/></div><p className="text-sm leading-6">清楚地阅读文字、公式与数字。</p><p className="text-sm" style={{color:themePalette[t.value].muted}}>说明文字也保持可读。</p><div className="rounded-md border px-3 py-2 text-sm" style={{background:themePalette[t.value].secondary,borderColor:themePalette[t.value].border}}>x² − 3x + 2 = 0</div><Button type="button" variant="outline" style={{color:themePalette[t.value].foreground,background:themePalette[t.value].surface,borderColor:themePalette[t.value].border}} onClick={()=>setTheme(t.value)}>应用{t.label}主题</Button></div></section>)}</div>
    <div className="mt-7 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>语义角色</TableHead>{themeOptions.map(t=><TableHead key={t.value}>{t.label}</TableHead>)}</TableRow></TableHeader><TableBody>{roles.map(([key,label])=><TableRow key={key}><TableCell>{label}</TableCell>{themeOptions.map(t=><TableCell key={t.value} className="font-mono text-xs"><span className="mr-2 inline-block size-3 rounded-sm border align-middle" style={{background:themePalette[t.value][key]}}/>{themePalette[t.value][key]}</TableCell>)}</TableRow>)}</TableBody></Table></div></DemoSection>
  <DemoSection title="曜彩只在需要时出现" description="三原色保留为资产；可读的文字和状态使用各主题中的配套深浅色。"><div className="flex flex-wrap gap-7">{brandColors.map(c=><div key={c.name} className="flex items-center gap-3"><span className="size-8 rounded-lg border" style={{background:c.color}}/><div className="text-sm">{c.name}<p className="mt-1 font-mono text-xs text-muted-foreground">{c.color}</p></div></div>)}</div><div className="mt-6 flex flex-wrap gap-3"><Badge variant="info"><Info/>进行中的信息</Badge><Badge variant="error">需要修正</Badge><Badge variant="success"><Check/>已完成</Badge></div></DemoSection>
  <DemoSection id="mathematics" title="文字、公式与数字" description="正文采用系统常用字体；数学使用本地 STIX Two Math 与原生 MathML，不手动压缩分式和根号。"><div className="max-w-2xl space-y-5"><h3 className="text-2xl font-semibold text-(--heading)">二次方程的实数根</h3><p className="text-base leading-7 text-foreground">正文优先完整、明确地传达内容。辅助信息通过字号、间距与位置建立层次，不靠过浅的字色隐藏。</p><div className="prism-equation"><RootFormula/></div><p className="prism-numeric text-sm">结果值　+1.000　+2.000　−0.125</p><p className="text-sm text-muted-foreground">表格数字开启 tabular-nums；需要小数点对齐时统一精度并右对齐。</p></div></DemoSection>
  <DemoSection title="coss 尺寸与字段宽度" description="高度、圆角、内边距和下拉行为沿用官方实现。宽度服从输入内容，避免把短选项拉成整栏。"><div className="flex flex-wrap items-start gap-7">{(['sm','default','lg']as const).map(size=><div key={size} className="w-48 space-y-4"><Labeled label={size==='default'?'默认尺寸':size==='sm'?'紧凑尺寸':'宽松尺寸'} id={'foundation-input-'+size}><Input id={'foundation-input-'+size} size={size} defaultValue="材料标题"/></Labeled><Labeled label="材料类型" id={'foundation-select-'+size}><MaterialSelect id={'foundation-select-'+size} size={size}/></Labeled><Button size={size}>保存修改</Button></div>)}</div><p className="mt-6 text-sm leading-7 text-muted-foreground">以默认 16px 根字号计：桌面默认高 32px，sm 为 28px，lg 为 36px；窄屏分别为 36 / 32 / 40px。单行标题通常填满表单列，类型选择约 11–12rem，数字输入约 9–11rem。这里只调整字段容器，不覆盖组件内部尺寸。</p></DemoSection>
  <DemoSection title="动效用于说明状态" description="coss 的展开与焦点动效保持原样；跨状态的出现与位移使用 Motion，并响应系统的减少动态效果设置。"><div className="max-w-sm"><div className={"mb-5 flex h-12 rounded-lg bg-muted p-2 "+(moved?"justify-end":"justify-start")}><motion.div layout transition={{duration:.2,ease:'easeOut'}} className="h-8 w-20 rounded-md bg-primary text-center text-sm leading-8 text-primary-foreground">{moved?'已就位':'待移动'}</motion.div></div><Button variant="outline" onClick={()=>setMoved(v=>!v)}>切换位置</Button></div></DemoSection>
  <div className="prism-source-foot"><p>组件源代码：coss apps/ui（MIT），版本固定于 <code>{COSS_COMMIT.slice(0,12)}</code>。本版提供 54 项官方基础组件、日期选择组合及材料研读、Agent 两种应用模式。</p><p>保留 shadcn 的组件源码工作方式；使用 Base UI 1.8.0、Motion 13.3.0。旧版保留在独立外壳中，历史评审结论不作为新版通过依据。</p><a href="https://coss.com/ui/docs" target="_blank" rel="noreferrer" className="underline underline-offset-4">查看 coss 官方文档 ↗</a></div>
</div>}
