"use client"
import {useLayoutEffect,useRef,type ReactNode,type KeyboardEvent,type RefObject} from 'react'
import {Button} from './button'
import {Badge as CossBadge} from '@/components/coss/badge'
import {Select,SelectTrigger,SelectValue,SelectPopup,SelectItem} from '@/components/coss/select'
import {ScrollArea} from '@/components/coss/scroll-area'
import {ThinBar} from './question-analysis-parts'
import './knowledge-rail.css'
export type KnowledgeEvidence = {question:string;points:string[];label:ReactNode}
export type KnowledgeRailItem = {id:string;name:ReactNode;rate:number;secondary:ReactNode;status?:ReactNode;evidence:KnowledgeEvidence[]}
export type KnowledgeRailProps = {sections:{id:string;label:ReactNode;items:KnowledgeRailItem[]}[];selected?:string|null;onSelect:(id:string)=>void;onEvidence:(question:string,points:string[])=>void;filter?:ReactNode;bodyOnly?:boolean}
export function KnowledgeEvidenceList({items,onEvidence}:{items:KnowledgeEvidence[];onEvidence:(question:string,points:string[])=>void}) {return <ul className="space-y-1">{items.map(e=><li key={e.question}><Button variant="link" className="h-auto sm:h-auto whitespace-normal text-left" onClick={()=>onEvidence(e.question,e.points)}>{e.label}</Button></li>)}</ul>}
export function ReviewRailFilter({id,label,value,items,onChange}:{id:string;label:string;value:string;items:{value:string;label:string;count?:number}[];onChange:(value:string)=>void}) {return <><label htmlFor={id} className="sr-only">{label}</label><Select value={value} items={items.map(f=>({value:f.value,label:f.count===undefined?f.label:`${f.label} ${f.count}`}))} onValueChange={v=>{if(v)onChange(v)}}><SelectTrigger id={id} size="sm"><SelectValue/></SelectTrigger><SelectPopup>{items.map(f=><SelectItem key={f.value} value={f.value}>{f.label}{f.count===undefined?null:<> {f.count}</>}</SelectItem>)}</SelectPopup></Select></>}
export function ReviewRailList({items,selected,onSelect,onLocate,children,label}:{items:{id:string}[];selected?:string|null;onSelect:(id:string)=>void;onLocate:(id?:string)=>void;children:ReactNode;label:string}) {
 const root=useRef<HTMLDivElement>(null),order=items.map(i=>i.id).join('|')
 useLayoutEffect(()=>{let frame=0;const reveal=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const node=root.current?.querySelector<HTMLElement>('[data-selected="true"]');if(node?.getClientRects().length&&!node.closest('[inert]'))node.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})})};reveal();const observer=new ResizeObserver(reveal);if(root.current)observer.observe(root.current);return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[selected,order])
 function keyboard(e:KeyboardEvent){if(!['ArrowUp','ArrowDown','Enter'].includes(e.key)||(e.target as HTMLElement).closest('[data-evidence]'))return;const focused=(e.target as HTMLElement).closest<HTMLElement>('[data-entry]')?.dataset.entry;e.preventDefault();e.stopPropagation();if(e.key==='Enter'){onLocate(focused??selected??undefined);return}const index=Math.max(0,items.findIndex(x=>x.id===(focused??selected))),next=items[Math.max(0,Math.min(items.length-1,index+(e.key==='ArrowUp'?-1:1)))];if(next){onSelect(next.id);[...root.current?.querySelectorAll<HTMLButtonElement>('[data-entry]')??[]].find(n=>n.dataset.entry===next.id)?.focus({preventScroll:true})}}
 return <div ref={root} className="space-y-4 px-3 pb-3" role="listbox" aria-label={label} onKeyDown={keyboard}>{children}</div>
}
export function KnowledgeRail({sections,selected,onSelect,onEvidence,filter,bodyOnly=false}:KnowledgeRailProps){
 const body=<>{sections.map(({id:topic,label,items})=>{return !!items.length&&<section key={topic}><h3 className="mb-2 text-ui-meta text-muted-foreground">{label}</h3><div className="space-y-2">{items.map(k=><div key={k.id} className="grid"><Button variant="ghost" role="option" data-entry={k.id} data-selected={k.id===selected} aria-selected={k.id===selected} onClick={()=>onSelect(k.id)} className={`h-auto sm:h-auto whitespace-normal ${selected===k.id?'ring-2 ring-info':''}`}><span className="grid min-w-0 flex-1 gap-1 text-left"><span className="flex items-start justify-between gap-2"><span className="text-ui-action">{k.name}</span>{k.status&&<CossBadge size="sm" variant="outline">{k.status}</CossBadge>}</span><span className="flex items-center gap-2"><ThinBar value={k.rate}/><span className="text-ui-meta">{k.rate}%</span></span><span className="text-ui-meta text-muted-foreground">{k.secondary}</span></span></Button>{selected===k.id&&<div data-evidence className="ml-3 mt-2 border-l pl-2"><p className="text-ui-meta text-muted-foreground">证据清单</p><KnowledgeEvidenceList items={k.evidence} onEvidence={onEvidence}/></div>}</div>)}</div></section>})}</>
 if(bodyOnly)return body
 const items=sections.flatMap(s=>s.items)
 return <aside className="knowledge-rail min-h-0 bg-background" aria-label="知识点栏">{filter}<ScrollArea overscrollContain><ReviewRailList items={items} selected={selected} onSelect={onSelect} onLocate={id=>{const k=items.find(i=>i.id===id);if(k){onSelect(k.id);const e=k.evidence[0];if(e)onEvidence(e.question,e.points)}}} label="选择知识点">{body}{!items.length&&<p className="text-ui-body text-muted-foreground">没有符合筛选的条目</p>}</ReviewRailList></ScrollArea></aside>
}
