"use client"
import { useId,type ReactNode } from "react"
import { CheckIcon,CircleAlertIcon,CircleIcon } from "lucide-react"
import { Field,FieldLabel } from "@/components/coss/field"
import { Textarea } from "@/components/coss/textarea"
import { DataRecordTable } from "./data-display"
import { QuestionSelect } from "./question-controls"

export type EvidenceItem={id:string;title:string;observation:ReactNode;source?:ReactNode;location?:ReactNode;status:ReactNode;actions?:ReactNode}
export function DiagnosisEvidenceTable({items,onInspect}:{items:EvidenceItem[];onInspect?:(id:string)=>void}){return <DataRecordTable rows={items} onSelect={onInspect} columns={[{id:"evidence",label:"观察与证据",render:r=><div className="min-w-56 max-w-lg whitespace-normal"><p className="font-medium">{r.title}</p><div className="mt-1 text-ui-hint text-muted-foreground">{r.observation}</div><div className="mt-2 text-ui-hint text-muted-foreground">{r.source}</div></div>},{id:"location",label:"关联",render:r=>r.location},{id:"status",label:"判断状态",render:r=>r.status},...(items.some(i=>i.actions)?[{id:"actions",label:"操作",render:(r:EvidenceItem)=>r.actions}]:[])]}/>}
export function LearningGoalCard({id,title,status,source,actions,children}:{id:string;title:string;status?:ReactNode;source?:ReactNode;actions?:ReactNode;children?:ReactNode}){return <article className="@container space-y-5 rounded-xl border p-5 sm:p-6" aria-label={`${id} 学习目标`}><header className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1 space-y-2"><div className="flex flex-wrap items-center gap-2"><span className="text-ui-hint text-muted-foreground">{id}</span>{status}</div><h4 className="text-block-title">{title}</h4><div className="text-ui-hint text-muted-foreground">{source}</div></div>{actions}</header>{children}</article>}
export type LearningTaskItem={id:string;title:ReactNode;condition?:ReactNode;note?:ReactNode;schedule:ReactNode;status:ReactNode;actions?:ReactNode}
/** List layout keeps forms and actions reachable in narrow planning containers. */
export function LearningTaskList({items,layout="table",density="default"}:{items:LearningTaskItem[];layout?:"table"|"list";density?:"default"|"compact"}){
 if(layout==="list")return <ol className={density==="compact"?"min-w-0 space-y-4":"min-w-0 space-y-6"}>{items.map((item,index)=><li key={item.id} className="min-w-0 space-y-3"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0 flex-1 basis-48"><p className="text-ui-hint text-muted-foreground">步骤 {index+1}</p><div className="min-w-0 break-words text-item-title">{item.title}</div></div>{item.status}</div><div className="min-w-0 space-y-2 text-ui-body">{item.condition}{item.note}{item.schedule}</div>{item.actions}</li>)}</ol>
 return <DataRecordTable rows={items} columns={[{id:"task",label:"任务与完成条件",render:r=><div className="min-w-56 max-w-lg whitespace-normal"><p className="font-medium">{r.title}</p><div className="mt-1 text-ui-hint text-muted-foreground">{r.condition}</div>{r.note&&<div className="mt-2 text-ui-hint">{r.note}</div>}</div>},{id:"schedule",label:"日期 / 时长",render:r=>r.schedule},{id:"status",label:"状态",render:r=>r.status},{id:"actions",label:"操作",render:r=>r.actions}]}/>
}
export type CriterionResult="pass"|"retry"
export function VerificationFields({criteria,results,note,onResultsChange,onNoteChange,error}:{criteria:{id:string;text:string}[];results:Record<string,CriterionResult|undefined>;note:string;onResultsChange:(results:Record<string,CriterionResult|undefined>)=>void;onNoteChange:(note:string)=>void;error?:string}){const id=useId();return <div className="space-y-5">{criteria.map((item,index)=><Field key={item.id}><FieldLabel>标准 {index+1}</FieldLabel><p className="text-ui-hint">{item.text}</p><QuestionSelect label={`标准 ${index+1} 判断`} value={results[item.id]??"pending"} onChange={value=>onResultsChange({...results,[item.id]:value==="pending"?undefined:value as CriterionResult})} items={[{value:"pending",label:"待判断"},{value:"pass",label:"满足标准"},{value:"retry",label:"尚未满足"}]}/></Field>)}<Field><FieldLabel htmlFor={id}>核验依据</FieldLabel><Textarea id={id} value={note} onChange={e=>onNoteChange(e.target.value)} placeholder="记录支持判断的具体证据。"/></Field>{error&&<p role="alert" className="text-ui-body text-destructive">{error}</p>}</div>}
export type MilestoneItem={id:string;title:string;detail:ReactNode;state:"met"|"blocked"|"retry"|"pending"|"active"}
export function MilestoneList({items}:{items:MilestoneItem[]}){return <ol className="goal-milestones">{items.map((item,index)=><li key={item.id} data-state={item.state}><span className="milestone-mark">{item.state==="met"?<CheckIcon/>:item.state==="blocked"||item.state==="retry"?<CircleAlertIcon/>:<CircleIcon/>}</span><div><p className="text-ui-hint text-muted-foreground">{String(index+1).padStart(2,"0")}</p><h3 className="mt-1 text-item-title">{item.title}</h3><div className="mt-2 text-ui-hint text-muted-foreground">{item.detail}</div></div></li>)}</ol>}
