"use client"
import { useState } from "react"
import { Button } from "@/components/coss/button"
import { Input } from "@/components/coss/input"
import { Textarea } from "@/components/coss/textarea"
import { Label } from "@/components/coss/label"
import { Switch } from "@/components/coss/switch"
import { Dialog, DialogPopup, DialogHeader, DialogTitle, DialogDescription, DialogPanel, DialogFooter } from "@/components/coss/dialog"
import { PointsField, QuestionSelect } from "./question-controls"
import type { DraftKind, QuestionDraft } from "@/lib/prism-next/question-workspace"
export function QuestionDraftSettings({kind,value,onSave,onClose}:{kind:DraftKind;value:QuestionDraft;onSave:(value:QuestionDraft)=>void;onClose:()=>void}) {
 const [draft,setDraft]=useState(value),[groups,setGroups]=useState(value.groups.map(name=>({original:name,name}))),[error,setError]=useState("")
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogPopup closeProps={{"aria-label":"关闭设置"}}><DialogHeader><DialogTitle>{kind==="paper"?"试卷设置":"练习设置"}</DialogTitle><DialogDescription>仅用于当前{kind==="paper"?"试卷":"练习"}，不会修改试题篮或另一份草稿。</DialogDescription></DialogHeader><DialogPanel><div className="space-y-5"><div className="space-y-2"><Label htmlFor="draft-title">标题</Label><Input id="draft-title" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></div>{kind==="practice"&&<div className="space-y-2"><Label htmlFor="draft-goal">练习目标</Label><Textarea id="draft-goal" value={draft.goal} onChange={event=>setDraft({...draft,goal:event.target.value})}/></div>}<div className="flex flex-wrap items-center justify-between gap-3"><Label>预计时长（分钟）</Label><PointsField label="预计时长（分钟）" value={draft.minutes} max={240} step={1} unit="分钟" onChange={value=>setDraft({...draft,minutes:value??0})}/></div><div className="flex items-center justify-between"><Label htmlFor="draft-points">显示分值</Label><Switch id="draft-points" checked={draft.showPoints} onCheckedChange={value=>setDraft({...draft,showPoints:value})}/></div><div className="space-y-2"><Label>答案展示设置</Label><QuestionSelect label="答案展示设置" value={draft.answers} items={[{value:"teacher",label:"仅教师可见"},{value:"after",label:"完成后显示"}]} onChange={value=>setDraft({...draft,answers:value as QuestionDraft["answers"]})}/><p className="text-ui-hint text-muted-foreground">当前为教师编排预览；设置供后续布置时使用。</p></div><div className="space-y-2"><Label>{kind==="paper"?"试卷结构":"练习分组"}</Label>{groups.map((group,index)=><div className="flex items-center gap-2" key={index}><Input aria-label={`第${index+1}组名称`} value={group.name} onChange={event=>setGroups(previous=>previous.map((item,i)=>i===index?{...item,name:event.target.value}:item))}/><Button variant="ghost" size="sm" aria-label={`删除第${index+1}组`} disabled={groups.length===1} onClick={()=>setGroups(previous=>previous.filter((_,i)=>i!==index))}>删除</Button></div>)}<Button variant="outline" size="sm" onClick={()=>setGroups(previous=>[...previous,{original:"",name:`第 ${previous.length+1} 组`}])}>添加分组</Button><p className="text-ui-hint text-muted-foreground">重命名保留原组题目。删除分组后，其题目移入第一组。</p></div>{error&&<p role="alert" className="text-ui-body text-destructive-foreground">{error}</p>}</div></DialogPanel><DialogFooter><Button variant="outline" onClick={onClose}>取消</Button><Button onClick={()=>{const names=groups.map(group=>group.name.trim());if(!draft.title.trim()||names.some(name=>!name)||new Set(names).size!==names.length||draft.minutes<=0){setError("请填写标题、正数时长，以及不重复且非空的分组名称。");return}onSave({...draft,title:draft.title.trim(),groups:names,entries:draft.entries.map(entry=>({...entry,group:groups.find(group=>group.original===(entry.group??value.groups[0]))?.name.trim()??names[0]}))});onClose()}}>应用设置</Button></DialogFooter></DialogPopup></Dialog>
}
