"use client"
import type {ReactNode} from 'react'
import {Sparkles} from 'lucide-react'
import {Button} from './button'
import {Badge} from './badge'
import {Badge as CossBadge} from '@/components/coss/badge'
import {Rate,ThinBar} from './question-analysis-parts'
import {KnowledgeEvidenceList,type KnowledgeEvidence} from './knowledge-rail'
export type QuestionAnalysisPanelProps = {
 knowledge?:{topic:ReactNode;rate?:number|null;rateEmptyText?:ReactNode;affected:ReactNode;volume?:ReactNode;volumeText?:ReactNode;status?:ReactNode;evidence:KnowledgeEvidence[]}|null
 total:ReactNode;kind:string;max:ReactNode;statistics:{mean:ReactNode;sd:ReactNode;d:ReactNode;discrimination:ReactNode;fullRate:ReactNode;zeroRate:ReactNode}
 distribution:number[];affected:ReactNode;rate:number;pending:ReactNode;insight?:ReactNode
 errorAnswers?:{text:string;count:number}[];errorAnswersSlot?:ReactNode;reasons:{text:string;count:number}[];related:{id:string;name:string}[]
 reasonsEmptyText?:ReactNode;relatedEmptyText?:ReactNode;evidenceEmptyText?:ReactNode
 affectedLabel?:string;supplementaryMetrics?:{label:string;value:ReactNode;hint?:ReactNode}[]
 onKnowledge:(id:string)=>void;onEvidence:(question:string,points:string[])=>void
}
/** Values, risk bands and AI descriptions are supplied by the host. */
export function QuestionAnalysisPanel({knowledge:k,total,kind,max,statistics,distribution,affected,rate,pending,insight='选项分析未提供',errorAnswers,errorAnswersSlot,reasons,related,reasonsEmptyText,relatedEmptyText,evidenceEmptyText,affectedLabel='受影响',supplementaryMetrics,onKnowledge,onEvidence}:QuestionAnalysisPanelProps) {return <section className="space-y-4" aria-label={k?'知识点概况':'本题全班概况'}>{k?<><p className="text-ui-meta text-muted-foreground">{k.topic}</p>{typeof k.rate==='number'&&Number.isFinite(k.rate)?<Rate value={k.rate} label="知识点本次得分率"/>:k.rateEmptyText!==undefined&&<p className="text-ui-hint text-muted-foreground">{k.rateEmptyText}</p>}<p className="text-ui-body">{`${affectedLabel} `}{k.affected} / {total} 名学生</p><p className="text-ui-body">{k.volumeText??k.volume}</p>{supplementaryMetrics&&supplementaryMetrics.length>0&&<dl data-supplementary-statistics className="grid grid-cols-2 gap-x-3 gap-y-4 text-ui-body tabular-nums"><SupplementaryMetrics items={supplementaryMetrics}/></dl>}{k.status&&<Badge variant="outline">{k.status}</Badge>}{k.evidence.length===0&&evidenceEmptyText!==undefined&&<section className="space-y-2"><h3 className="text-ui-action">证据清单</h3><p className="text-ui-hint text-muted-foreground">{evidenceEmptyText}</p></section>}<KnowledgeEvidenceList items={k.evidence} onEvidence={onEvidence}/><p className="text-ui-meta text-muted-foreground">单次试卷不表达长期掌握度</p></>:<><dl data-question-statistics className="grid grid-cols-2 gap-x-3 gap-y-4 whitespace-nowrap text-ui-body tabular-nums"><div><dt className="text-ui-meta text-muted-foreground">平均分</dt><dd>{statistics.mean} / {max}</dd></div><div><dt className="text-ui-meta text-muted-foreground">标准差</dt><dd>{statistics.sd}</dd></div><div><dt className="text-ui-meta text-muted-foreground">区分度</dt><dd className="flex items-center gap-1">{statistics.d} <CossBadge size="sm" variant="outline">{statistics.discrimination}</CossBadge></dd></div><div><dt className="text-ui-meta text-muted-foreground">满分率 · 零分率</dt><dd>{percentText(statistics.fullRate)} · {percentText(statistics.zeroRate)}</dd></div>{supplementaryMetrics&&<SupplementaryMetrics items={supplementaryMetrics}/>}</dl>
 {kind==='选择题'?<p data-option-insight className="text-ui-body">{insight}</p>:kind==='填空题'?<><div className="flex items-center gap-2 text-ui-body"><span>答对 {distribution[0]} · 答错 {affected}</span><ThinBar value={rate}/></div><h3 className="text-ui-action">典型错误答案</h3>{errorAnswersSlot??(errorAnswers?<ul className="space-y-2 text-ui-body">{errorAnswers.map(g=><li key={g.text}>{g.text} · {g.count} 人</li>)}</ul>:<p className="text-ui-body">未提供</p>)}</>:<><div className="flex h-1 gap-0.5 overflow-hidden rounded-full" aria-label="本题得分分布">{distribution.map((n,i)=><span key={i} className={['bg-muted-foreground','bg-warning','bg-destructive'][i]} style={{flex:n}}/>)}</div><p className="text-ui-meta">满分 {distribution[0]} · 部分 {distribution[1]} · 零分 {distribution[2]}</p><Badge variant="outline">待复核 {pending}</Badge><section className="space-y-2"><h3 className="flex items-center gap-2 text-ui-action"><Sparkles className="size-4"/>主要失分原因 <span className="text-ui-meta text-muted-foreground">AI 归纳</span></h3>{reasons.length===0&&reasonsEmptyText!==undefined&&<p className="text-ui-hint text-muted-foreground">{reasonsEmptyText}</p>}<ul className="space-y-2 text-ui-meta text-muted-foreground">{reasons.map(r=><li key={r.text}>{r.text} · {r.count} 人</li>)}</ul></section></>}
 <div data-related-knowledge><p className="text-ui-meta text-muted-foreground">关联知识点</p>{related.length===0&&relatedEmptyText!==undefined&&<p className="text-ui-hint text-muted-foreground">{relatedEmptyText}</p>}<div className="flex flex-wrap gap-1">{related.map(k=><Button key={k.id} variant="link" className="h-auto sm:h-auto whitespace-normal" onClick={()=>onKnowledge(k.id)}>{k.name}</Button>)}</div></div>
</>}</section>}

function percentText(value:ReactNode) {return typeof value==='number'||(typeof value==='string'&&value.trim()!==''&&Number.isFinite(Number(value)))?<>{value}%</>:value}

function SupplementaryMetrics({items}:{items:NonNullable<QuestionAnalysisPanelProps['supplementaryMetrics']>}){return items.map((item,index)=><div key={index} className="min-w-0 whitespace-normal break-words [overflow-wrap:anywhere]"><dt className="text-ui-meta text-muted-foreground">{item.label}</dt><dd>{item.value}</dd>{item.hint!==undefined&&<dd className="text-ui-hint text-muted-foreground">{item.hint}</dd>}</div>)}
