"use client"
import { useLayoutEffect, useRef, type RefObject, type ReactElement } from 'react'
import { ChevronLeft, ChevronRight, PanelLeftClose, Sparkles } from 'lucide-react'
import { Button } from '@/components/prism-next/button'
import { Badge } from '@/components/prism-next/badge'
import { Badge as CossBadge } from '@/components/coss/badge'
import { Tabs, TabsList, TabsTab, TabsPanel } from '@/components/coss/tabs'
import { Select, SelectTrigger, SelectValue, SelectPopup, SelectItem } from '@/components/coss/select'
import { Tooltip, TooltipTrigger, TooltipPopup } from '@/components/coss/tooltip'
import { Kbd } from '@/components/coss/kbd'
import { Group, GroupSeparator } from '@/components/coss/group'
import { Combobox, ComboboxTrigger, ComboboxPopup, ComboboxInput, ComboboxList, ComboboxGroup, ComboboxGroupLabel, ComboboxCollection, ComboboxItem, ComboboxEmpty } from '@/components/coss/combobox'
import { Frame, FrameHeader, FrameFooter } from '@/components/coss/frame'
import { Meter, MeterTrack, MeterIndicator } from '@/components/coss/meter'
import { Avatar, AvatarFallback } from '@/components/coss/avatar'
import { ScrollArea } from '@/components/coss/scroll-area'
import { reviewQuestions, questionAnalyses, knowledgePoints, questionFilters, knowledgeFilters, filterQuestions, filterKnowledge, type ReviewQuestion, type Knowledge, type StudentAnswer } from './fixture'
import { questionSorts, sortQuestions, rateLabel } from './analysis'
export function Tip({label,keys,children}:{label:string;keys:string;children:ReactElement}){return <Tooltip><TooltipTrigger render={children}/><TooltipPopup className="surface-floating motion-reduce:transition-none" side="left">{label} <Kbd>{keys}</Kbd></TooltipPopup></Tooltip>}
export function Rate({value,label}:{value:number;label:string}){return <div className="flex items-center gap-2"><div className="min-w-0 flex-1"><Meter value={value} max={100} aria-label={label}><MeterTrack><MeterIndicator className="motion-reduce:transition-none"/></MeterTrack></Meter></div><span className="text-ui-meta tabular-nums">{value}%</span></div>}
export function ThinBar({value}:{value:number}){return <span aria-hidden="true" className="block h-1 flex-1 overflow-hidden rounded-full bg-muted"><span className="block h-full bg-foreground" style={{width:`${Number.isFinite(value)?Math.max(0,Math.min(100,value)):0}%`}}/></span>}
export function StudentLabel({answer:a}:{answer:StudentAnswer}){return <div className="flex items-center gap-2 py-2 text-ui-body"><Avatar aria-hidden="true"><AvatarFallback>{a.student.name[0]}</AvatarFallback></Avatar><span>{a.student.name}</span><span className="truncate text-ui-meta text-muted-foreground">{a.student.examId}</span><span className={`size-2 shrink-0 rounded-full ${a.status==='满分'?'bg-success':a.status==='零分'?'bg-destructive':'bg-warning'}`} aria-label={a.status}/><span className="text-ui-meta">{a.score} 分</span></div>}
export function QuestionJump({current,open,onOpenChange,onSelect,triggerRef}:{current:ReviewQuestion;open:boolean;onOpenChange:(v:boolean)=>void;onSelect:(id:string)=>void;triggerRef:RefObject<HTMLButtonElement|null>}){
 const groups=['选择题','填空题','解答题'].map(value=>({value,items:reviewQuestions.filter(q=>q.type===value)}))
 return <Combobox items={groups} value={current} open={open} onOpenChange={onOpenChange} itemToStringLabel={q=>`第 ${q.number} 题 ${q.type} ${knowledgePoints.find(k=>k.id===q.knowledge)!.name}`} onValueChange={q=>{if(q)onSelect(q.id)}}>
 <Group className="ml-auto shrink-0" aria-label="题目导航"><Tip label="上一题" keys="["><Button variant="outline" disabled={current.number===1} onClick={()=>onSelect(reviewQuestions[current.number-2].id)}><ChevronLeft/><span className="d1-student-label">上一题</span></Button></Tip><GroupSeparator/><ComboboxTrigger ref={triggerRef} render={<Button variant="outline"/>} aria-label={`选择题目，当前第 ${current.number} / 20 题`}>{current.number} / 20</ComboboxTrigger><GroupSeparator/><Tip label="下一题" keys="]"><Button variant="outline" disabled={current.number===20} onClick={()=>onSelect(reviewQuestions[current.number].id)}><span className="d1-student-label">下一题</span><ChevronRight/></Button></Tip></Group>
 <ComboboxPopup finalFocus={triggerRef} className="surface-floating w-96 max-w-[calc(100vw-1rem)]" aria-label="题目跳转面板"><div className="space-y-2 border-b p-2"><label htmlFor="question-search" className="text-ui-action">搜索题号或知识点</label><ComboboxInput id="question-search" showTrigger={false}/></div><ComboboxEmpty>没有匹配的题目</ComboboxEmpty><ComboboxList>{(group:typeof groups[number])=><ComboboxGroup key={group.value} items={group.items}><ComboboxGroupLabel>{group.value}</ComboboxGroupLabel><ComboboxCollection>{(q:ReviewQuestion)=><ComboboxItem key={q.id} value={q}><div className="min-w-0 flex-1 space-y-1"><span className="block text-ui-body">第 {q.number} 题 · {q.type} · {knowledgePoints.find(k=>k.id===q.knowledge)!.name}</span><div className="flex items-center gap-2"><ThinBar value={q.rate}/><span className="text-ui-meta">{rateLabel(q)} {q.rate}% · 区分度 {questionAnalyses[q.id].d.toFixed(2)}</span></div></div></ComboboxItem>}</ComboboxCollection></ComboboxGroup>}</ComboboxList><p className="p-2 text-ui-meta"><Kbd>↑ ↓</Kbd>选择 <Kbd>Enter</Kbd>跳转 <Kbd>Esc</Kbd>关闭</p></ComboboxPopup></Combobox>
}
export function StudentJump({answers,current,max,open,onOpenChange,onSelect,triggerRef}:{answers:StudentAnswer[];current:StudentAnswer|null;max:number;open:boolean;onOpenChange:(v:boolean)=>void;onSelect:(id:string)=>void;triggerRef:RefObject<HTMLButtonElement|null>}){
 const groups=['待复核','已确认'].map(value=>({value,items:answers.filter(a=>a.review===value)}))
 const index=current?answers.indexOf(current):-1, search=useRef<HTMLInputElement>(null)
 return <Combobox items={groups} value={current} open={open} onOpenChange={onOpenChange} itemToStringLabel={a=>`${a.student.name} ${a.student.examId} ${a.student.id}`} onValueChange={a=>{if(a)onSelect(a.student.id)}}>
 <Group className="shrink-0" aria-label="学生导航">
 <Tip label="上一位学生" keys="←"><Button variant="outline" size="icon" aria-label="上一位学生" disabled={index<=0} onClick={()=>onSelect(answers[index-1].student.id)}><ChevronLeft/></Button></Tip><GroupSeparator/>
 <Tip label="选择学生" keys="S"><ComboboxTrigger ref={triggerRef} render={<Button variant="outline"/>} aria-label={current?`选择学生，${current.student.name}，当前第 ${index+1} / ${answers.length} 位`:`选择学生 · ${answers.length}`}>
 {current?<><Avatar aria-hidden="true" className="size-6"><AvatarFallback>{current.student.name[0]}</AvatarFallback></Avatar><span>{current.student.name}</span><span className="tabular-nums">{index+1} / {answers.length}</span></>:<>选择学生 · {answers.length}</>}
 </ComboboxTrigger></Tip><GroupSeparator/>
 <Tip label="下一位学生" keys="→"><Button variant="outline" size="icon" aria-label="下一位学生" disabled={index===answers.length-1} onClick={()=>onSelect(answers[index+1].student.id)}><ChevronRight/></Button></Tip>
 </Group>
 <ComboboxPopup initialFocus={search} finalFocus={triggerRef} className="surface-floating w-96 max-w-[calc(100vw-1rem)]" aria-label="学生跳转面板"><div className="space-y-2 border-b p-2"><label className="text-ui-action" htmlFor="answer-student-search">姓名或考号</label><ComboboxInput ref={search} id="answer-student-search" showTrigger={false}/></div><ComboboxEmpty>没有匹配的学生</ComboboxEmpty><ComboboxList>{(group:typeof groups[number])=><ComboboxGroup key={group.value} items={group.items}><ComboboxGroupLabel>{group.value}</ComboboxGroupLabel><ComboboxCollection>{(a:StudentAnswer)=><ComboboxItem key={a.student.id} value={a}><div className="min-w-0 flex-1"><StudentLabel answer={a}/><div className="flex items-center gap-2"><ThinBar value={a.score/max*100}/><span className="text-ui-meta tabular-nums">{a.score} / {max}</span></div><span className="text-ui-meta text-muted-foreground">{a.review} · {a.status}</span></div></ComboboxItem>}</ComboboxCollection></ComboboxGroup>}</ComboboxList><p className="p-2 text-ui-meta"><Kbd>↑ ↓</Kbd>选择 <Kbd>Enter</Kbd>跳转 <Kbd>Esc</Kbd>关闭</p></ComboboxPopup></Combobox>
}
export function StudentScale({answers,current,max,onSelect}:{answers:StudentAnswer[];current:StudentAnswer|null;max:number;onSelect:(id:string)=>void}){
 const counts=['满分','部分得分','零分'].map(status=>answers.filter(a=>a.status===status).length)
 return <><p className="sr-only">{answers.length} 位学生：满分 {counts[0]}、部分 {counts[1]}、零分 {counts[2]}</p><div data-student-scale aria-hidden="true" className="flex h-2 items-end gap-0.5 px-2">{answers.map(a=><Tooltip key={a.student.id}><TooltipTrigger render={<span/>} data-student-tick={a.student.id} onClick={()=>onSelect(a.student.id)} className={`min-w-0 flex-1 cursor-pointer ${a.student.id===current?.student.id?'h-2 bg-info':`h-1 ${a.status==='满分'?'bg-muted-foreground':a.status==='零分'?'bg-destructive':'bg-warning'}`}`}/><TooltipPopup className="surface-floating">{a.student.name} · {a.score} / {max}</TooltipPopup></Tooltip>)}</div></>
}
export function EvidenceList({knowledge:k,onEvidence}:{knowledge:Knowledge;onEvidence:(question:string,points:string[])=>void}){return <ul className="space-y-1">{k.evidence.map(e=><li key={e.question}><Button variant="link" className="h-auto sm:h-auto whitespace-normal text-left" onClick={()=>onEvidence(e.question,e.points)}>第 {reviewQuestions.find(q=>q.id===e.question)!.number} 题 · 评分点 {e.points.map(p=>p.slice(1)).join('、')}</Button></li>)}</ul>}
export function QuestionKnowledgeRail({view,onView,question,knowledge,filter,onFilter,sort='number',onSort=()=>{},onQuestion,onKnowledge,onEvidence,onLocate,onCollapse,closeRef}:{view:string;onView:(s:string)=>void;question:ReviewQuestion;knowledge:Knowledge|null;filter:string;onFilter:(s:string)=>void;sort?:string;onSort?:(s:string)=>void;onQuestion:(s:string)=>void;onKnowledge:(s:string)=>void;onEvidence:(s:string,p:string[])=>void;onLocate:()=>void;onCollapse:()=>void;closeRef:RefObject<HTMLButtonElement|null>}){
 const root=useRef<HTMLElement>(null), list=view==='questions'?sortQuestions(filterQuestions(filter),sort,questionAnalyses):filterKnowledge(filter), selected=view==='questions'?question.id:knowledge?.id
 useLayoutEffect(()=>{let frame=0;const reveal=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const node=root.current?.querySelector<HTMLElement>('[data-selected="true"]');if(node?.getClientRects().length&&!node.closest('[inert]'))node.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})})};reveal();const observer=new ResizeObserver(reveal);if(root.current)observer.observe(root.current);return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[selected,view,filter,sort])
 const filters=view==='questions'?questionFilters:knowledgeFilters
 const choose=(id:string)=>view==='questions'?onQuestion(id):onKnowledge(id)
 return <aside ref={root} data-review-rail aria-label="题目与知识点栏" className="d1-rail bg-background"><Tabs className="q1-rail-tabs" value={view} onValueChange={onView}><header className="d1-rail-header flex items-center justify-between gap-1 px-3"><TabsList size="sm" aria-label="浏览视角"><TabsTab value="questions">题目<CossBadge variant="outline">20</CossBadge></TabsTab><TabsTab value="knowledge">知识点<CossBadge variant="outline">18</CossBadge></TabsTab></TabsList><Tip label="收起题目栏" keys="T"><Button ref={closeRef} variant="ghost" size="icon" aria-label="收起题目栏" onClick={onCollapse}><PanelLeftClose/></Button></Tip></header>
 <div className="grid gap-2 px-3 pb-2"><label htmlFor="review-rail-filter" className="sr-only">{view==='questions'?'题目筛选':'知识点筛选'}</label><Select value={filter} items={filters.map(f=>({value:f.value,label:`${f.label} ${f.count}`}))} onValueChange={v=>{if(v)onFilter(v)}}><SelectTrigger id="review-rail-filter" size="sm"><SelectValue/></SelectTrigger><SelectPopup>{filters.map(f=><SelectItem key={f.value} value={f.value}>{f.label} {f.count}</SelectItem>)}</SelectPopup></Select>{view==='questions'&&<><label htmlFor="review-rail-sort" className="sr-only">题目排序</label><Select value={sort} items={questionSorts} onValueChange={v=>{if(v)onSort(v)}}><SelectTrigger id="review-rail-sort" size="sm"><SelectValue/></SelectTrigger><SelectPopup>{questionSorts.map(s=><SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectPopup></Select></>}</div>
 <TabsPanel value={view} className="min-h-0"><ScrollArea overscrollContain><div className="space-y-4 px-3 pb-3" role="listbox" aria-label={view==='questions'?'选择题目':'选择知识点'} onKeyDown={e=>{if(!['ArrowUp','ArrowDown','Enter'].includes(e.key)||(e.target as HTMLElement).closest('[data-evidence]'))return;const focused=(e.target as HTMLElement).closest<HTMLElement>('[data-entry]')?.dataset.entry; e.preventDefault();e.stopPropagation();if(e.key==='Enter'){if(view==='knowledge'){const k=knowledgePoints.find(k=>k.id===(focused??selected));if(k){onKnowledge(k.id);const evidence=k.evidence[0];onEvidence(evidence.question,evidence.points)}}else{if(focused&&focused!==selected)choose(focused);onLocate()}return}const index=Math.max(0,list.findIndex(x=>x.id===(focused??selected))),next=list[Math.max(0,Math.min(list.length-1,index+(e.key==='ArrowUp'?-1:1)))];if(next){choose(next.id);root.current?.querySelector<HTMLButtonElement>(`[data-entry="${next.id}"]`)?.focus({preventScroll:true})}}}>
 {view==='questions'?<><div className="space-y-1 py-1"><div className="flex h-1 gap-0.5 overflow-hidden rounded-full" aria-hidden="true"><span className="bg-warning" style={{flex:6}}/><span className="bg-muted" style={{flex:14}}/></div><p className="text-ui-meta text-muted-foreground">高失分 6 · 其余 14</p></div>{(sort==='number'?['选择题','填空题','解答题']:['排序结果']).map(type=>{const items=sortQuestions(filterQuestions(filter),sort,questionAnalyses).filter(q=>sort!=='number'||q.type===type),all=reviewQuestions.filter(q=>q.type===type);if(!items.length)return null;const rows=sort!=='number'||type==='解答题';return <section key={type}><h3 className="mb-1 flex justify-between text-ui-meta text-muted-foreground"><span>{type} · {items.length} 题</span>{sort==='number'&&<span>{Math.round(all.reduce((s,q)=>s+q.rate*q.max,0)/all.reduce((s,q)=>s+q.max,0))}%</span>}</h3><div className={rows?'grid gap-1':'grid grid-cols-4 gap-1'}>{items.map(q=>{const stats=questionAnalyses[q.id],description=`第 ${q.number} 题，${q.type}，${rateLabel(q)} ${q.rate}%，平均分 ${stats.mean.toFixed(1)} / ${q.max}，区分度 ${stats.d.toFixed(2)} · ${stats.discrimination}`;return <Tooltip key={q.id}><TooltipTrigger render={<Button variant="ghost" role="option" aria-selected={q.id===selected} data-entry={q.id} data-selected={q.id===selected} aria-label={description} onClick={()=>onQuestion(q.id)} className={`d1-question relative h-auto sm:h-auto ${rows?'':'min-h-11 flex-col gap-0.5'} ${q.tone==='destructive'?'bg-destructive/10 hover:bg-destructive/20':q.tone==='warning'?'bg-warning/10 hover:bg-warning/20':'bg-muted hover:bg-accent'} ${q.id===selected?'ring-2 ring-info shadow-sm':''}`}/>}>
 {rows?<span className="grid flex-1 gap-1"><span className="flex items-center gap-2"><span className="text-ui-action tabular-nums">{q.number}</span>{sort!=='number'&&<span className="text-ui-meta">{q.type}</span>}<ThinBar value={q.rate}/><span className="text-ui-meta tabular-nums">{q.rate}%</span></span><span className="text-left text-ui-meta text-muted-foreground">区分度 {stats.d.toFixed(2)}</span></span>:<><span className="text-ui-action tabular-nums">{q.number}</span><span className="text-ui-meta tabular-nums">{q.rate}%</span>{stats.discrimination==='待改进'&&<span aria-hidden="true" className="absolute right-1 top-1 size-1.5 rounded-full bg-info"/>}</>}
 </TooltipTrigger><TooltipPopup className="surface-floating">{description}</TooltipPopup></Tooltip>})}</div></section>})}</>:<>{[...new Set(knowledgePoints.map(k=>k.topic))].map(topic=>{const items=filterKnowledge(filter).filter(k=>k.topic===topic);return !!items.length&&<section key={topic}><h3 className="mb-2 text-ui-meta text-muted-foreground">{topic}</h3><div className="space-y-2">{items.map(k=><div key={k.id} className="grid"><Button variant="ghost" role="option" data-entry={k.id} data-selected={k.id===selected} aria-selected={k.id===selected} onClick={()=>onKnowledge(k.id)} className={`h-auto sm:h-auto whitespace-normal ${selected===k.id?'ring-2 ring-info':''}`}><span className="grid min-w-0 flex-1 gap-1 text-left"><span className="flex items-start justify-between gap-2"><span className="text-ui-action">{k.name}</span>{!k.sufficient&&<CossBadge size="sm" variant="outline">继续观察</CossBadge>}</span><span className="flex items-center gap-2"><ThinBar value={k.rate}/><span className="text-ui-meta">{k.rate}%</span></span><span className="text-ui-meta text-muted-foreground">受影响 {k.affected} / 36 · {k.evidence.length} 道证据题</span></span></Button>{selected===k.id&&<div data-evidence className="ml-3 mt-2 border-l pl-2"><p className="text-ui-meta text-muted-foreground">证据清单</p><EvidenceList knowledge={k} onEvidence={onEvidence}/></div>}</div>)}</div></section>})}</>}
 {!list.length&&<p className="text-ui-body text-muted-foreground">没有符合筛选的条目</p>}</div></ScrollArea></TabsPanel></Tabs></aside>
}
export function QuestionInspector({question:q,answer:a,knowledge:k,onKnowledge,onEvidence,onIntent}:{question:ReviewQuestion;answer:StudentAnswer|null;knowledge:Knowledge|null;onKnowledge:(s:string)=>void;onEvidence:(s:string,p:string[])=>void;onIntent:(s:string)=>void}){const stats=questionAnalyses[q.id];const related=[...new Set(q.points.flatMap(p=>p.knowledge))];const knowledgeTags=(ids:string[])=><div className="flex flex-wrap gap-1">{ids.map(id=><Button key={id} variant="link" className="h-auto sm:h-auto whitespace-normal" onClick={()=>onKnowledge(id)}>{knowledgePoints.find(k=>k.id===id)!.name}</Button>)}</div>;return <aside className="d1-inspector min-h-0 bg-background" data-review-inspector aria-label="题目与作答检查器"><FrameHeader className="d1-inspector-header justify-center px-4 py-0"><h2 className="text-block-title">{k?`知识点 · ${k.name}`:'本题分析'}</h2></FrameHeader><div className="min-h-0 overflow-hidden px-4 pb-4"><ScrollArea overscrollContain scrollFade><Frame><div className="space-y-7 px-4 py-5"><section className="space-y-4" aria-label={k?'知识点概况':'本题全班概况'}>{k?<><p className="text-ui-meta text-muted-foreground">{k.topic}</p><Rate value={k.rate} label="知识点本次得分率"/><p className="text-ui-body">受影响 {k.affected} / 36 名学生</p><p className="text-ui-body">{k.volume} 分 · {k.evidence.length} 道证据题</p>{!k.sufficient&&<Badge variant="outline">继续观察</Badge>}<EvidenceList knowledge={k} onEvidence={onEvidence}/><p className="text-ui-meta text-muted-foreground">单次试卷不表达长期掌握度</p></>:<><dl data-question-statistics className="grid grid-cols-2 gap-x-3 gap-y-4 whitespace-nowrap text-ui-body tabular-nums"><div><dt className="text-ui-meta text-muted-foreground">平均分</dt><dd>{stats.mean.toFixed(1)} / {q.max}</dd></div><div><dt className="text-ui-meta text-muted-foreground">标准差</dt><dd>{stats.sd.toFixed(1)}</dd></div><div><dt className="text-ui-meta text-muted-foreground">区分度</dt><dd className="flex items-center gap-1">{stats.d.toFixed(2)} <CossBadge size="sm" variant="outline">{stats.discrimination}</CossBadge></dd></div><div><dt className="text-ui-meta text-muted-foreground">满分率 · 零分率</dt><dd>{stats.fullRate}% · {stats.zeroRate}%</dd></div></dl>
 {q.type==='选择题'?<p data-option-insight className="text-ui-body">{(()=>{const o=stats.options?.find(o=>o.label===stats.distractor);return o?`主要干扰项 ${o.label}：${o.count} 人，高分组 ${o.high} · 低分组 ${o.low}`:'选项分析未提供'})()}</p>:q.type==='填空题'?<><div className="flex items-center gap-2 text-ui-body"><span>答对 {q.distribution[0]} · 答错 {q.affected}</span><ThinBar value={q.rate}/></div><h3 className="text-ui-action">典型错误答案</h3>{stats.errorAnswers?<ul className="space-y-2 text-ui-body">{stats.errorAnswers.map(g=><li key={g.text}>{g.text} · {g.students.length} 人</li>)}</ul>:<p className="text-ui-body">未提供</p>}</>:<><div className="flex h-1 gap-0.5 overflow-hidden rounded-full" aria-label="本题得分分布">{q.distribution.map((n,i)=><span key={i} className={['bg-muted-foreground','bg-warning','bg-destructive'][i]} style={{flex:n}}/>)}</div><p className="text-ui-meta">满分 {q.distribution[0]} · 部分 {q.distribution[1]} · 零分 {q.distribution[2]}</p><Badge variant="outline">待复核 {q.pending}</Badge><section className="space-y-2"><h3 className="flex items-center gap-2 text-ui-action"><Sparkles className="size-4"/>主要失分原因 <span className="text-ui-meta text-muted-foreground">AI 归纳</span></h3><ul className="space-y-2 text-ui-meta text-muted-foreground">{stats.reasons.map(r=><li key={r.text}>{r.text} · {r.count} 人</li>)}</ul></section></>}
 <div data-related-knowledge><p className="text-ui-meta text-muted-foreground">关联知识点</p>{knowledgeTags(related)}</div>
</>}</section>
 {a&&<section aria-label="当前学生作答" className="space-y-4"><h3 className="text-block-title">当前作答 · {a.student.name}</h3><div className="flex items-baseline gap-1"><span className="text-score-display">{a.score}</span><span className="text-ui-body text-muted-foreground">/ {q.max}</span><Badge variant="outline" className="ml-auto">{a.status}</Badge></div><Badge variant="outline">{a.review}</Badge><ul className="space-y-4 text-ui-body">{q.points.map((p,i)=><li key={p.id} className="grid grid-cols-[1rem_minmax(0,1fr)_3rem] items-baseline gap-x-2 gap-y-1"><span aria-label={a.points[i].score===p.max?'达成':'未完全达成'}>{a.points[i].score===p.max?'✓':'×'}</span><span>{p.label}</span><span className="text-right tabular-nums">{a.points[i].score}/{p.max}</span>{a.points[i].reason&&<p className="col-span-2 col-start-2 text-ui-meta text-muted-foreground">缺失：{a.points[i].reason}</p>}</li>)}</ul><p className="text-ui-meta text-muted-foreground">{a.review==='已确认'?'教师确认后的评分依据':'评分依据待教师确认'}：{a.annotation}</p><section className="overflow-hidden rounded-lg bg-muted" aria-label="AI 判定依据"><div className="h-0.5" style={{background:'var(--brand-ai-gradient)'}}/><div className="space-y-3 p-4"><h4 className="flex items-center gap-2 text-block-title"><Sparkles className="size-4"/>AI 判定依据</h4><p className="text-ui-body">{a.annotation}</p><p className="text-ui-meta text-muted-foreground">置信度：未提供</p></div></section><Button variant="link" render={<a href={`/next/reviews/paper-review?question=${q.id}&student=${a.student.id}&source=question-review`}/>}>查看整卷 →</Button></section>}</div></Frame></ScrollArea></div><FrameFooter className="flex-row flex-wrap gap-2"><Button onClick={()=>onIntent('教师批阅')}>教师批阅</Button><Button variant="outline" onClick={()=>onIntent('更正评分')}>更正评分</Button></FrameFooter></aside>}
