"use client"
import {QuestionRailClass} from "@/components/prism-next/question-rail"
import {Tip,Rate,ThinBar} from '@/components/prism-next/question-analysis-parts'
import {StudentIdentity,StudentControlSwitcher,StudentControlScale,type StudentControlItem} from '@/components/prism-next/student-control-bar'

import {QuestionAnalysisPanel} from '@/components/prism-next/question-analysis-panel'
import {KnowledgeRail,KnowledgeEvidenceList,ReviewRailList,ReviewRailFilter} from '@/components/prism-next/knowledge-rail'

import { useLayoutEffect, useRef, type RefObject, type ReactElement } from 'react'
import { ChevronLeft, ChevronRight, PanelLeftClose, Sparkles } from 'lucide-react'
import { Button } from '@/components/prism-next/button'
import { Badge } from '@/components/prism-next/badge'
import { Badge as CossBadge } from '@/components/coss/badge'
import { Tabs, TabsList, TabsTab, TabsPanel } from '@/components/coss/tabs'
import { Select, SelectTrigger, SelectValue, SelectPopup, SelectItem } from '@/components/coss/select'
import { Tooltip, TooltipTrigger, TooltipPopup } from '@/components/coss/tooltip'
import { Kbd } from '@/components/coss/kbd'
import { Group, GroupSeparator } from '@/components/coss/group'
import { Combobox, ComboboxTrigger, ComboboxPopup, ComboboxInput, ComboboxList, ComboboxGroup, ComboboxGroupLabel, ComboboxCollection, ComboboxItem, ComboboxEmpty } from '@/components/coss/combobox'
import { Frame, FrameHeader, FrameFooter } from '@/components/coss/frame'
import { Meter, MeterTrack, MeterIndicator } from '@/components/coss/meter'
import { Avatar, AvatarFallback } from '@/components/coss/avatar'
import { ScrollArea } from '@/components/coss/scroll-area'
import { reviewQuestions, questionAnalyses, knowledgePoints, questionFilters, knowledgeFilters, filterQuestions, filterKnowledge, type ReviewQuestion, type Knowledge, type StudentAnswer } from './fixture'
import { questionSorts, sortQuestions, rateLabel } from './analysis'
export {Tip,Rate,ThinBar} from '@/components/prism-next/question-analysis-parts'
export function StudentLabel({answer:a}:{answer:StudentAnswer}){return <StudentIdentity item={studentControlItem(a,1)} className="flex items-center gap-2 py-2 text-ui-body"/>}
export function QuestionJump({current,open,onOpenChange,onSelect,triggerRef}:{current:ReviewQuestion;open:boolean;onOpenChange:(v:boolean)=>void;onSelect:(id:string)=>void;triggerRef:RefObject<HTMLButtonElement|null>}){
 const groups=['选择题','填空题','解答题'].map(value=>({value,items:reviewQuestions.filter(q=>q.type===value)}))
 return <Combobox items={groups} value={current} open={open} onOpenChange={onOpenChange} itemToStringLabel={q=>`第 ${q.number} 题 ${q.type} ${knowledgePoints.find(k=>k.id===q.knowledge)!.name}`} onValueChange={q=>{if(q)onSelect(q.id)}}>
 <Group className="ml-auto shrink-0" aria-label="题目导航"><Tip label="上一题" keys="["><Button variant="outline" disabled={current.number===1} onClick={()=>onSelect(reviewQuestions[current.number-2].id)}><ChevronLeft/><span className="d1-student-label">上一题</span></Button></Tip><GroupSeparator/><ComboboxTrigger ref={triggerRef} render={<Button variant="outline"/>} aria-label={`选择题目，当前第 ${current.number} / 20 题`}>{current.number} / 20</ComboboxTrigger><GroupSeparator/><Tip label="下一题" keys="]"><Button variant="outline" disabled={current.number===20} onClick={()=>onSelect(reviewQuestions[current.number].id)}><span className="d1-student-label">下一题</span><ChevronRight/></Button></Tip></Group>
 <ComboboxPopup finalFocus={triggerRef} className="surface-floating w-96 max-w-[calc(100vw-1rem)]" aria-label="题目跳转面板"><div className="space-y-2 border-b p-2"><label htmlFor="question-search" className="text-ui-action">搜索题号或知识点</label><ComboboxInput id="question-search" showTrigger={false}/></div><ComboboxEmpty>没有匹配的题目</ComboboxEmpty><ComboboxList>{(group:typeof groups[number])=><ComboboxGroup key={group.value} items={group.items}><ComboboxGroupLabel>{group.value}</ComboboxGroupLabel><ComboboxCollection>{(q:ReviewQuestion)=><ComboboxItem key={q.id} value={q}><div className="min-w-0 flex-1 space-y-1"><span className="block text-ui-body">第 {q.number} 题 · {q.type} · {knowledgePoints.find(k=>k.id===q.knowledge)!.name}</span><div className="flex items-center gap-2"><ThinBar value={q.rate}/><span className="text-ui-meta">{rateLabel(q)} {q.rate}% · 区分度 {questionAnalyses[q.id].d.toFixed(2)}</span></div></div></ComboboxItem>}</ComboboxCollection></ComboboxGroup>}</ComboboxList><p className="p-2 text-ui-meta"><Kbd>↑ ↓</Kbd>选择 <Kbd>Enter</Kbd>跳转 <Kbd>Esc</Kbd>关闭</p></ComboboxPopup></Combobox>
}
export const studentControlItem=(a:StudentAnswer,max:number):StudentControlItem=>({formValue:JSON.stringify(a),id:a.student.id,name:a.student.name,examId:a.student.examId,score:a.score,scoreText:`${a.score} 分`,status:a.status,review:a.review,ratio:a.score/max*100,identityTone:a.status==='满分'?'success':a.status==='零分'?'destructive':'warning',tickTone:a.status==='满分'?'neutral':a.status==='零分'?'destructive':'warning',group:a.review})
export function StudentJump({answers,current,max,open,onOpenChange,onSelect,triggerRef}:{answers:StudentAnswer[];current:StudentAnswer|null;max:number;open:boolean;onOpenChange:(v:boolean)=>void;onSelect:(id:string)=>void;triggerRef:RefObject<HTMLButtonElement|null>}) {
 const items=answers.map(a=>studentControlItem(a,max))
 return <StudentControlSwitcher items={items} current={items.find(a=>a.id===current?.student.id)??null} groups={['待复核','已确认'].map(value=>({value,items:items.filter(a=>a.group===value)}))} max={max} open={open} onOpenChange={onOpenChange} onSelect={onSelect} triggerRef={triggerRef}/>
}
export function StudentScale({answers,current,max,onSelect}:{answers:StudentAnswer[];current:StudentAnswer|null;max:number;onSelect:(id:string)=>void}) {
 const counts=['满分','部分得分','零分'].map(status=>answers.filter(a=>a.status===status).length)
 return <StudentControlScale items={answers.map(a=>({id:a.student.id,tone:studentControlItem(a,max).tickTone,tooltip:<>{a.student.name} · {a.score} / {max}</>}))} selected={current?.student.id} summary={<>{answers.length} 位学生：满分 {counts[0]}、部分 {counts[1]}、零分 {counts[2]}</>} onSelect={onSelect}/>
}
export const knowledgeEvidence=(k:Knowledge)=>k.evidence.map(e=>({...e,label:`第 ${reviewQuestions.find(q=>q.id===e.question)!.number} 题 · 评分点 ${e.points.map(p=>p.slice(1)).join('、')}`}))
export function EvidenceList({knowledge,onEvidence}:{knowledge:Knowledge;onEvidence:(question:string,points:string[])=>void}){return <KnowledgeEvidenceList items={knowledgeEvidence(knowledge)} onEvidence={onEvidence}/>}
export function QuestionKnowledgeRail({view,onView,question,knowledge,filter,onFilter,sort='number',onSort=()=>{},onQuestion,onKnowledge,onEvidence,onLocate,onCollapse,closeRef}:{view:string;onView:(s:string)=>void;question:ReviewQuestion;knowledge:Knowledge|null;filter:string;onFilter:(s:string)=>void;sort?:string;onSort?:(s:string)=>void;onQuestion:(s:string)=>void;onKnowledge:(s:string)=>void;onEvidence:(s:string,p:string[])=>void;onLocate:()=>void;onCollapse:()=>void;closeRef:RefObject<HTMLButtonElement|null>}){
 const root=useRef<HTMLElement>(null), list=view==='questions'?sortQuestions(filterQuestions(filter),sort,questionAnalyses):filterKnowledge(filter), selected=view==='questions'?question.id:knowledge?.id

 const filters=view==='questions'?questionFilters:knowledgeFilters
 const choose=(id:string)=>view==='questions'?onQuestion(id):onKnowledge(id)
 return <aside ref={root} data-review-rail aria-label="题目与知识点栏" className="d1-rail bg-background"><Tabs className="q1-rail-tabs" value={view} onValueChange={onView}><header className="d1-rail-header flex items-center justify-between gap-1 px-3"><TabsList size="sm" aria-label="浏览视角"><TabsTab value="questions">题目<CossBadge variant="outline">20</CossBadge></TabsTab><TabsTab value="knowledge">知识点<CossBadge variant="outline">18</CossBadge></TabsTab></TabsList><Tip label="收起题目栏" keys="T"><Button ref={closeRef} variant="ghost" size="icon" aria-label="收起题目栏" onClick={onCollapse}><PanelLeftClose/></Button></Tip></header>
 <div className="grid gap-2 px-3 pb-2"><ReviewRailFilter id="review-rail-filter" label={view==='questions'?'题目筛选':'知识点筛选'} value={filter} items={filters} onChange={onFilter}/>{view==='questions'&&<ReviewRailFilter id="review-rail-sort" label="题目排序" value={sort} items={questionSorts} onChange={onSort}/>}</div>
 <TabsPanel value={view} className="min-h-0"><ScrollArea overscrollContain><ReviewRailList items={list} selected={selected} onSelect={choose} label={view==='questions'?'选择题目':'选择知识点'} onLocate={focused=>{if(view==='knowledge'){const k=knowledgePoints.find(k=>k.id===(focused??selected));if(k){onKnowledge(k.id);const evidence=k.evidence[0];if(evidence)onEvidence(evidence.question,evidence.points)}}else{if(focused&&focused!==selected)choose(focused);onLocate()}}}>
 {view==='questions'?<QuestionRailClass bodyOnly sections={(sort==='number'?['选择题','填空题','解答题']:['排序结果']).map(type=>{const items=sortQuestions(filterQuestions(filter),sort,questionAnalyses).filter(q=>sort!=='number'||q.type===type),all=reviewQuestions.filter(q=>q.type===type);return {id:type,label:`${type} · ${items.length} 题`,summary:sort==='number'?`${Math.round(all.reduce((s,q)=>s+q.rate*q.max,0)/all.reduce((s,q)=>s+q.max,0))}%`:undefined,layout:sort!=='number'||type==='解答题'?'row':'cell',items:items.map(q=>{const stats=questionAnalyses[q.id],description=`第 ${q.number} 题，${q.type}，${rateLabel(q)} ${q.rate}%，平均分 ${stats.mean.toFixed(1)} / ${q.max}，区分度 ${stats.d.toFixed(2)} · ${stats.discrimination}`;return {id:q.id,number:q.number,tone:q.tone,value:`${q.rate}%`,ratio:q.rate,detail:`区分度 ${stats.d.toFixed(2)}`,kind:sort!=='number'?q.type:undefined,marker:stats.discrimination==='待改进',ariaLabel:description,tooltip:description}})}})} overview={{segments:[{count:6,tone:'warning'},{count:14,tone:'neutral'}],text:'高失分 6 · 其余 14'}} selected={selected!} onSelect={onQuestion}/>:<><KnowledgeRail bodyOnly sections={[...new Set(knowledgePoints.map(k=>k.topic))].map(topic=>({id:topic,label:topic,items:filterKnowledge(filter).filter(k=>k.topic===topic).map(k=>({...k,secondary:`受影响 ${k.affected} / 36 · ${k.evidence.length} 道证据题`,status:!k.sufficient?'继续观察':undefined,evidence:knowledgeEvidence(k)}))}))} selected={selected} onSelect={onKnowledge} onEvidence={onEvidence}/></>}
 {!list.length&&<p className="text-ui-body text-muted-foreground">没有符合筛选的条目</p>}</ReviewRailList></ScrollArea></TabsPanel></Tabs></aside>
}
export function QuestionInspector({question:q,answer:a,knowledge:k,onKnowledge,onEvidence,onIntent}:{question:ReviewQuestion;answer:StudentAnswer|null;knowledge:Knowledge|null;onKnowledge:(s:string)=>void;onEvidence:(s:string,p:string[])=>void;onIntent:(s:string)=>void}){const stats=questionAnalyses[q.id];const related=[...new Set(q.points.flatMap(p=>p.knowledge))];return <aside className="d1-inspector min-h-0 bg-background" data-review-inspector aria-label="题目与作答检查器"><FrameHeader className="d1-inspector-header justify-center px-4 py-0"><h2 className="text-block-title">{k?`知识点 · ${k.name}`:'本题分析'}</h2></FrameHeader><div className="min-h-0 overflow-hidden px-4 pb-4"><ScrollArea overscrollContain scrollFade><Frame><div className="space-y-7 px-4 py-5"><QuestionAnalysisPanel knowledge={k?{...k,status:!k.sufficient?'继续观察':undefined,evidence:knowledgeEvidence(k)}:null} total={36} kind={q.type} max={q.max} statistics={{mean:stats.mean.toFixed(1),sd:stats.sd.toFixed(1),d:stats.d.toFixed(2),discrimination:stats.discrimination,fullRate:stats.fullRate,zeroRate:stats.zeroRate}} distribution={q.distribution} affected={q.affected} rate={q.rate} pending={q.pending} insight={(()=>{const o=stats.options?.find(o=>o.label===stats.distractor);return o?`主要干扰项 ${o.label}：${o.count} 人，高分组 ${o.high} · 低分组 ${o.low}`:undefined})()} errorAnswersSlot={stats.errorAnswers?<ul className="space-y-2 text-ui-body">{stats.errorAnswers.map(g=><li key={g.text}>{g.text} · {g.students.length} 人</li>)}</ul>:undefined} reasons={stats.reasons} related={related.map(id=>knowledgePoints.find(k=>k.id===id)!)} onKnowledge={onKnowledge} onEvidence={onEvidence}/>
 {a&&<section aria-label="当前学生作答" className="space-y-4"><h3 className="text-block-title">当前作答 · {a.student.name}</h3><div className="flex items-baseline gap-1"><span className="text-score-display">{a.score}</span><span className="text-ui-body text-muted-foreground">/ {q.max}</span><Badge variant="outline" className="ml-auto">{a.status}</Badge></div><Badge variant="outline">{a.review}</Badge><ul className="space-y-4 text-ui-body">{q.points.map((p,i)=><li key={p.id} className="grid grid-cols-[1rem_minmax(0,1fr)_3rem] items-baseline gap-x-2 gap-y-1"><span aria-label={a.points[i].score===p.max?'达成':'未完全达成'}>{a.points[i].score===p.max?'✓':'×'}</span><span>{p.label}</span><span className="text-right tabular-nums">{a.points[i].score}/{p.max}</span>{a.points[i].reason&&<p className="col-span-2 col-start-2 text-ui-meta text-muted-foreground">缺失：{a.points[i].reason}</p>}</li>)}</ul><p className="text-ui-meta text-muted-foreground">{a.review==='已确认'?'教师确认后的评分依据':'评分依据待教师确认'}：{a.annotation}</p><section className="overflow-hidden rounded-lg bg-muted" aria-label="AI 判定依据"><div className="h-0.5" style={{background:'var(--brand-ai-gradient)'}}/><div className="space-y-3 p-4"><h4 className="flex items-center gap-2 text-block-title"><Sparkles className="size-4"/>AI 判定依据</h4><p className="text-ui-body">{a.annotation}</p><p className="text-ui-meta text-muted-foreground">置信度：未提供</p></div></section><Button variant="link" render={<a href={`/next/reviews/paper-review?question=${q.id}&student=${a.student.id}&source=question-review`}/>}>查看整卷 →</Button></section>}</div></Frame></ScrollArea></div><FrameFooter className="flex-row flex-wrap gap-2"><Button onClick={()=>onIntent('教师批阅')}>教师批阅</Button><Button variant="outline" onClick={()=>onIntent('更正评分')}>更正评分</Button></FrameFooter></aside>}
