export type AgentSpec = {
  component: string
  source: string
  contract: string[]
  states?: string[]
  accessibility?: string[]
  do?: string[]
  dont?: string[]
}

export const coreAgentSpecs: Record<string, AgentSpec> = {
  'agent-components': {
    component: 'Agent semantic group / record views / exception handler / evidence drilldown / item reviewer / document workspace / file input / collection basket / object viewer / scope builder v0.1 — design candidate',
    source: 'Prism / coss composition; interaction reference: https://www.beautifului.dev/',
    contract: [
      "AgentScopeBuilder (semantic 02, components/prism-next/agent-scope-builder.tsx) declares Inline + dedicated workspace content. view=inline|workspace defaults inline; density=default|compact defaults default and is not a third state. Builds the set of participating objects; execution/result rules belong to semantic 08. Scope selection never grants access, and unspecified scope never means all authorized data. Reuse TextbookRangePicker, TextbookDirectory/Tree, FilterBar and Calendar/Popover via controlled editor slots, with Card, Prism Badge/Button and RecordDetails. No new selector, catalog entry, dependencies, visual tokens, business types, store, routing, executor or persistence.",
      "Scope required props: title, scope={scopeId,version}, readonly dimensions, summary:string|null and confirmation. Scope/dimension IDs and revision references are opaque event associations, never labels or DOM attributes. Available dimensions={id,label,required,core?,access:available,source:{label,options:unknown},value:unknown,summary:string|null,validation:{state:valid|conflict|unavailable,reason},disabledReason?,renderEditor?,renderInlineEditor?}. Values/options stay opaque; no normalization, default value, cache, implicit full selection, validation computation or permission inference. Required missing values must be marked conflict by the host. summary blank/null explicitly means unspecified.",
      "Restricted scope dimensions={id,label,required,core?,access:restricted,validation:{state:out-of-scope,reason,count?}} accept only permitted dimension labels/reasons/counts, never private value/source/options/summary/editor fields. Runtime also ignores injected payloads, including contradictory available access with out-of-scope validation. Every string, aggregate, exclusion, source label, detail and slot must already satisfy current disclosure permissions. impact?:string displays only a host-calculated authorized scale, never a count inferred from dimensions or options. exclusions?:{reason,count?}[] only disclose approved reasons/nonnegative integer counts; absent counts are not invented and zero stays zero.",
      "Scope inline shows core dimensions plus all non-valid/restricted/disabled dimensions and only explicitly supplied renderInlineEditor controls. Missing onExpand hides Adjust full scope and preserves all dimension summaries; workspace renders the complete list with source labels and renderEditor. Editor receives {value,options,onChange,controlId,labelledBy,describedBy}; onValueChange emits {scopeId,version,dimensionId,value} unchanged, including empty/undefined values. No editor mounts without a receiver or for unavailable/restricted/disabled input. Conflict remains editable. Host adapters use fixed labels and existing accessible controls, resolve TextbookRangePicker functional updates against current values, and invalidate staged picker drafts when object/revision changes; Apply selection is not Agent confirmation.",
      "confirmation=unconfirmed(reason?)|confirmed(version,reason?)|changed(reason) is external. Changed or a different confirmed revision displays 范围已变化，需重新确认 without changing values. onConfirm({scopeId,version}) only requests confirmation; a click/return value never records success or starts analysis/retrieval. Empty summary/dimensions, missing scope identity/revision, any non-valid validation and disabled reasons block and guard confirmation; confirmed is displayed only with matching revision and no confirmation blocker. Host synchronizes selection, legal options/permissions, revision, summary/impact and confirmation on critical change, then rechecks current authorization and scope/version when receiving requests. Frontend guards are not authorization.",
      "Scope workspace onReset/onRestoreDefaults emit the current target only, never clear or choose defaults or alter confirmation. disabledReason blocks editing and all mutation intents; confirmDisabledReason only blocks confirmation. onExpand(trigger) and onBack are navigation only, retaining host-owned values/revision and restoring focus. notice allows one persistent boundary hint and details holds supplemental prose; compact preserves all conflicts, access/unavailability reasons, exclusions, impact and changed/disabled facts. #scope-builder has analysis and lesson-resource fixtures with three presentations, an undisclosed unauthorized class, unavailable resource directory, 320px, long Chinese and math. Confirmation/reset requests and manual fixture record loading are separate. SSR/callback tests do not establish browser or Workspace acceptance; P04 deduplicate/blurry are constraints, not a reason to reclassify semantic 02.",
      "AgentObjectViewer (semantic 14, components/prism-next/agent-object-viewer.tsx) declares Inline + generic workspace container; domain slots can be specialized. AgentArtifactPreview (13) is the result-summary card and opening entry; ObjectViewer presents the opened object. Reuse QuestionCard/QuestionDetails and DocumentRegionViewer as read-only slots, not a shared domain model. No catalog entry, dependencies, visual tokens, store, routing, executor, permission service or persistence.",
      "Required object={id,type,name,displayId?}, version={id,label,state:current|historical,currentLabel?,difference?}, access={state:available,scope,readOnlyReason?}|{state:restricted,reason}, sections and controlled activeSection:string|null. IDs are callback references only, never visible text, DOM attributes or fallback labels; only explicit displayId renders a number. Names, labels, source, relations and differences must already be authorized. Missing source or version label stays unconfirmed. Display only the supplied difference; opening never creates read/citation/model-context facts.",
      "Object sections use unique stable IDs: available={id,title,access?:available,summary?,content,sensitive?:{reason}} or restricted={id,access:restricted,disclosure:{label,reason}}. Runtime restricted branches ignore injected private fields and render no slots. Sensitive summary never mounts; content mounts only after the explicit Confirm view trigger on a local coss Collapsible, with no keepMounted/hiddenUntilFound. Directory navigation or full-view expansion cannot confirm answers. Object/version/state/visible-scope changes reset disclosure; restricted or changed sensitive sections remount. Confirmation is view state, never authorization. All slots must be permitted read-only content; do not bypass actions with embedded writes. QuestionDetails archive displays question.id, so omit archive or provide safe readable domain metadata.",
      "view=inline|workspace defaults inline; density=default|compact defaults default, not a third state. Inline shows first inlineLimit=1|2 (default 2) non-sensitive supplied summaries, with local entry for every section even without onExpand. Workspace has full sections, a generated-anchor directory and host-controlled activeSection; onNavigate(sectionId,trigger) only requests, prop changes scroll without inference. versions={id,label,state,disabledReason?} and onVersionChange({objectId,versionId,targetVersionId},trigger) only display in workspace with capability; no local version substitution. relations={id,relationship,name,openable?} need openable and onOpenRelation({objectId,versionId,relatedObjectId},trigger) for an entry.",
      "Object actions={id,kind:add-to-collection|review|drilldown,label,disabledReason?} with onAction({objectId,versionId,actionId,kind},trigger) emit only registered intents; absent receiver or unrecognized kind has no entry. Disabled reasons are persistent and guarded. Historical versions explicitly display 当时版本 and read-only; historical/readOnlyReason suppress collection/review actions, retain viewing and evidence navigation. Whole-object restriction preserves permitted identity/version/reason/return only, never source/differences/slots/relations/details/actions or expansion. Host revalidates current permissions even for history and fulfills version-bound requests.",
      "onExpand(trigger) provides 查看完整 only in inline with identified available object; onBack only returns. notice permits one standing boundary hint; supplementary prose goes to details, never restriction/history/sensitive confirmation/version differences or disabled reasons. Compact preserves those facts and reading typography. #object-viewer shows question and student-response fixtures with three presentations, explicit answer confirmation, restricted parent contacts, 320px and formulas; manual fixture version loading is separate from the request. Component tests do not establish browser or Workspace acceptance.",
      "AgentCollectionBasket (semantic 11, components/prism-next/agent-collection-basket.tsx) declares Inline + dedicated workspace content. Required collection={id,title,type,version?,source?,snapshot?}, readonly items and summary={count:number|null,unit?,fields?:{label,value:string|number}[]}; optional groups={id,label,count:number|null}[]. All totals, group counts and scores are host values, never calculated from items. Null means unconfirmed, zero stays zero. view=inline|workspace defaults inline; density=default|compact defaults default and is not a third business view. No store, Provider, persistence, business scoring, routing, class handoff, publication, dependencies, visual tokens or catalog entry.",
      "Collection entries={id,title,type,access?:available,source?,version?,groupId?,summary?,fields?,issue?,selectable?,actions?}. issue={state:invalid|conflict,reason} is a host fact with a persistent reason. Restricted entries accept only id/access=restricted/disclosure={label,reason}/actions={remove?,resolve?}; injected private fields, metadata, grouping, selection and renderer content are ignored. Collection identity, aggregate counts, changes and details must also be pre-authorized by the host. Optional workspace renderItem(entry,{density}) composes permitted passive content such as QuestionCard summaries; never execute writes or disclose private data through slots. QuestionWorkPanel remains an optional Drawer shell, not another basket. Workspace uses its existing single right pane and unique TeacherQuestionBasket Provider.",
      "Collection sync defaults unknown: local/synced/failed/unknown display 本页暂存/已同步/同步失败/状态未确认; failed requires description, other descriptions optional, action optional. changes={id,kind:added|removed,description}[] display host-supplied change facts only. Clicks, callback returns, elapsed time and animations never alter facts. collection.snapshot presence marks then-version and read-only actions/selection, including an empty snapshot label. Missing source/version remains unconfirmed, not backfilled from current collection or contents.",
      "Inline shows first inlineLimit (default 3, finite integer >=1) plus every invalid/conflicting/restricted item, preserving host order. Without onExpand, all entries stay accessible with no Manage all entry; onExpand(trigger) requests the same collection only. Workspace displays full list, controlled groupBy=none|group/onGroupByChange, selectedIds/onSelectionChange, host-defined batchActions and optional onBack. Group view preserves within-group order plus ungrouped/unresolved/restricted buckets and disables reordering with a visible reason. Compact only adjusts spacing; issues, access reasons, unknown/failing sync and disabled reasons remain outside collapsed details. notice allows one standing boundary hint; supplementary text belongs in details.",
      "Collection entry actions explicitly declare remove, independent move.up/move.down, group={options:{id:string|null,label}[],disabledReason?}, and resolve={id,label,disabledReason?}[]. Touch/keyboard use persistent navigation-sized up/down buttons with actual adjacentId; endpoints are guarded. Group options are controlled, unknown requests ignored. Clear is workspace-only; destinations appear in both views with one primary action. onAction(intent,trigger?) binds collectionId/collectionVersion and remove/move/group/resolve itemId/version; move adds direction/adjacentId, group adds groupId, resolve adds actionId. Clear/destination/batch carry actionId and targets={itemId,version?}[]; sync carries actionId. Missing onAction and disabled reasons visibly block and guard callbacks. Destination requests never imply a created paper or published task.",
      "Batch actions={id,label,itemIds,disabledReason?} define exact host scopes; nonempty unique targets must all exist, be selectable and exactly match controlled selectedIds. Block invalid scopes as a whole, never silently narrow; emit original target order with supplied versions. Stale selection remains visible and can be cleared; selection counts are view state, not business totals. Host-registered action IDs define business meaning, not button labels; host must authorize every target, respect per-item restrictions for bulk/clear/destination actions and revalidate versions, concurrency, permissions and confirmations. Collection-level targets are the complete supplied items, not unseen members inferred from summary.count. #collection-basket provides question and image/video/article preparation fixtures, inline/workspace/compact, manual sync and 320px; component tests do not establish browser, Workspace or service acceptance.",
      "For file selected state, local source displays 已选择（仅本机） and existing source displays 已选择（已有资料）. Selecting an existing resource reference, including P04 attached=true, never creates received/uploaded or a synthetic upload request. Group headings use the shared selected label; the row retains the source distinction.",
      "AgentFileInput (semantic 04, components/prism-next/agent-file-input.tsx) declares Inline + dedicated workspace content. Required title/items/limits={accept,acceptLabel,maxFileSize,maxFiles}/capabilities/onSelect. Native accessible file input and capability-enabled drop only emit onSelect(File[]), preserving every selected file for host validation; empty selection emits nothing and the native input is cleared. No file content reads, uploads, persistence, global File cache, dependencies or catalog entries. Limits are host-owned positive bytes/count; accept is a picker hint, never security validation. select requires supported; upload/drop use supported or limited/unsupported with required reason. Unsupported upload is explicitly unconnected; touch always has the equivalent file picker.",
      "File items={id,name,type,sizeBytes?,source:{kind:local|existing,label?},version?,status,processing?,actions?,details?,preview?} contain only host-permitted metadata. status selected/invalid/queued/received/uploading/uploaded/failed/unknown/removed are separate facts. invalid requires validation=type|size|count and reason; received/uploading require original request={id,label}. Only finite supplied upload progress in [0,100] renders a percentage; absent/invalid progress stays unconfirmed and 100 never means uploaded. Uploaded time/version remain unconfirmed if absent. processing={label,description?} is independent: upload is not reading, parsing, model context or citation.",
      "File actions remove/replace/move are declared per item, with disabledReason when unavailable. onAction emits fileId/version and a registered kind; move also direction/adjacentId, retry original requestId when supplied, query mandatory original requestId. failed may supply retry; unknown requires request/reason and admits query only, including at runtime against injected actions. Removed entries have no mutation actions. Unsupported upload blocks retry. Empty request IDs or absent receivers disable actions with visible associated reasons. Host enforces permissions, ownership, version, request identity/idempotency, replacement and restoration; callbacks never mutate facts.",
      "File view=inline|workspace defaults inline; density=default|compact only changes spacing. Inline defaults to 3 records plus every invalid/failed/unknown record. With onExpand and more records than the threshold, Manage all emits the trigger; without onExpand the entire queue stays accessible and no expand entry appears. Workspace renders full queue, optional controlled groupBy=none|status, host-scoped batch operations, passive file details/preview and up/down ordering. Status grouping disables reorder with reason; adjacent unknown cannot be reordered indirectly. batchActions={id,label,kind:remove|upload|retry,fileIds,disabledReason?} emit exact target IDs, never a filtered subset. Missing/duplicate/unknown/removed targets block the entire batch; upload only selected/queued, retry only explicit enabled failed.retry; per-item removal restrictions remain. Unregistered batch kinds are ignored.",
      "File input has one optional notice; supplementary prose goes to collapsed details, critical capability/error/unknown/disabled facts stay visible. Slots cannot bypass query-only restrictions. Composer conversation.attachments can contain compact AgentFileInput and tools can open the same host queue; current default/compact Composer branches do not render those slots. Queue buttons never submit the Composer form. Read-only/running slot capabilities must be set by the host. #file-input shows scan image/PDF and Word/Excel preparation fixtures, inline/workspace/compact and 320px; real local selections undergo demo-host metadata checks only, real upload remains unconnected. Component tests and offline rendering do not establish Workspace or service acceptance.",
      "AgentDocumentWorkspace (semantic 28, components/prism-next/agent-document-workspace.tsx) declares Inline + dedicated workspace content. Required document={id,title,version,format,contentScope,source?,snapshot?,currentVersion?}, capabilities, sections and activeSection reference host-owned data. view=inline|workspace defaults inline; density=default|compact defaults default. Inline uses only the supplied preview={kind:summary|excerpt,range,content}; no automatic excerpts or read/citation inference. Workspace reads all provided sections and a nested heading directory, edits the active chapter and displays annotations. No catalog entry, dependencies, format AST, Office editor, store or persistence.",
      "All four capabilities view/edit/annotate/export are mandatory: supported may have reason; limited/unsupported require reason. Each requires conversion={state:none} or {state:lossy|unknown,description}. Limitations and lossy/unknown conversion risks stay visible in every density. Unsupported capability or missing callback produces no executable entry. Unsupported view hides preview, sections, draft, annotations, quick actions and expansion. Plain strings are escaped text, not HTML/Markdown; host-rendered ReactNode can supply existing math renderers. Slots must respect authorization and historical read-only boundaries.",
      "Document sections={id,title,content,children?} use unique stable IDs. activeSection is controlled (string|null); onNavigate(sectionId,trigger) is an intent, not a selection mutation. A confirmed prop change scrolls to the chapter without generating read/citation facts. Arrow/Home/End move directory focus; Enter/Space requests navigation. Narrow containers use coss Collapsible; no invented tree engine. draft={baseVersion,values,onChange,readOnlyReason?} is controlled per chapter, with no initial copy or persistence. onChange({documentId,version,baseVersion,sectionId,value}) preserves exact input. Missing values do not initialize from reading content. Host keeps draft and read rendering synchronized, owns leaving/recovery and checks concurrency.",
      "Document save={state:unsaved|saved-draft|submitted|conflict|unknown,description?} is exclusively a host fact, default unknown; events never save or submit. Conflict preserves the draft; host may lock editing using readOnlyReason. document.snapshot presence marks a historical read-only version: no draft or edit/annotate action even if passed, only version-bound viewing/export and navigation. Do not fill historical content or saving facts from currentVersion. annotations={id,version,anchor:{sectionId,paragraph?},author,time?,state:open|resolved|unknown,content} retain their own records; missing time stays unknown. onAddAnnotation({documentId,version,sectionId}) only requests a host annotation composer, never appends a record; paragraph targeting stays in that composer.",
      "Document quickActions={id,label,capability,disabledReason?} use only registered capability kinds; onAction({documentId,version,actionId,capability}) is version-bound intent. Disabled reasons stay visible and handlers guard execution. onExpand(trigger) only exposes Open document in inline with actual view capability; absent callback means no entry. onBack is navigation only. notice is at most one persistent boundary hint; extra prose goes to details, never critical scope, risks or saving facts. /next/components/agent-components#document-workspace has five-stage lesson outline and read-only PDF excerpts (limited annotations, unsupported export), clearly labelled fixtures. Browser and Workspace acceptance remain separate from component tests.",
      "AgentItemReviewer (semantic 17, components/prism-next/agent-item-reviewer.tsx) declares Inline + dedicated workspace content. AgentItemReviewerProps<T=string> requires item={id,title,version}, review, checkpoints:string[] and summary. view=inline|workspace defaults inline; independent density=default|compact defaults default. Inline keeps identity, review basis, all checkpoints, current value and supplied quick actions. Workspace adds evidence, controlled editing, original-value comparison, reason and then-records. Compact never hides unknown, expired, unsaved or disabled facts and never shrinks text. No catalog entry, business model, scoring schema, store, persistence or executor is added.",
      "AgentItemReview is a discriminated host fact with required description. waiting-human/draft/failed may receive actions; draft explicitly says unsaved. waiting/unknown require request={id,label} and may receive query only. resolved requires resolution={reviewer,version,time?}; absent time stays unconfirmed, never client time. expired admits no old action. Runtime also rejects injected actions on waiting/unknown/resolved/expired. Optional versionChange={currentVersion?,description?} explicitly expires any old confirmation, even resolved, preserving basis, draft, reason and prior receipt. Concurrent expiry and waiting/unknown retain both facts and only the original query; restart is unavailable until the in-flight request is resolved.",
      "Review actions={id,label,impact,disabledReason?} are host-registered capabilities. onAction emits {kind:review,itemId,version,actionId}, {kind:query,itemId,version,actionId,requestId}, or {kind:restart,itemId,version,actionId,currentVersion?}. Optional restart is shown only for expired items without an in-flight request. No callback creates a receipt, history entry, saved state or cleared reason. Missing identity/version/callback or disabledReason visibly blocks actions; missing original request blocks querying. The trusted host validates ownership, permissions, version, scope and idempotency. Missing onExpand has no entry; unknown suppresses expansion. Workspace onBack is pure navigation, including unknown; host protects unsaved inputs and restores focus.",
      "draft={value:T,onChange,render} is entirely controlled. render receives the exact value, a guarded onChange, readOnly and describedBy. reason={value,onChange} uses a fixed-label controlled Textarea with no trimming/reset. Editing is blocked for waiting/unknown/resolved/expired, version changes and disabledReason; domain fields must honor readOnly and use the supplied callback. Generic scoring remains a domain slot. evidence/comparison/summary/details are already-authorized passive business content and must not introduce submit/retry/adoption bypasses; view interactions such as source navigation remain distinct from review facts. One notice is allowed; details holds collapsed supplementary copy, never critical facts.",
      "history records={id,item,state,description,reviewer?,time?,resultVersion?,reason?,request?} preserve their own then-identity/version/reviewer/time/reason/request and input order, with no actions or backfilling from current facts. QuestionReview is deliberately not composed: question-review.tsx:39 writes saved/record and clears reason directly on confirmation before onConfirm; lines 36/40 present recorded score/history. This legacy behavior is unchanged and assigned to Supervisor follow-up. VerificationFields and PointsField are safe controlled starting points; AgentChangeReview/AgentChangeSet adoption is a distinct host decision. Demos at #item-reviewer use P04 original-versus-question and single-answer scoring, manual receipt selection, 320px, long Chinese/math and all three presentations. Existing P04 checked is only a local comparison marker, not a resolved review or saved receipt. Real integration belongs at Workspace /teacher/agent/workspace.",
      "AgentEvidenceDrilldown (semantic 21, components/prism-next/agent-evidence-drilldown.tsx) declares Inline + dedicated workspace content. view=inline|workspace defaults inline; independent density=default|compact defaults default. Required conclusion={id,statement,version?,snapshot?,summary?,evidenceCount?,coverage?} and nodes form one externally owned conclusion/object/evidence tree. evidenceCount and coverage are displayed only when supplied, never computed from node counts; coverage=complete|incomplete|unavailable|unknown, known gaps must be supplied as incomplete. Inline shows the first two permitted evidence entries in host order plus all omitted incomplete/unavailable/unknown/preview-unavailable/access limitations; missing onExpand hides the entry and preserves all summaries. The host must keep other decision-critical evidence in summary or the first two entries. Compact changes spacing and wrapping only.",
      "Evidence objects={kind:object,id,title,type,version?,location?,summary?,children,openable?}; evidence items={kind:evidence,id,title,type,source,facts,relation,summary?,preview?,previewUnavailableReason?,openable?}. source={objectId,label,location,version?,snapshot?}; snapshot marks then-version, never backfilled from the current object/conclusion. relation=supports|counterexample|pending is independent of usage facts. facts is a parallel collection of read/cited/not-read/not-cited/retrieval-only/preview-only/incomplete/unavailable/unknown. read requires a scoped description; cited requires description and output version/location, separately from source.version. Negative facts require complete verified record coverage in the host. Every fact may retain its own version/location; empty facts means no supplied fact records, not absence of events. No read, reference, citation, correctness or sufficient-coverage inference from any other fact or interaction.",
      "Evidence path is a controlled readonly ID array, default [], traversing child nodes from the conclusion. onNavigate(path,trigger) requests entry, parent or breadcrumb navigation without local mutation; missing callback leaves a readonly selected level. Missing paths explain the unavailable position without showing an unrelated preview, and can request the nearest supplied ancestor. onExpand(trigger) is inline-only; workspace onBack returns to the original host location. onOpen({kind:object|evidence,conclusionId,nodeId,path},trigger) appears only when supplied and node.openable=true. The host resolves versions, permissions, fetching, focus/scroll and return state; these requests never modify evidence or create a second task model.",
      "Restricted evidence/object nodes={id,kind,access:restricted,disclosure:{label,reason}} accept only explicitly disclosable information. Runtime ignores accidentally supplied title/source/version/facts/preview/children/openable on restricted nodes, and never traverses their descendants. This is display of an authorization result, not authorization itself. Selected workspace evidence accepts a passive domain preview such as DocumentRegionViewer; previewUnavailableReason suppresses mounting that preview. Usage-record availability is independent of preview capability. One optional notice is the standing boundary explanation; details is collapsed supplementary content and may not hide necessary facts or bypass actions. Demos at #evidence-drilldown use DiagnosisEvidenceTable as an entry, AgentContextList source rows and DocumentRegionViewer regions; scan correction and learning diagnosis are labelled fixtures, not real OCR/diagnosis records or Workspace acceptance.",
      "AgentExceptionHandler (semantic 18, components/prism-next/agent-exception-handler.tsx) declares Inline + dedicated workspace content. view=inline|workspace defaults inline; independent density=default|compact defaults default. title/items are required; item={id,title,kind,scope,retained,basis,disposition,critical?,disabledReason?,evidence?,history?}. kind=low-confidence|conflict|missing|unparseable is an external fact, not a local detector. Inline shows the first inlineLimit (default 2, normalized to a positive integer) plus all critical/failed/waiting items in input order. Missing onExpand retains all items and hides the entry; any unknown suppresses expansion and retains the full list. Workspace exposes all evidence, rules and then-records. Compact never reduces text sizes or hides unknown/failure/disabled/impact facts.",
      "Exception disposition requires description and state=waiting-human|waiting|unknown|resolved|failed|ignored|skipped. waiting/unknown require request={id,label} and accept only optional query; actions are prohibited by the type and ignored at runtime. Other states accept optional actions. resolved/ignored/skipped require resolution={method,time?}; absent time is explicitly unconfirmed, never read from the client clock. Shared waiting/unknown/failure badges use AgentStepStatus vocabulary; resolved, ignored and skipped stay distinct and never imply task completion.",
      "Exception actions are host-registered {id,label,impact,disabledReason?}. onAction emits only {kind:handle,exceptionId,actionId} or {kind:query,exceptionId,actionId,requestId}; callbacks do not update facts, append history or decide recoverability. Group, item and action disabled reasons are visibly associated and guarded; missing callback or missing original query request disables the capability with a reason. onExpand(trigger) only requests a view; workspace onBack is optional pure view navigation, including unknown, never a disguised recovery/cancel/submit. The host checks owner, task/run/object/version, permission, request state and idempotency.",
      "Exception evidence={id,label,location,version?,preview?,unavailableReason?} is passive and already authorized; unavailableReason suppresses the preview, absent version/preview is explicit. Viewing never creates read/reference evidence. History={id,state,description,scope,basis,method?,time?,request?} is rendered from each then-snapshot with no actions or current-value backfill. notice permits at most one standing boundary explanation; details is collapsed supplementary text. preview/details must not bypass the action union with interactive business controls. Demos at #exception-handler cover P04 blurry scans and question conflicts/missing answers, three presentations, seven manually supplied states, 320px, long Chinese and math; they are not execution receipts or Workspace acceptance.",
      'AgentExecutionProgress (26), AgentExecutionResult (27), and AgentContextSummary (03) support Inline + generic workspace content via view=inline|workspace (default inline); density=default|compact is an independent layout setting, default default, not a third state. Existing presentation=card|inline still controls the frame only. Old calls match 28 pinned main e99813a SSR snapshots. All views consume the same external facts; no truncation, execution, persistence or inferred transitions. Optional onExpand(trigger) exposes More only in inline when available; workspace never creates its own shell. Optional details is supplementary, collapsed Explanation; uncertainty, failure and unavailable facts stay visible. State and explanation type roles never shrink in compact rows.',
      'Progress adds run={id,label,version?}, stages={id,title,state,time?,description?,steps}[], exceptions={id,title,description,time?,resolution?}[], history={id,label,version?,state,description,updatedAt?,steps,stages?,exceptions?}[], and snapshot?. AgentStep.time is optional; AgentTaskProgress.density defaults to default. Missing updatedAt/run/stage time or resolution remains unconfirmed. Only a current running round without snapshot may be live, and a nested stage also requires running. All history is marked then and snapshot, including formerly running stages, without animation or aria-current. Workspace/compact expose steps regardless of expanded; inline retains the original controlled disclosure.',
      'AgentStep.state accepts done/running/pending/error/unknown/waiting-human/waiting/partial. Unreached steps must remain pending; an occurred or submitted step without a receipt is unknown (unconfirmed) or waiting (explicitly awaiting receipt/processing), never pending. waiting-human means currently awaiting teacher handling; partial preserves completed and remaining scope in detail. Step labels reuse agentProgressLabels, mapping done to completed and preserving the legacy error label 失败. New states use the existing warning Badge and static row glyphs: unknown CircleHelp, waiting Clock3, waiting-human/partial CircleAlert. Snapshot preserves every non-running state; only running changes to 上次进行到 with outline/Circle. New states never animate or claim aria-current. Overall state remains independent. Old four-state output matches 25 pinned main 0a19ff7 SSR snapshots across statuses, lists, stages, history, views and densities.',
      'Result adds receipt.record={request,run,version?,receivedAt?}, outputs={id,title,version,status,open?}[], and failures using AgentExecutionIssue. Scope remains completed/remaining from an explicit succeeded/partial/failed receipt; output existence does not establish success. Missing open has no entry; disabledReason is visibly associated. Unknown permits only receipt.query for the original request, suppressing output open, next, secondary and onExpand even from untyped input. children is a passive compatibility slot and must not bypass this rule with actions. No receipt polling, permission or idempotency implementation is included.',
      'Context adds source.version, selection=unavailable, selectionDetail={description?,version?,location?}, and independent fact.version/location. Selection, reading, Agent reference for this run, and output citation remain separate. confirmed requires a description; absent requires complete verified coverage; incomplete records are unknown and unavailable records remain unavailable. Citation location/version identifies the output, not a guessed source. Workspace/compact show all source details without expanded. onInspect is a supplied capability, never evidence. The host validates task/run/source/version/output correspondence.',
      'New record-view fields default to omitted. Demos contain two explicitly labelled uses (P04 scan organization and lesson-material organization), three presentations, narrow containers and long Chinese/math. Real integration is verified at Workspace /teacher/agent/workspace; SSR or the historical skeleton is not acceptance. Execution confirmation (25) remains Inline only.',
      'AgentChangeSet (semantic 15) supports view=inline|workspace with the same host items and decisions; presentation remains unrelated. Required basis identifies source/version. Inline defaults to two items plus every critical or conflict item; without onExpand all items remain reachable and no expansion entry is shown. onExpand receives the trigger for host focus restoration. Item conflict={baseLabel,currentLabel,description?} and group notice only expose host facts, never auto-decide or disable. onDecision(id,pending|accepted|kept), onRewrite(id,value) and optional apply={label,onApply,disabledReason?} return intent only; the host owns drafts, freshness checks, application and saving. Group disabledReason blocks decisions, rewrites and apply; item disabledReason blocks that item; apply.disabledReason blocks application only. No accepted-count or conflict-based application rule is inferred. beforePreview/afterPreview remain host domain-rendering slots. Real integration is verified in Workspace /teacher/agent/workspace, never the historical skeleton.', 'AgentComposer scope is a host-provided slot. readOnly/sendDisabled default false; a nonempty sendDisabledReason also blocks form and keyboard submission. Read-only keeps the native draft readable; sendDisabled alone permits editing. The visible status reason describes both input and send button. Running stop behavior stays unchanged; slots remain host-owned.', 'AgentContextSummary composes AgentContextList; selection, read, current context and citation are independent host facts. confirmed requires a scoped description; absent requires complete host-verified coverage; unknown and unavailable stay distinct. Opening a source does not change facts.', 'AgentArtifactPreview receives object identity, version, status and optional open capability. Preview content never proves execution or publication.', 'AgentExecutionConfirmation receives a discriminated ready/submitting/received/blocked/unknown/recorded state. Only ready exposes confirmation. Callbacks return intent, not acknowledgements.', 'AgentExecutionProgress reuses AgentTaskProgress; overall state and expansion are external. Waiting/unknown renders old running steps as static snapshots, never ongoing activity.', 'AgentExecutionResult receives a succeeded/partial/failed/unknown receipt. Unknown exposes query only; partial preserves completed and remaining scope. Host capabilities determine recovery.', 'AgentChangeReview preserves controlled string input and adds optional version labels, scope, presentation slots and reset intent. Caller owns freshness, draft updates and saving. AgentQuestionCard remains controlled; choosing does not execute or save.'],
    states: ['valid/conflict/out-of-scope/unavailable scope validation; unconfirmed/confirmed/changed scope confirmation, version-bound intents', 'waiting-human/draft/waiting/unknown/resolved/failed/expired item review facts; independent host version-change guard', 'independent read/cited/not-read/not-cited/retrieval-only/preview-only/incomplete/unavailable/unknown evidence facts; supports/counterexample/pending relations; restricted disclosure; then-version snapshots', 'waiting-human/waiting/unknown/resolved/failed/ignored/skipped exception dispositions', 'draft/current/historical/unavailable preview', 'pending/accepted/kept or externally blocked comparison', 'ready/submitting/received/blocked/recorded/unknown confirmation', 'running/waiting/snapshot progress', 'done/running/pending/error/unknown/waiting-human/waiting/partial steps', 'succeeded/partial/failed/unknown receipt'],
    accessibility: ['Scope dimensions retain fixed labels and visible validation reasons; editor groups and action buttons reference descriptions. Compact does not hide conflicts or restricted content boundaries. Expansion carries the original trigger; focus restoration belongs to the host.', 'Item review actions include object titles and visible impact/disabled descriptions. Fixed-label controlled editors receive readOnly and status association. History is read-only and marked then; host owns expansion/return focus and unsaved-input protection.', 'Evidence breadcrumbs identify the current level; navigation/open names include object or evidence labels. The host receives triggers for focus restoration; incomplete/unavailable/restricted reasons remain visible in both densities. No hidden restricted descendants or previews are mounted.', 'Exception action names include their item title; impacts and disabled reasons remain visible and aria-describedby-associated. Current and then-records are labelled separately. Pure return navigation restores focus in the host.', 'Change decision and reset names include each item title; disabled reasons are visible and associated with controls.', 'Choices use the pinned RadioGroup and associated labels.', 'Decision information is at least 14px; long source and comparison text uses read-body 16/28.', 'Narrow containers wrap or stack; source dialogs return focus.'],
    dont: ['Do not put demo execution, business persistence or model calls in reusable components.', 'Do not treat selection or accepted changes as permission to publish.', 'Do not manufacture confidence, completion percentages or internal reasoning.'],
  },
  button: {
    component: "Button",
    source: "Pinned coss Button with components/prism-next/button adaptation; preserve upstream sizing, radius, padding and focus behavior",
    contract: ["One primary action per action region.", "Use native sizes; Prism Button additionally exposes navigation and navigation-icon with 40px desktop / 44px coarse-pointer targets. Default output is unchanged; icon buttons require an accessible name.", "Prism variant=info uses existing semantic info tokens for guidance and informational actions, composes with navigation sizes, and does not replace the default primary action hierarchy.", "Destructive actions use the destructive treatment and confirmation when impact warrants it."],
    states: ["default", "hover", "focus-visible", "active", "loading", "disabled"],
    accessibility: ["Preserve keyboard focus and loading/disabled semantics.", "Icon-only buttons require aria-label or equivalent accessible naming."],
    do: ["Use hierarchy before adding color.", "Keep coss interaction behavior intact."],
    dont: ["Do not invent new internal dimensions.", "Do not use Prism colors as decoration."]
  },
  toolbar: {
    component: 'Toolbar',
    source: 'Pinned coss Toolbar; optional Prism composition',
    contract: ['Prism variant defaults to framed with identical coss output. plain reuses the same Base UI root and children without the visual frame; no new tokens.'],
    accessibility: ['Preserve arrow-key navigation, ToolbarLink semantics and accessible naming.'],
  },
  'metric-summary': {
    component: 'MetricSummary',
    source: 'components/prism-next/data-display.tsx',
    contract: ['density defaults to default; compact changes only layout to two columns with baseline-aligned label/value. Preserve analytics-value typography, external detail and onSelect intent.'],
  },
  'status-composition': {
    component: 'StatusComposition',
    source: 'components/prism-next/data-display.tsx',
    contract: ['density defaults to default; compact uses a wrapping legend and an 8px read-only bar. An interactive bar stays 32px. Missing and invalid values retain existing semantics.'],
    accessibility: ['Compact read-only legends retain full quantity and percentage through accessible labels and titles. Interactive bars and legends remain keyboard-selectable.'],
  },
  question: {
    component: 'Question composition / QuestionPrint',
    source: 'components/prism-next/question-print.tsx',
    contract: ['QuestionPrint showQuestionIds defaults true. false hides the printed ID/version line and triggers pagination; question numbering, internal version references and edition hash stay unchanged. It is not a data-redaction API.'],
  },
  form: {
    component: "Form",
    source: "coss Form composed with Field, Input, Select, Textarea and Button",
    contract: ["Canonical structure is fields plus explicit submit/reset actions.", "Validation is local to the affected field and recovery feedback remains visible.", "Labels are persistent fixed labels."],
    states: ["editing", "invalid", "submitting", "success/recovery"],
    accessibility: ["Associate errors with fields and preserve native form semantics."],
    dont: ["Do not replace persistent labels with placeholder-only identification.", "Do not introduce floating labels as base behavior."]
  },
  field: {
    component: "Field",
    source: "coss Field",
    contract: ["Field owns label, description and inline validation feedback.", "Field identity remains visible in every state.", "Canonical label strategy is persistent fixed label."],
    states: ["default", "filled", "invalid", "readonly", "disabled"],
    accessibility: ["Keep label-control association and error announcement semantics."],
    dont: ["Do not infer floating-label behavior.", "Do not hide field identity after input."]
  },
  input: {
    component: "Input",
    source: "coss Input",
    contract: ["Use native sm / default / lg sizing; field container controls width.", "Persistent fixed label is canonical.", "Readonly, disabled, invalid and filled states remain distinguishable.", "Single-line title fields commonly fill the form column; short numeric/select fields stay content-sized."],
    states: ["default", "hover", "focus-visible", "filled", "invalid", "readonly", "disabled"],
    accessibility: ["Use a persistent associated label.", "Use aria-invalid and associated inline error text for invalid fields."],
    dont: ["Do not override internal coss height, radius or padding.", "Do not use placeholder as the only label.", "Do not infer floating labels."]
  },
  textarea: {
    component: "Textarea",
    source: "coss Textarea",
    contract: ["Persistent fixed label is canonical.", "Allow long content to grow naturally when the product context needs it.", "Character count is supporting information, not a replacement for validation."],
    states: ["default", "focus-visible", "filled", "invalid", "readonly", "disabled"],
    accessibility: ["Keep a persistent associated label and explicit max-length/error feedback when applicable."],
    dont: ["Do not introduce floating labels as base behavior."]
  },
  select: {
    component: "Select",
    source: "coss Select",
    contract: ["Preserve coss list, selected indicator, keyboard behavior and native size variants.", "Width follows content and field context; short choices should not be stretched into a full column.", "Use a persistent fixed label."],
    states: ["closed", "open", "focus-visible", "selected", "disabled"],
    accessibility: ["Preserve keyboard navigation, selection semantics and focus return."],
    dont: ["Do not replace the component's popup behavior.", "Do not infer custom motion or dimensions."]
  },
  badge: {
    component: "Badge",
    source: "coss Badge plus Prism info-solid and attention aliases",
    contract: ["Use text plus restrained color to express status.", "Prism semantic colors require textual meaning.", "info-solid increases information emphasis only; it does not imply pending, error, category or completion.", "attention maps to the existing error appearance for host-declared human attention; text defines meaning, never infer execution failure. Prism size remains lg by default.", "Counts do not automatically hide zero or collapse to 99+."],
    accessibility: ["Ensure the containing control has a complete accessible name when a numeric badge is visually repeated."],
    dont: ["Do not communicate status by color alone.", "Do not invent automatic count truncation."]
  },
  card: {
    component: "Card",
    source: "coss Card composition",
    contract: ["Reuse one Card family for content, horizontal rows, metrics, people, selection and grouping.", "Hierarchy comes from content structure and spacing before separators or decoration."],
    states: ["default", "interactive when the caller provides interaction", "selected when explicitly composed"],
    dont: ["Do not create a new component for every card layout.", "Do not add decorative icon backgrounds or repeated separators without a semantic need."]
  },
  dialog: {
    component: "Dialog",
    source: "coss Dialog",
    contract: ["Use for temporary focused editing while preserving the surrounding context.", "Nested controls such as Select must inherit the active theme.", "Footer actions state the commit/cancel choice clearly."],
    states: ["closed", "opening/open", "nested-popup", "closing"],
    accessibility: ["Preserve focus trapping, close semantics, accessible title/description and focus return."],
    dont: ["Do not replace a destructive confirmation with a generic Dialog when Alert Dialog is the correct primitive."]
  },
  tabs: {
    component: "Tabs",
    source: "coss Tabs",
    contract: ["Use segmented tabs or underline tabs to switch related content for the same object.", "Selected state must remain clear without glow or decorative shadow.", "Disabled tabs remain explicit."],
    states: ["default", "hover", "focus-visible", "selected", "disabled"],
    accessibility: ["Preserve tablist/tab/tabpanel semantics and keyboard navigation."],
    dont: ["Do not use Tabs as unrelated page navigation.", "Do not add glow/shadow to manufacture selected state."]
  }
}

export function getAgentSpec(id: string) {
  return coreAgentSpecs[id]
}
