"use client"
import { useTheme } from "next-themes"
import { EChart } from "./echart"
import { DataRecordTable } from "../data-display"
import { matrixExtent, validBox, type AxisItem, type MatrixCell, type ScatterPoint, type BoxSummary } from "@/lib/prism-next/chart-data"
import { themePalette } from "@/lib/prism-next/config"
export type { AxisItem, MatrixCell, ScatterPoint, BoxSummary } from "@/lib/prism-next/chart-data"
type Shared={label:string;unit?:string;selectedId?:string;onSelect?:(id:string)=>void;height?:number}
function useChartColors(){const {theme}=useTheme();return theme==="dark"?{base:"#86C5FF",selected:"#F296C2",fill:"#365B7B"}:{base:"#1769AA",selected:"#B8266E",fill:"#76A9D2"}}
function DataSummary({children}:{children:React.ReactNode}){return <details><summary className="cursor-pointer py-2 text-sm text-muted-foreground">查看数据与选择项目</summary>{children}</details>}
export function HeatmapChart({rows,columns,cells,label,unit="",selectedId,onSelect,height=320}:Shared&{rows:AxisItem[];columns:AxisItem[];cells:MatrixCell[]}){
 const {theme}=useTheme();const palette=themePalette[theme as keyof typeof themePalette]??themePalette.light;const extent=matrixExtent(cells)
 const cellLabel=(c:MatrixCell)=>c.label??(c.value===null||!Number.isFinite(c.value)?"缺测":`${c.value}${unit}`)
 const data=cells.filter(c=>rows.some(r=>r.id===c.row)&&columns.some(r=>r.id===c.column)).map(c=>({id:c.id,value:[columns.findIndex(x=>x.id===c.column),rows.findIndex(x=>x.id===c.row),c.value===null||!Number.isFinite(c.value)?extent.missing:c.value],rawLabel:cellLabel(c),rowLabel:rows.find(r=>r.id===c.row)!.label,columnLabel:columns.find(r=>r.id===c.column)!.label,itemStyle:{borderWidth:c.id===selectedId?2:1,borderColor:c.id===selectedId?palette.foreground:palette.background},label:{color:c.value===null||!Number.isFinite(c.value)?palette.muted:c.value>(extent.min+extent.max)/2?"#fff":palette.foreground}}))
 return <div className="space-y-3">{data.length?<EChart label={label} height={height} onSelect={onSelect} option={{tooltip:{formatter:params=>{const p=Array.isArray(params)?params[0]:params;const cell=p.data as typeof data[number];return `${cell.rowLabel} · ${cell.columnLabel}\n${cell.rawLabel}`}},grid:{left:105,right:20,top:20,bottom:75},xAxis:{type:"category",data:columns.map(c=>c.label),splitArea:{show:false}},yAxis:{type:"category",data:rows.map(r=>r.label),inverse:true},visualMap:{min:extent.min,max:extent.max,calculable:false,text:[`${extent.max}${unit}`,`${extent.min}${unit}`],orient:"horizontal",left:"center",bottom:0,inRange:{color:[palette.secondary,"#76A9D2","#1769AA"]},outOfRange:{color:[palette.secondary]},textStyle:{color:palette.muted}},series:[{type:"heatmap",data,label:{show:true,formatter:p=>(p.data as typeof data[number]).rawLabel},emphasis:{itemStyle:{borderColor:palette.foreground,borderWidth:2}}}]}}/>:<p className="py-10 text-sm text-muted-foreground">暂无矩阵数据。</p>}<p className="text-xs text-muted-foreground">{label} · {unit||"数值"}；缺测单独标记，不按零值绘制。</p><DataSummary><DataRecordTable rows={cells} selectedId={selectedId} onSelect={onSelect} columns={[{id:"row",label:"行",render:c=>rows.find(x=>x.id===c.row)?.label},{id:"column",label:"列",render:c=>columns.find(x=>x.id===c.column)?.label},{id:"value",label:"数值",render:cellLabel}]}/></DataSummary></div>
}
export {ScatterChart,QuadrantScatterChart} from "./scatter-chart"
export function BoxPlotChart({data,label,unit="",selectedId,onSelect,height=320}:Shared&{data:BoxSummary[]}){const colors=useChartColors();const valid=data.filter(x=>validBox(x.values));return <div className="space-y-3">{valid.length?<EChart label={label} height={height} onSelect={onSelect} option={{grid:{left:55,right:20,top:25,bottom:45},xAxis:{type:"category",data:valid.map(d=>d.label)},yAxis:{type:"value",name:unit},series:[{type:"boxplot",data:valid.map(d=>({id:d.id,value:d.values,itemStyle:{color:colors.fill,borderColor:d.id===selectedId?colors.selected:colors.base,borderWidth:d.id===selectedId?3:1.5}}))}]}}/>:<p className="py-10 text-sm text-muted-foreground">暂无有效箱线数据。</p>}{valid.length!==data.length&&<p role="alert" className="text-sm text-destructive">部分五数摘要顺序不正确，未绘制。</p>}<p className="text-xs text-muted-foreground">输入顺序：下须、第一四分位、中位数、第三四分位、上须。统计方法由数据提供方确定。</p><DataSummary><DataRecordTable rows={data} selectedId={selectedId} onSelect={onSelect} columns={[{id:"label",label:"分组",render:r=>r.label},...["下须","Q1","中位数","Q3","上须"].map((label,i)=>({id:String(i),label,render:(r:BoxSummary)=>`${r.values[i]}${unit}`}))]}/></DataSummary></div>}
