"use client"
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, Legend } from "recharts"
import { DataRecordTable } from "../data-display"
export type ChartPoint={id:string;label:string;value:number|null}
export type ChartSeries={id:string;label:string;data:ChartPoint[];color?:string}
export type BasicChartProps={label:string;series:ChartSeries[];unit?:string;domain?:[number,number];onSelect?:(pointId:string,seriesId:string)=>void;height?:number;showData?:boolean}
const axis={tickLine:false,axisLine:false,tickMargin:10,tick:{fill:"var(--muted-foreground)",fontSize:12}}
export function TrendChart({label,series,unit="",domain,height=260,onSelect,showData=true}:BasicChartProps){const rows=[...new Set(series.flatMap(s=>s.data.map(p=>p.id)))].map(id=>({id,label:series.flatMap(s=>s.data).find(p=>p.id===id)!.label,...Object.fromEntries(series.map(s=>[s.id,s.data.find(p=>p.id===id)?.value??null]))}));return <div className="space-y-3"><div role="group" aria-label={label} style={{height}}><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:600,height}}><LineChart data={rows} accessibilityLayer margin={{top:12,right:20,left:0,bottom:6}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 4"/><XAxis {...axis} dataKey="label"/><YAxis {...axis} domain={domain} tickFormatter={v=>`${v}${unit}`}/><Tooltip contentStyle={{background:"var(--popover)",color:"var(--popover-foreground)",borderColor:"var(--border)",borderRadius:8}} formatter={v=>`${v??"—"}${unit}`}/>{series.length>1&&<Legend/>}{series.map((s,i)=><Line key={s.id} dataKey={s.id} name={s.label} type="linear" connectNulls={false} stroke={s.color??`var(--chart-${i%5+1})`} strokeWidth={2} isAnimationActive={false} activeDot={{r:5,onClick:(_,payload:unknown)=>{const row=payload as {payload?:{id:string}};if(row.payload)onSelect?.(row.payload.id,s.id)}}}/>)}</LineChart></ResponsiveContainer></div>{showData&&<details><summary className="cursor-pointer text-ui-hint text-muted-foreground">查看数据</summary><DataRecordTable rows={rows} columns={[{id:"label",label:"项目",render:r=>r.label},...series.map(s=>({id:s.id,label:s.label,render:(r:typeof rows[number])=>{const value=(r as Record<string,unknown>)[s.id];return <span>{value==null?"—":`${value}${unit}`}</span>}}))]} onSelect={onSelect?id=>onSelect(id,series[0]?.id??""):undefined}/></details>}</div>}
export function ComparisonChart({label,data,unit="",domain,onSelect,horizontal=true,height=260}:{label:string;data:ChartPoint[];unit?:string;domain?:[number,number];onSelect?:(id:string)=>void;horizontal?:boolean;height?:number}){return <div className="space-y-3"><div role="group" aria-label={label} style={{height}}><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:600,height}}><BarChart data={data} layout={horizontal?"vertical":"horizontal"} accessibilityLayer margin={{top:12,right:16,left:0,bottom:6}}><CartesianGrid horizontal={!horizontal} vertical={horizontal} stroke="var(--border)" strokeDasharray="3 4"/><XAxis {...axis} type={horizontal?"number":"category"} dataKey={horizontal?undefined:"label"} domain={horizontal?domain:undefined}/><YAxis {...axis} type={horizontal?"category":"number"} dataKey={horizontal?"label":undefined} domain={horizontal?undefined:domain} width={horizontal?110:45}/><Tooltip contentStyle={{background:"var(--popover)",color:"var(--popover-foreground)",borderColor:"var(--border)",borderRadius:8}} formatter={v=>`${v??"—"}${unit}`}/><Bar dataKey="value" name={label} fill="var(--chart-1)" barSize={20} isAnimationActive={false} onClick={row=>{if(row.id)onSelect?.(row.id)}}/></BarChart></ResponsiveContainer></div><details><summary className="cursor-pointer text-ui-hint text-muted-foreground">查看数据</summary><DataRecordTable rows={data} columns={[{id:"label",label:"项目",render:r=>r.label},{id:"value",label:unit||"数值",render:r=>r.value==null?"—":`${r.value}${unit}`}]} onSelect={onSelect}/></details></div>}
