"use client"
import type {ScatterSeriesOption} from 'echarts'
import {EChart} from './echart'
import {useChartTheme} from './chart-theme'
import {DataRecordTable} from '../data-display'
import {chartDomain,withinDomain,formatChartValue} from '@/lib/prism-next/chart-options'
import type {ScatterPoint} from '@/lib/prism-next/chart-data'
export type ScatterGroup={id:string;label:string;symbol?:'circle'|'diamond'|'triangle'|'rect';color?:string}
export type Quadrants={x:number;y:number;labels:[string,string,string,string]}
export type ScatterChartProps={data:ScatterPoint[];label:string;xLabel:string;yLabel:string;unit?:string;xUnit?:string;xDomain?:[number,number];yDomain?:[number,number];groups?:ScatterGroup[];quadrants?:Quadrants;selectedId?:string;onSelect?:(id:string)=>void;height?:number}
export function ScatterChart({data,label,xLabel,yLabel,unit='',xUnit='',xDomain,yDomain,groups,quadrants,selectedId,onSelect,height=340}:ScatterChartProps){
 const {palette,colors}=useChartTheme(),xr=chartDomain(data.map(d=>d.x),xDomain),yr=chartDomain(data.map(d=>d.y),yDomain)
 const grouping=groups?.length?groups:[{id:'all',label}];const coordinates=data.filter(p=>withinDomain(p.x,xr)&&withinDomain(p.y,yr));const valid=coordinates.filter(p=>!groups?.length||groups.some(g=>g.id===p.group));const ungrouped=coordinates.length-valid.length
 const divided=quadrants&&withinDomain(quadrants.x,xr)&&withinDomain(quadrants.y,yr)?quadrants:undefined
 const series:ScatterSeriesOption[]=grouping.map((group,i)=>({id:group.id,name:group.label,type:'scatter',symbol:group.symbol??'circle',clip:true,data:valid.filter(p=>!groups?.length||p.group===group.id).map(p=>({id:p.id,name:p.label,value:[p.x,p.y],symbolSize:p.size?Math.max(8,Math.min(36,p.size)):13,itemStyle:{color:group.color??colors[i%colors.length],borderColor:p.id===selectedId?palette.foreground:palette.background,borderWidth:p.id===selectedId?3:1}})),label:{show:!!quadrants,position:'right',color:palette.foreground,fontSize:12,formatter:'{b}',width:110,overflow:'truncate'},labelLayout:{hideOverlap:true},emphasis:{label:{show:true}},...(i===0&&divided?{markLine:{silent:true,symbol:'none',label:{show:false},lineStyle:{color:palette.muted,type:'solid',width:1},data:[{xAxis:divided.x},{yAxis:divided.y}]},markArea:{silent:true,itemStyle:{color:'transparent'},label:{show:true,color:palette.muted,fontSize:12,position:'insideTop'},data:[[{name:divided.labels[0],coord:[xr[0],yr[1]]},{coord:[divided.x,divided.y]}],[{name:divided.labels[1],coord:[divided.x,yr[1]]},{coord:[xr[1],divided.y]}],[{name:divided.labels[2],coord:[xr[0],divided.y]},{coord:[divided.x,yr[0]]}],[{name:divided.labels[3],coord:[divided.x,divided.y]},{coord:[xr[1],yr[0]]}]]}}:{})}))
 const missing=data.filter(p=>p.x===null||p.y===null).length,excluded=data.length-coordinates.length-missing
 return <div className="min-w-0 space-y-4">
 {groups?.length&&<ul className="flex flex-wrap gap-4 text-ui-body" aria-label="点形图例">{groups.map((g,i)=><li key={g.id} className="flex items-center gap-2"><span aria-hidden className="inline-block size-2.5" style={{background:g.color??colors[i%colors.length],borderRadius:(!g.symbol||g.symbol==='circle')?'50%':0,clipPath:g.symbol==='triangle'?'polygon(50% 0,100% 100%,0 100%)':undefined,transform:g.symbol==='diamond'?'rotate(45deg)':undefined}}/>{g.label}</li>)}</ul>}
 {valid.length?<EChart label={label} height={height} onSelect={id=>onSelect?.(id)} option={{grid:{left:60,right:28,top:40,bottom:55},xAxis:{type:'value',min:xr[0],max:xr[1],name:xLabel,nameLocation:'middle',nameGap:34,splitNumber:4,axisLabel:{formatter:(v:number)=>formatChartValue(v,xUnit)}},yAxis:{type:'value',min:yr[0],max:yr[1],name:yLabel,splitNumber:4,axisLabel:{formatter:(v:number)=>formatChartValue(v,unit)}},tooltip:{formatter:params=>{const p=Array.isArray(params)?params[0]:params;const values=p.value as number[];return `${p.name}\n${xLabel}：${formatChartValue(values[0],xUnit)}\n${yLabel}：${formatChartValue(values[1],unit)}`}},series,media:[{option:{series:series.map(s=>({id:s.id,label:{show:!!quadrants},markArea:{label:{show:!!divided}}}))}},{query:{maxWidth:440},option:{series:series.map(s=>({id:s.id,label:{show:false},markArea:{label:{show:false}}}))}}]}}/>:<p className="py-10 text-ui-hint text-muted-foreground">暂无范围内的散点数据。</p>}
 {divided&&<><p className="text-ui-hint text-muted-foreground">分界：{xLabel} {formatChartValue(divided.x,xUnit)}；{yLabel} {formatChartValue(divided.y,unit)}。分界线上的点保留原坐标。</p><ul className="grid grid-cols-2 gap-x-5 gap-y-2 text-ui-hint text-muted-foreground" aria-label="象限说明">{['左上','右上','左下','右下'].map((position,i)=><li key={position}>{position} · {divided.labels[i]}</li>)}</ul></>}
 {ungrouped>0&&<p role="alert" className="text-ui-body text-destructive">{ungrouped} 项未匹配分组，未绘制；可在数据表查看。</p>}
 {quadrants&&!divided&&<p role="alert" className="text-ui-body text-destructive">分界值超出坐标范围，未绘制象限。</p>}
 {(missing>0||excluded>0)&&<p className="text-ui-hint text-muted-foreground">缺测 {missing} 项；无效或超出范围 {excluded} 项。未绘制的项目仍保留在数据表中。</p>}
 <details><summary className="cursor-pointer text-ui-hint text-muted-foreground">查看数据与选择项目</summary><DataRecordTable rows={data} selectedId={selectedId} onSelect={onSelect} columns={[{id:'label',label:'项目',render:p=>p.label},{id:'x',label:xLabel,render:p=>formatChartValue(p.x,xUnit)},{id:'y',label:yLabel,render:p=>formatChartValue(p.y,unit)}]}/></details>
 </div>
}
export function QuadrantScatterChart(props:ScatterChartProps&{quadrants:Quadrants}){return <ScatterChart {...props}/>}
