"""Build self-hosted reading fonts from pinned upstream files (fontTools + Brotli).

Usage: python scripts/build-reading-fonts.py SANS_VF.otf SERIF_REGULAR.otf
The common shard optimizes this route; all remaining source cmap entries are
also shipped, so dynamic input is not restricted to the sample vocabulary.
"""
import hashlib
import json
import re
import sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "public/fonts/reading"
SPECS = [
    ("sans", "Prism Reading Sans SC", "100 900", "2745e9681cb9d8a5c8901b62c9e1bd98c9c774365fc3b84dd467621013b51cd3"),
    ("serif", "Prism Reading Serif SC", "400", "2a2eae2628df83556c54018c41e20fa532c1b862c5256ae8b3f23feb918d12ca"),
]


def ranges(points):
    groups = []
    for cp in sorted(points):
        if groups and cp == groups[-1][1] + 1:
            groups[-1][1] = cp
        else:
            groups.append([cp, cp])
    return ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in groups)


def build(job):
    source, stem, family, weight, suffix, points = job
    font = TTFont(source, recalcTimestamp=False)
    opts = subset.Options()
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    opts.name_languages = ["*"]
    opts.notdef_glyph = True
    sub = subset.Subsetter(options=opts)
    sub.populate(unicodes=points)
    sub.subset(font)
    for record in font["name"].names:
        if record.nameID in (1, 3, 4, 6, 16):
            value = family.replace(" ", "") if record.nameID == 6 else family
            record.string = value.encode(record.getEncoding())
    assert set(font.getBestCmap()) == set(points)
    if stem == "sans":
        axis = font["fvar"].axes[0]
        assert (axis.axisTag, axis.minValue, axis.maxValue) == ("wght", 100, 900)
    else:
        assert font["OS/2"].usWeightClass == 400
    font.flavor = "woff2"
    temporary = OUT / f"{stem}-{suffix}.woff2"
    font.save(temporary)
    digest = hashlib.sha256(temporary.read_bytes()).hexdigest()
    path = temporary.with_name(f"{stem}-{suffix}-{digest[:12]}.woff2")
    temporary.rename(path)
    result = {"file": path.name, "family": family, "weight": weight, "characters": len(points), "bytes": path.stat().st_size, "sha256": digest, "unicodeRange": ranges(points)}
    print(f"{path.name}: {result['bytes']} bytes / {len(points)} characters", flush=True)
    return result


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    text = (ROOT / "app/review/reading-review/reading-review.tsx").read_text()
    common = set(range(0x20, 0x100)) | set(range(0x2000, 0x2070)) | set(range(0x3000, 0x3040)) | set(range(0xFF01, 0xFF61))
    common |= {ord(c) for c in text if "\u3400" <= c <= "\u9fff"}
    jobs, sources = [], []
    for source, (stem, family, weight, checksum) in zip(sys.argv[1:], SPECS, strict=True):
        assert hashlib.sha256(Path(source).read_bytes()).hexdigest() == checksum, "Unexpected source version"
        font = TTFont(source)
        cmap = set(font.getBestCmap())
        groups = [sorted(cmap & common)]
        rest = sorted(cmap - common)
        groups += [rest[i:i + 4096] for i in range(0, len(rest), 4096)]
        assert set().union(*map(set, groups)) == cmap
        assert sum(map(len, groups)) == len(cmap)
        sources.append({"family": family, "sourceSha256": checksum, "characters": len(cmap), "weight": weight})
        jobs += [(source, stem, family, weight, "common" if i == 0 else f"{i:02}", group) for i, group in enumerate(groups)]
    with ProcessPoolExecutor(max_workers=2) as pool:
        files = list(pool.map(build, jobs))
    css = "/* Generated by scripts/build-reading-fonts.py. */\n" + "\n".join(
        f"@font-face {{ font-family: '{f['family']}'; src: url('/fonts/reading/{f['file']}') format('woff2'); font-style: normal; font-weight: {f['weight']}; font-display: swap; unicode-range: {f['unicodeRange']}; }}" for f in files)
    (ROOT / "app/review/reading-review/fonts.css").write_text(css + "\n")
    (OUT / "manifest.json").write_text(json.dumps({"sources": sources, "files": files}, ensure_ascii=False, indent=2) + "\n")
