"use client"

import { useEffect,useRef,useState } from "react"
import { Bold,Italic,Underline,Save,Plus,Copy,AlignLeft,AlignCenter,AlignRight } from "lucide-react"
import { Button } from "@/components/prism-next/button"
import { Group } from "@/components/coss/group"
import { Toggle } from "@/components/coss/toggle"
import { ToggleGroup,ToggleGroupItem } from "@/components/coss/toggle-group"
import { Toolbar,ToolbarButton,ToolbarGroup,ToolbarSeparator } from "@/components/prism-next/toolbar"
import { Command,CommandInput,CommandList,CommandEmpty,CommandItem,CommandPanel } from "@/components/coss/command"
import { DemoSection,Feedback } from "@/components/prism-next/demo-parts"

export function ButtonDemo(){
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null)
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[])
  const save=()=>{if(busy)return;setBusy(true);setMessage('正在保存示例…');timer.current=setTimeout(()=>{setBusy(false);setMessage('示例修改已保存。')},700)}
  return <><DemoSection title="操作层级" description="一个操作区域保留一个主要按钮；颜色随主题成套变化。"><div className="flex flex-wrap gap-3"><Button onClick={save} loading={busy} aria-label={busy?'正在保存':'保存修改'}><Save/>保存修改</Button><Button variant="outline" onClick={()=>setMessage('已打开预览示例。')}>预览</Button><Button variant="secondary" onClick={()=>setMessage('已添加到教研清单。')}>加入清单</Button><Button variant="ghost" onClick={()=>setMessage('已取消当前操作。')}>取消</Button><Button variant="destructive-outline" onClick={()=>setMessage('此处展示危险操作样式；实际删除应使用确认对话框。')}>删除草稿</Button></div><Feedback>{message||'点击按钮可查看各自的反馈。'}</Feedback></DemoSection><DemoSection title="尺寸与禁用"><div className="flex flex-wrap items-center gap-4"><Button size="sm">紧凑</Button><Button>默认</Button><Button size="lg">宽松</Button><Button size="icon" variant="outline" aria-label="新增材料" onClick={()=>setMessage('已选择新增材料。')}><Plus/></Button><Button disabled>已锁定</Button><Button size="navigation" variant="outline">导航尺寸</Button><Button size="navigation-icon" variant="outline" aria-label="新增导航材料"><Plus/></Button></div></DemoSection></>
}
export function GroupDemo(){const[page,setPage]=useState(2);return <DemoSection title="相关操作组成一组"><Group><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>上一页</Button><Button variant="outline" aria-label={`当前第 ${page} 页`}>{page} / 5</Button><Button variant="outline" disabled={page===5} onClick={()=>setPage(n=>n+1)}>下一页</Button></Group><Feedback>当前阅读第 {page} 页。</Feedback></DemoSection>}
export function ToggleDemo(){const[value,setValue]=useState(false);return <DemoSection title="独立切换"><Toggle aria-label="加粗文字" pressed={value} onPressedChange={setValue} variant="outline"><Bold/></Toggle><p className={'mt-5 text-read-body '+(value?'font-semibold':'font-normal')}>二次方程的实数根</p><Feedback>{value?'加粗已开启。':'加粗已关闭。'}</Feedback></DemoSection>}
export function ToggleGroupDemo(){const[value,setValue]=useState<string[]>(['left']);return <DemoSection title="互斥视图"><ToggleGroup value={value} onValueChange={setValue} aria-label="文字对齐"><ToggleGroupItem value="left" aria-label="左对齐"><AlignLeft/></ToggleGroupItem><ToggleGroupItem value="center" aria-label="居中"><AlignCenter/></ToggleGroupItem><ToggleGroupItem value="right" aria-label="右对齐"><AlignRight/></ToggleGroupItem></ToggleGroup><p className="mt-6 max-w-md border-y py-5" style={{textAlign:(value[0]??'left') as 'left'|'center'|'right'}}>让文字的组织服从内容。</p></DemoSection>}
export function ToolbarDemo(){const[plain,setPlain]=useState(false);const[formats,setFormats]=useState<string[]>([]);const toggle=(f:string)=>setFormats(s=>s.includes(f)?s.filter(x=>x!==f):[...s,f]);return <DemoSection title="编辑工具栏"><Button className="mb-4" variant="outline" aria-pressed={plain} onClick={()=>setPlain(v=>!v)}>无框工具栏：{plain?"开启":"关闭"}</Button><Toolbar variant={plain?"plain":"framed"} aria-label="文字格式工具栏"><ToolbarGroup><ToolbarButton aria-label="加粗" render={<Toggle pressed={formats.includes('bold')} onPressedChange={()=>toggle('bold')}/>}><Bold/></ToolbarButton><ToolbarButton aria-label="斜体" render={<Toggle pressed={formats.includes('italic')} onPressedChange={()=>toggle('italic')}/>}><Italic/></ToolbarButton><ToolbarButton aria-label="下划线格式" render={<Toggle pressed={formats.includes('underline')} onPressedChange={()=>toggle('underline')}/>}><Underline/></ToolbarButton></ToolbarGroup><ToolbarSeparator/><ToolbarButton render={<Button variant="ghost"/>} onClick={()=>setFormats([])}>清除格式</ToolbarButton></Toolbar><p lang="en" className="mt-6 text-read-body" style={{fontWeight:formats.includes('bold')?600:400,fontStyle:formats.includes('italic')?'italic':'normal',textDecoration:formats.includes('underline')?'underline':'none'}}>Clear content, calm interface.</p></DemoSection>}
export function CommandDemo(){const[value,setValue]=useState('');const[chosen,setChosen]=useState('');const items=['新建材料','打开材料研读','查看主题规范','继续上次复核'];return <DemoSection title="搜索命令" description="输入关键词，使用方向键选择，再按 Enter 执行。"><div className="max-w-lg overflow-hidden rounded-2xl border bg-popover"><Command items={items} value={value} onValueChange={setValue}><CommandInput placeholder="搜索命令…" aria-label="搜索命令"/><CommandPanel><CommandEmpty>没有匹配的命令。</CommandEmpty><CommandList>{(item:string)=><CommandItem key={item} value={item} onClick={()=>setChosen(item)}>{item}</CommandItem>}</CommandList></CommandPanel></Command></div><Feedback>{chosen?`已执行示例命令：${chosen}`:'命令仅作用于当前示例。'}</Feedback></DemoSection>}
export const actionDemos={button:ButtonDemo,group:GroupDemo,toggle:ToggleDemo,'toggle-group':ToggleGroupDemo,toolbar:ToolbarDemo,command:CommandDemo}
