"use client"

import { useId, useRef, useState } from "react"
import { Button } from "@/components/coss/button"
import { Field, FieldLabel } from "@/components/coss/field"
import { Textarea } from "@/components/coss/textarea"
import { AgentItemReviewer, type AgentItemReview, type AgentItemReviewEditor, type AgentItemReviewRecord, type AgentItemReviewState, type AgentItemReviewTarget } from "../agent-item-reviewer"
import { AgentEvidenceDrilldown, type AgentEvidenceItem } from "../agent-evidence-drilldown"
import { DocumentRegionViewer } from "../document-region-viewer"
import { DraftMathPreview } from "../draft-math-preview"
import { VerificationFields, type CriterionResult } from "../learning-components"
import { PointsField, QuestionSelect } from "../question-controls"

type ExampleDraft = { text: string; score: number | null; checks: Record<string, CriterionResult | undefined>; evidenceNote: string }
type ReviewExample = { label: string; item: AgentItemReviewTarget; checkpoints: readonly string[]; original: string; draft: ExampleDraft; evidence: AgentEvidenceItem; history: readonly AgentItemReviewRecord[] }

const formula = <math className="prism-math" aria-label="y 等于二分之一 x 平方减二 x 加三"><mi>y</mi><mo>=</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><msup><mi>x</mi><mn>2</mn></msup><mo>−</mo><mn>2</mn><mi>x</mi><mo>+</mo><mn>3</mn></math>

function OriginalPreview() {
  const [selected, setSelected] = useState("q2")
  return <DocumentRegionViewer label="第 2 题原稿 · 示例" selectedId={selected} onSelect={setSelected} header={<p>二次函数练习 · 原稿 v1 · 示例</p>}
    regions={[{ id: "q2", label: "第 2 题", rect: [8, 22, 84, 38], content: <div className="space-y-3 text-read-body"><p>2. 将下式配方，并求对称轴。</p><div className="overflow-x-auto">{formula}</div></div> }]} />
}

export const itemReviewExamples: Record<"scan" | "grading", ReviewExample> = {
  scan: {
    label: "P04 单题与原稿对照",
    item: { id: "p04-question-2", title: "第 2 题 · 二次函数的配方与对称轴（示例）", version: "校对稿 r2" },
    checkpoints: ["识别存疑：请核对二次项系数及对称轴，保留题目完整条件与求解要求。", "已有“已与原稿对照”标记仅表示本地核对，复核提交记录仍待确认。"],
    original: "已知 y = x² − 2x + 3，求对称轴。",
    draft: { text: "已知 y = x² − 2x + 3，求对称轴。", score: null, checks: {}, evidenceNote: "" },
    evidence: { kind: "evidence", id: "original", title: "第 2 题原稿区域 · 示例", type: "原稿片段", source: { objectId: "scan-v1", label: "二次函数练习", version: "原稿 v1", location: "第 1 页 · 第 2 题" }, relation: "pending", facts: [{ state: "unknown", description: "读取、引用与本次参考记录未确认。" }],
      preview: <OriginalPreview /> },
    history: [{ id: "scan-history", item: { id: "p04-question-2", title: "第 2 题 · 首次校对", version: "校对稿 r1" }, state: "waiting-human", description: "当时尚未核对二次项系数。", reason: "需回看原稿第 1 页。" }],
  },
  grading: {
    label: "单份作答的评分复核",
    item: { id: "attempt-a-q4", title: "学生甲 · 第 4 题配方步骤的评分复核（示例）", version: "评分稿 r2" },
    checkpoints: ["评分待定：补入平方项后的常数是否处理正确。", "结论待核：只复核当前作答，不推定整份答卷或全班成绩已确认。"],
    original: "配方步骤正确，建议得 2 分。",
    draft: { text: "配方步骤正确，建议得 2 分。", score: 2, checks: {}, evidenceNote: "" },
    evidence: { kind: "evidence", id: "answer", title: "学生甲作答与评分依据 · 示例", type: "作答片段", source: { objectId: "attempt-a", label: "学生甲 · 第 4 题", version: "作答 v1", location: "作答第 2 段" }, relation: "pending", facts: [{ state: "preview-only", description: "示例仅有预览记录，不能证明评分已复核。" }],
      preview: <div className="space-y-3 text-read-body"><p>题目：将 x² − 4x + 1 配方。</p><p>学生写为：(x − 2)² + 1。</p><p>评分依据：正确配成平方项 1 分，常数处理正确 1 分；本项上限 2 分。</p></div> },
    history: [{ id: "grading-history", item: { id: "attempt-a-q4", title: "学生甲 · 第 4 题首次评分", version: "评分稿 r1" }, state: "failed", description: "此前复核被退回，需补充评分依据。", reviewer: "教师乙（示例）", time: "2026-09-24 15:00", resultVersion: "评分稿 r1", reason: "未说明常数项的得分依据。" }],
  },
}

/** Manual fixture inputs, never a simulated receipt generated by a review action. */
export function itemReviewFixture(state: AgentItemReviewState, version: string): AgentItemReview {
  if (state === "unknown" || state === "waiting") return { state, description: "保留本次提交的内容与理由。", request: { id: "review-request-1", label: "本题首次复核请求（示例）" }, query: { id: "query", label: "查询原请求", impact: "只查询这次复核的结果。" } }
  if (state === "resolved") return { state, description: "示例记录确认本题已复核。", resolution: { reviewer: "教师甲（示例）", version } }
  if (state === "expired") return { state, description: "保留原版本的草稿和理由，重新核对后再提交。" }
  return { state, description: state === "failed" ? "本次复核被退回，请补充依据后重新提交。" : state === "draft" ? "题目与理由的修改尚未提交。" : "请结合原始材料核对本项内容。", actions: [
    { id: state === "draft" || state === "failed" ? "submit" : "confirm", label: state === "draft" || state === "failed" ? "提交修订" : "确认无误", impact: "仅确认当前对象及所示版本。" },
    { id: "edit", label: "修改", impact: "进入本项草稿继续编辑。" },
    { id: "defer", label: "标记待议", impact: "将本项留待进一步讨论。" },
  ] }
}

function DraftFields({ value, onChange, readOnly, describedBy, grading }: AgentItemReviewEditor<ExampleDraft> & { grading: boolean }) {
  const id = useId()
  return <div className="space-y-4">
    <Field className="w-full"><FieldLabel htmlFor={id}>{grading ? "评分说明草稿" : "题干草稿"}</FieldLabel>
      <Textarea id={id} value={value.text} readOnly={readOnly} aria-describedby={describedBy} onChange={event => onChange({ ...value, text: event.target.value })} /></Field>
    {!grading && <DraftMathPreview value={value.text} label="当前题干草稿" />}
    {grading ? <div className="space-y-2"><p className="text-ui-action">本评分点得分 · 上限 2 分</p>
      {readOnly ? <p className="text-ui-body">{value.score ?? "待评分"} / 2 分</p>
        : <PointsField label="配方步骤得分" value={value.score} max={2} onChange={score => onChange({ ...value, score })} />}
    </div> : readOnly ? <div className="space-y-2 text-ui-hint"><p>标准 1：二次项系数与原稿一致。</p><p>判断：{value.checks.coefficient === "pass" ? "满足标准" : value.checks.coefficient === "retry" ? "尚未满足" : "待判断"}</p><p className="whitespace-pre-wrap">核验依据：{value.evidenceNote || "未填写"}</p></div>
      : <VerificationFields criteria={[{ id: "coefficient", text: "二次项系数与原稿一致。" }]} results={value.checks} note={value.evidenceNote}
        onResultsChange={checks => onChange({ ...value, checks })} onNoteChange={evidenceNote => onChange({ ...value, evidenceNote })} />}
  </div>
}

export function ReviewerExample({ example, grading, narrow }: { example: ReviewExample; grading: boolean; narrow: boolean }) {
  const [draft, setDraft] = useState(example.draft)
  const [reason, setReason] = useState("")
  const [state, setState] = useState<AgentItemReviewState>("waiting-human")
  const [changed, setChanged] = useState(false)
  const [feedback, setFeedback] = useState("")
  const origin = useRef<HTMLButtonElement | null>(null)
  const heading = useRef<HTMLHeadingElement>(null)
  const inlineHeading = useRef<HTMLHeadingElement>(null)
  const selectId = useId()
  const focusWorkspace = () => { heading.current?.focus(); heading.current?.scrollIntoView({ block: "nearest" }) }
  const review = itemReviewFixture(state, example.item.version)
  const updateDraft = (value: ExampleDraft) => { setDraft(value); setState("draft") }
  return <div className="space-y-5">
    <Field><FieldLabel htmlFor={selectId}>复核状态示例</FieldLabel><QuestionSelect id={selectId} label="复核状态示例" value={state} onChange={value => setState(value as AgentItemReviewState)} items={[
      { value: "waiting-human", label: "待复核" }, { value: "draft", label: "已编辑未提交" }, { value: "waiting", label: "复核提交中" },
      { value: "unknown", label: "回执未确认" }, { value: "resolved", label: "已复核 · 时间未确认" }, { value: "failed", label: "已退回 / 失败" }, { value: "expired", label: "已过期" },
    ]} /></Field>
    <Button variant="outline" onClick={() => { setState("unknown"); setChanged(true) }}>旧请求未确认且版本变化（示例）</Button>
    <Button variant="outline" aria-pressed={changed} onClick={() => setChanged(!changed)}>当前版本变化（示例）</Button>
    <p role="status" className="text-ui-hint">{feedback || "固定示例：可手动切换复核记录；确认、提交与查询不会生成回执。"}</p>
    <div className={narrow ? "grid max-w-80 gap-6" : "grid min-w-0 gap-6"}>
      {([["inline", "default", "对话摘要"], ["workspace", "default", "完整复核"], ["inline", "compact", "紧凑列表"]] as const).map(([view, density, label], index) => <section key={label} aria-label={`${label}示例`} className="min-w-0 space-y-3">
        <h3 ref={index === 1 ? heading : index === 0 ? inlineHeading : undefined} tabIndex={-1} className="text-block-title">{label}</h3>
        <AgentItemReviewer item={example.item} review={review} checkpoints={example.checkpoints} view={view} density={density}
          summary={<>{draft.text}{grading && <p className="mt-2 text-ui-hint">当前评分草稿：{draft.score ?? "待评分"} / 2 分</p>}</>}
          versionChange={changed || state === "expired" ? { currentVersion: grading ? "评分稿 r3" : "校对稿 r3" } : undefined}
          restart={{ id: "restart", label: "重新复核当前版本", impact: "请求打开当前版本，原草稿保留。" }}
          draft={{ value: draft, onChange: updateDraft, render: editor => <DraftFields {...editor} grading={grading} /> }}
          reason={{ value: reason, onChange: value => { setReason(value); setState("draft") } }}
          evidence={<AgentEvidenceDrilldown conclusion={{ id: `${example.item.id}-evidence`, statement: "本项核对依据（示例）", version: example.item.version }} nodes={[example.evidence]} view="workspace" density="compact" path={[example.evidence.id]} />}
          comparison={<dl className="grid min-w-0 gap-4 @min-[560px]:grid-cols-2"><div className="min-w-0 space-y-2"><dt className="text-ui-action">原值 · {example.item.version}</dt><dd className="whitespace-pre-wrap break-words text-read-body">{example.original}{grading && <p>初评：2 / 2 分</p>}</dd></div><div className="min-w-0 space-y-2"><dt className="text-ui-action">当前草稿</dt><dd className="whitespace-pre-wrap break-words text-read-body">{draft.text}{grading && <p>草稿：{draft.score ?? "待评分"} / 2 分</p>}</dd></div></dl>}
          history={example.history} notice="示例：未连接真实复核服务。"
          details={<p>预览、核对标记、复核提交与业务保存分别记录。复核本项不代表整份任务已完成。</p>}
          onExpand={button => { origin.current = button; focusWorkspace() }}
          onBack={() => { const target = origin.current?.isConnected ? origin.current : inlineHeading.current; target?.focus(); target?.scrollIntoView({ block: "nearest" }) }}
          onAction={intent => { setFeedback(`示例：已请求${intent.kind === "query" ? "查询原请求" : intent.kind === "restart" ? "重新复核当前版本" : intent.actionId === "edit" ? "修改" : intent.actionId === "defer" ? "标记待议" : intent.actionId === "confirm" ? "确认无误" : "提交修订"}，尚未取得新的复核回执。`); if (intent.kind === "review" && intent.actionId === "edit") focusWorkspace() }} />
      </section>)}
    </div>
  </div>
}

export function AgentItemReviewerDemo() {
  const [purpose, setPurpose] = useState<keyof typeof itemReviewExamples>("scan")
  const [narrow, setNarrow] = useState(false)
  return <section id="item-reviewer" className="mb-12 space-y-5">
    <h2 className="text-section-title">单项复核器 v0.1 · 设计候选</h2>
    <p className="text-ui-hint text-muted-foreground">固定示例：同一对象、草稿与理由在三种用法中展示，评分字段仅用于单份作答示例。</p>
    <div className="flex flex-wrap gap-2" aria-label="复核示例用途">{Object.entries(itemReviewExamples).map(([key, example]) => <Button key={key} variant="outline" aria-pressed={purpose === key} onClick={() => setPurpose(key as typeof purpose)}>{example.label}</Button>)}
      <Button variant="ghost" aria-pressed={narrow} onClick={() => setNarrow(!narrow)}>320px 窄容器</Button>
    </div>
    <ReviewerExample key={purpose} example={itemReviewExamples[purpose]} grading={purpose === "grading"} narrow={narrow} />
  </section>
}
