"use client"
// Application adapters: aggregation, labels and workflow belong to this example.
import { useId,useState,type ReactNode } from "react"
import { Button } from "@/components/coss/button"
import { Badge } from "@/components/coss/badge"
import { MetricSummary as Metrics,GoalComparison as Goal,StatusComposition as Composition,FilterBar,DataRecordTable } from "../data-display"
import { TrendChart as Trend,ComparisonChart as Compare } from "../charts/basic-charts"
import { QuestionWorkPanel } from "../question-work-panel"
import { topics,rubric,statusLabels,summarize,trendSeries,comparisonSeries,distributionSeries,statusSeries,displayRate,type EvidenceRecord,type AnalysisFilter,type Drill } from "@/lib/prism-next/analytics-model"
type DataProps={records:EvidenceRecord[];onDrill?:(drill:Drill)=>void}
export function AnalysisPanel({title,description,children,action}:{title:string;description:string;children:ReactNode;action?:ReactNode}){return <section className="analytics-panel"><header className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</header>{children}</section>}
export function MetricSummary({records,onDrill}:DataProps){const s=summarize(records);return <Metrics items={[{id:"reviewed",label:"样本得分率",value:displayRate(s.rate),detail:`${s.earned} / ${s.possible} 分 · ${s.scored} 道已复核题`},{id:"pending",label:"待复核",value:s.pending,detail:"尚不计入得分统计"},{id:"missing",label:"缺测",value:s.missing,detail:"未提交，不按零分处理"}]} onSelect={onDrill?id=>onDrill({kind:"status",value:id,label:statusLabels[id as keyof typeof statusLabels]}):undefined}/>}
export function TrendChart({records,onDrill}:DataProps){const data=trendSeries(records);return <AnalysisPanel title="样本得分率趋势" description="0–100% 固定坐标；缺测保留断点，不跨缺测连线。"><Trend label="样本得分率趋势" series={[{id:"rate",label:"得分率",data:data.map(d=>({id:d.date,label:d.label,value:d.rate}))}]} unit="%" domain={[0,100]} onSelect={onDrill?id=>onDrill({kind:"date",value:id,label:id}):undefined}/></AnalysisPanel>}
export function ComparisonChart({records,onDrill}:DataProps){const data=comparisonSeries(records);return <AnalysisPanel title="知识点样本比较" description="呈现样本表现，不直接推断掌握程度。"><Compare label="知识点样本得分率" unit="%" domain={[0,100]} data={data.map(d=>({id:d.id,label:d.label,value:d.rate}))} onSelect={onDrill?id=>onDrill({kind:"topic",value:id,label:topics.find(t=>t.id===id)?.label??id}):undefined}/></AnalysisPanel>}
export function DistributionChart({records,onDrill}:DataProps){const data=distributionSeries(records);return <AnalysisPanel title="单题得分分布" description="仅计已复核题目；互不重叠的统计区间。"><Compare label="题数" unit="道" horizontal={false} data={data.map(d=>({id:d.id,label:d.label,value:d.count}))} onSelect={onDrill?id=>onDrill({kind:"bin",value:id,label:data.find(d=>d.id===id)!.label}):undefined}/></AnalysisPanel>}
export function StatusComposition({records,onDrill}:DataProps){return <AnalysisPanel title="题目处理状态" description="处理状态不代表学习结果。"><Composition items={statusSeries(records).map(d=>({id:d.id,label:d.label,value:d.count}))} onSelect={onDrill?id=>onDrill({kind:"status",value:id,label:statusLabels[id as keyof typeof statusLabels]}):undefined}/></AnalysisPanel>}
export function GoalComparison({records}:DataProps){const data=trendSeries(records).filter(r=>r.rate!==null);return <AnalysisPanel title="目标对照" description="示例标准：80%，连续两次完整测评达到，并经教师确认。"><Goal baseline={data[0]?.rate??null} current={data.at(-1)?.rate??null} target={80} unit="%" status={<Badge variant="outline">目标待核验</Badge>}><p className="text-sm text-muted-foreground">数值达到目标不自动判定达成；此示例不生成教师确认记录。</p></Goal></AnalysisPanel>}
export function AnalysisFilters({value,onChange,onReset}:{value:AnalysisFilter;onChange:(v:AnalysisFilter)=>void;onReset:()=>void}){return <FilterBar fields={[{id:"learner",label:"学生",options:[{value:"SYN-A",label:"示例学生 A"},{value:"SYN-EMPTY",label:"示例学生 B（暂无记录）"}]},{id:"topic",label:"知识点",options:[{value:"all",label:"全部知识点"},...topics.map(t=>({value:t.id,label:t.label}))]},{id:"range",label:"时间范围",options:[{value:"all",label:"09/02–09/14 · 全部 6 轮"},{value:"recent",label:"09/09–09/14 · 最近 3 轮"}]}]} value={value} onChange={v=>onChange(v as AnalysisFilter)} onReset={onReset}/>}
export function EvidenceTable({records,drill,onClear}:{records:EvidenceRecord[];drill?:Drill;onClear?:()=>void}){const id=useId();const [selected,setSelected]=useState<string>();const [descending,setDescending]=useState(false);const row=records.find(r=>r.id===selected);return <AnalysisPanel title="证据明细" description={`${records.length} 道题 · 独立合成示例数据`} action={drill&&<Button variant="ghost" onClick={onClear}>清除：{drill.label}</Button>}><Button variant="ghost" size="sm" onClick={()=>setDescending(!descending)}>日期 {descending?"↓":"↑"}</Button><DataRecordTable rows={[...records].sort((a,b)=>descending?b.date.localeCompare(a.date):a.date.localeCompare(b.date))} onSelect={setSelected} selectedId={selected} columns={[{id:"date",label:"日期",render:r=>r.date.slice(5)},{id:"topic",label:"知识点 / 证据编号",render:r=><><span className="block">{topics.find(t=>t.id===r.topic)?.label}</span><span className="text-xs text-muted-foreground">{r.id}</span></>},{id:"status",label:"状态",render:r=>statusLabels[r.status]},{id:"score",label:"得分 / 满分",render:r=>`${r.score??"—"} / ${r.max}`} ]}/><QuestionWorkPanel id={id} open={!!row} onClose={()=>setSelected(undefined)} title="分析证据" description={row?.id??""}>{row&&<div className="space-y-5 text-sm leading-7"><Badge variant="outline">合成演示数据</Badge><p>{row.date} · {topics.find(t=>t.id===row.topic)?.label}</p><p>{statusLabels[row.status]} · {row.score??"—"} / {row.max} 分</p><p>{row.note}</p><h4 className="font-medium">评分标准 v1</h4><ol className="list-decimal pl-5">{rubric.map(r=><li key={r}>{r}</li>)}</ol><p className="text-muted-foreground">本记录不包含真实作答影像。</p></div>}</QuestionWorkPanel></AnalysisPanel>}
