"use client"
import { useState } from "react"
import { useTheme } from "next-themes"
import { paperSequentialCandidate } from "@/lib/prism-next/chart-color"
import { PaperPaletteReview } from "./paper-palette-review"
import { Button } from "@/components/coss/button"
import { DemoSection } from "../demo-parts"
import { QuestionSelect } from "../question-controls"
import { TrendChart,ComparisonChart } from "../charts/basic-charts"
import { HeatmapChart,ScatterChart,BoxPlotChart,type BoxSummary } from "../charts/advanced-charts"
import { MetricSummary,GoalComparison,StatusComposition,FilterBar,DataRecordTable } from "../data-display"
import {ReviewDemoThemes} from "./review-workspace-fixtures"
import {ReferenceChartDemo} from './reference-charts'
const datasets=[{id:"assessment",label:"测评数据",unit:"分",groups:["甲组","乙组","丙组"],values:[62,78,86],baseline:45,target:90},{id:"devices",label:"设备处理量",unit:"份",groups:["一号设备","二号设备","三号设备"],values:[120,180,95],baseline:60,target:200}]
export function ChartComponentDemo({kind}:{kind:string}){const [source,setSource]=useState("assessment"),[empty,setEmpty]=useState(false),[selected,setSelected]=useState(""),[filters,setFilters]=useState<Record<string,string>>({group:"all",period:"week"});const [candidate,setCandidate]=useState(true);const {theme}=useTheme();const sample=datasets.find(d=>d.id===source)!,{unit}=sample;const points=empty?[]:sample.values.map((value,i)=>({id:`item-${i}`,label:sample.groups[i],value}));const rows=points.map(p=>({id:p.id,label:p.label}));const select=(id:string)=>setSelected(id)
if(['status-composition','paired-dot-chart','quadrant-chart','combo-chart'].includes(kind))return <ReferenceChartDemo kind={kind}/>
return <><DemoSection title="数据驱动的独立组件" description="切换两组不同用途的数据，组件实现保持一致；选中结果通过回调交给外部。"><div className="mb-6 flex flex-wrap items-center gap-3"><QuestionSelect label="组件数据集" value={source} onChange={id=>{setSource(id);setSelected("")}} items={datasets.map(d=>({value:d.id,label:d.label}))}/><Button variant="outline" aria-pressed={empty} onClick={()=>{setEmpty(!empty);setSelected("")}}>{empty?"恢复数据":"查看空数据"}</Button></div>{kind==="evidence-matrix"&&<PaperPaletteReview candidate={candidate} onChange={setCandidate}/>}<div className="analytics-panel">
{kind==="trend-chart"&&<TrendChart label={sample.label} unit={unit} series={[{id:"a",label:"序列 A",data:points},{id:"b",label:"序列 B",data:points.map((p,i)=>({...p,value:i===1?null:Math.round(p.value*.8*10)/10}))}]} onSelect={select}/>}
{(kind==="comparison-chart"||kind==="distribution-chart")&&<ComparisonChart label={sample.label} unit={unit} horizontal={kind!=="distribution-chart"} data={points} onSelect={select}/>}
{kind==="evidence-matrix"&&<HeatmapChart sequentialColors={theme==="paper"&&candidate?paperSequentialCandidate:undefined} label={sample.label} unit={unit} rows={rows} columns={[{id:"before",label:"第一轮"},{id:"after",label:"第二轮"}]} cells={points.flatMap((p,i)=>[{id:p.id+"-before",row:p.id,column:"before",value:i===1?null:Math.round(p.value*.8)},{id:p.id+"-after",row:p.id,column:"after",value:p.value}])} selectedId={selected} onSelect={select}/>}
{kind==="scatter-chart"&&<ScatterChart label={sample.label} xLabel="用时（分钟）" yLabel={sample.label+`（${unit}）`} unit={unit} data={points.map((p,i)=>({id:p.id,label:p.label,x:[15,28,40][i],y:p.value}))} selectedId={selected} onSelect={select}/>}
{kind==="box-plot"&&<BoxPlotChart label={sample.label} unit={unit} data={points.map(p=>({id:p.id,label:p.label,values:[.4,.65,.8,1,1.2].map(ratio=>Math.round(p.value*ratio*10)/10) as BoxSummary["values"]}))} selectedId={selected} onSelect={select}/>}
{kind==="metric-summary"&&<div className="space-y-6"><MetricSummary items={points.map(p=>({...p,value:`${p.value} ${unit}`,detail:"由调用方提供口径"}))} onSelect={select}/><section id="compact-summary" className="space-y-3"><h3 className="text-block-title">紧凑指标摘要</h3><MetricSummary density="compact" items={points.map(p=>({...p,value:`${p.value} ${unit}`,detail:"由调用方提供口径"}))} onSelect={select}/></section></div>}
{kind==="goal-comparison"&&<GoalComparison baseline={empty?null:sample.baseline} current={empty?null:sample.values[1]} target={sample.target} unit={unit} status={<span className="text-ui-hint text-muted-foreground">数值进展；达成判断由外部业务决定。</span>}/>}
{kind==="status-composition"&&<StatusComposition items={points} onSelect={select}/>}
{kind==="analysis-filter"&&<FilterBar fields={[{id:"group",label:"分组",options:[{value:"all",label:"全部"},...rows.map(p=>({value:p.id,label:p.label}))]},{id:"period",label:"周期",options:[{value:"week",label:"本周"},{value:"month",label:"本月"}]}]} value={filters} onChange={setFilters} onReset={()=>setFilters({group:"all",period:"week"})}/>}
{kind==="evidence-table"&&<DataRecordTable rows={points} selectedId={selected} onSelect={select} columns={[{id:"label",label:"项目",render:p=>p.label},{id:"value",label:unit,render:p=>p.value}]}/>}
{!points.length&&!["evidence-table","evidence-matrix","scatter-chart","box-plot","goal-comparison"].includes(kind)&&<p className="py-6 text-ui-hint text-muted-foreground">当前没有数据。</p>}
</div><p role="status" className="mt-4 min-h-5 text-ui-hint text-muted-foreground">{kind==="analysis-filter"?`筛选值：${filters.group} · ${filters.period}`:selected?`已选项目：${selected}`:"可点击图形或展开数据表选择项目。"}</p><details className="mt-6 text-ui-body"><summary className="cursor-pointer text-muted-foreground">组件接口与边界</summary><p className="mt-3 leading-7">数据、单位、标签、选择状态与回调由调用方提供。组件不读取学生、题库或工作流状态，不计算诊断结论。</p><pre className="mt-3 overflow-x-auto rounded-lg bg-muted p-4 text-ui-hint">{kind==="evidence-matrix"?'<HeatmapChart rows={rows} columns={columns} cells={cells}\n  label={label} unit={unit} selectedId={selected}\n  onSelect={setSelected} />':kind==="box-plot"?'<BoxPlotChart data={fiveNumberSummaries} label={label}\n  unit={unit} onSelect={setSelected} />':kind==="scatter-chart"?'<ScatterChart data={points} label={label}\n  xLabel={xLabel} yLabel={yLabel} onSelect={setSelected} />':'数据与交互参数请参照对应导出的 TypeScript 类型。'}</pre></details></DemoSection>{(kind==="comparison-chart"||kind==="distribution-chart")&&<DemoSection title="分数段分布与参考线" description="分数段和参考值由宿主提供；及格线 60、优秀线 85、目标线 90。标签分行，查看数据保留全部参考值。"><ComparisonReferenceFixture/><ComparisonPlotLabelFixture/><ReviewDemoThemes>{()=> <ComparisonReferenceFixture narrow/>}</ReviewDemoThemes></DemoSection>}</>}

const scoreBands=[0,0,0,2,6,10,9,8,6,4].map((value,i)=>({id:`band-${i}`,label:i===9?'90–100':`${i*10}–<${(i+1)*10}`,value,range:[i*10,(i+1)*10] as [number,number]}))
export function ComparisonReferenceFixture({narrow=false}:{narrow?:boolean}){return <div className="min-w-0 space-y-4"><ComparisonChart label="分数段人数分布（分数 0–100）" data={scoreBands} unit="人" horizontal={false} height={300} referenceLines={[{value:60,label:'及格线',tone:'warning'},{value:85,label:'优秀线',tone:'success'},{value:90,label:'目标线',tone:'info'}]}/>{narrow&&<><ComparisonChart label="同值与长标签参考线" data={[{id:'a',label:'甲组',value:62},{id:'b',label:'乙组',value:85}]} domain={[0,100]} referenceLines={[{value:60,label:'需要结合完整评分依据和证据范围解释的中文参考线',tone:'neutral'},{value:60,label:'同值参考线仍保留独立标签',tone:'destructive'}]}/><ComparisonChart label="纵向数值轴参考线" data={[{id:'a',label:'甲组',value:62},{id:'b',label:'乙组',value:85}]} domain={[0,100]} horizontal={false} referenceLines={[{value:60,label:'数值轴参考线',tone:'info'}]}/></>}</div>}

const plotReferences=[{value:20,label:'低分线',tone:'destructive' as const},{value:60,label:'及格线',tone:'warning' as const},{value:85,label:'优秀线',tone:'success' as const},{value:90,label:'需要结合完整评分依据解释的目标参考线',tone:'info' as const}]
export function ComparisonPlotLabelFixture(){return <section id="plot-labels" className="min-w-0 space-y-6"><h3 className="text-block-title">分布 + 图内参考线标注 + 柱顶数值</h3><p className="text-ui-hint text-muted-foreground">纵向矮图高 140px，标注带与高柱数值分开；十个分段含零值，横向四条参考线含相邻 5 分与长名称；分值与人数分别呈现。横向示例的可见数据入口由宿主提供。</p><ComparisonChart label="纵向分布与图内标注" data={scoreBands} unit="人" horizontal={false} height={140} showValueLabels referenceLabelPlacement="plot" referenceLines={[{value:40,label:"参考线",tone:"info"},{value:60,label:"及格线",tone:"warning"},{value:85,label:"优秀线",tone:"success"}]}/><ComparisonChart label="横向分布与图内标注" data={scoreBands} unit="人" height={460} showValueLabels referenceLabelPlacement="plot" referenceLines={plotReferences} dataDisclosure="none"/><details><summary className="cursor-pointer text-ui-hint text-muted-foreground">查看完整分布与参考值（宿主入口）</summary><DataRecordTable rows={scoreBands} columns={[{id:'label',label:'分段',render:row=>row.label},{id:'value',label:'人数',render:row=>row.value}]}/><DataRecordTable rows={plotReferences.map((line,i)=>({...line,id:String(i)}))} columns={[{id:'label',label:'参考线',render:row=><span className="whitespace-normal break-words">{row.label}</span>},{id:'value',label:'分值',render:row=>row.value}]}/></details></section>}
