"use client"

import { useState } from "react"
import Link from "next/link"
import { ArrowUpDown,BookOpen,ChevronDown,FileText,Check,Info,TriangleAlert } from "lucide-react"
import { Button } from "@/components/coss/button"
import { Avatar,AvatarFallback } from "@/components/coss/avatar"
import { Badge } from "@/components/coss/badge"
import { Card,CardHeader,CardTitle,CardDescription,CardPanel,CardFooter } from "@/components/coss/card"
import { Frame,FrameHeader,FrameTitle,FrameDescription,FramePanel,FrameFooter } from "@/components/coss/frame"
import { Table,TableHeader,TableBody,TableHead,TableRow,TableCell,TableCaption } from "@/components/coss/table"
import { Accordion,AccordionItem,AccordionTrigger,AccordionPanel } from "@/components/coss/accordion"
import { Collapsible,CollapsibleTrigger,CollapsiblePanel } from "@/components/coss/collapsible"
import { Kbd,KbdGroup } from "@/components/coss/kbd"
import { ScrollArea } from "@/components/coss/scroll-area"
import { Separator } from "@/components/coss/separator"
import { DemoSection,Feedback } from "@/components/prism-next/demo-parts"

export function AvatarDemo(){return <DemoSection title="文字回退"><div className="flex flex-wrap gap-6">{[['陈','陈老师'],['林','林老师'],['A','Ashrum']].map(([letter,name])=><div key={name} className="flex items-center gap-3"><Avatar><AvatarFallback>{letter}</AvatarFallback></Avatar><span className="text-sm">{name}</span></div>)}</div></DemoSection>}
export function BadgeDemo(){return <DemoSection title="信息与状态"><div className="flex flex-wrap items-center gap-3"><Badge variant="secondary">草稿</Badge><Badge variant="outline">待复核</Badge><Badge variant="info"><Info/>处理中</Badge><Badge variant="success"><Check/>已复核</Badge><Badge variant="warning"><TriangleAlert/>需要补充</Badge><Badge variant="error">未通过</Badge></div></DemoSection>}
export function CardDemo(){const[saved,setSaved]=useState(false);return <DemoSection title="围绕一份材料"><Card className="max-w-sm"><CardHeader><CardTitle>二次方程的实数根</CardTitle><CardDescription>数学 · 函数与方程</CardDescription></CardHeader><CardPanel><p className="text-base leading-7 text-foreground">从判别式开始，理解两实根、重根与无实根的区别。</p><div className="mt-4 flex items-center gap-3 text-sm text-muted-foreground"><Badge variant="outline">待复核</Badge><span>预计 8 分钟</span></div></CardPanel><CardFooter><Button render={<Link href="/next/reading"/>}>阅读材料</Button><Button variant="ghost" onClick={()=>setSaved(v=>!v)} aria-pressed={saved}>{saved?'已收藏':'收藏'}</Button></CardFooter></Card></DemoSection>}
export function FrameDemo(){return <DemoSection title="连续的内容面板"><Frame className="max-w-lg"><FrameHeader><FrameTitle>本次复核</FrameTitle><FrameDescription>同一任务内的材料与进度。</FrameDescription></FrameHeader><FramePanel><h3 className="font-medium">二次方程的实数根</h3><p className="mt-2 text-sm text-muted-foreground">公式与结论已核对，待补充教学提示。</p></FramePanel><FrameFooter><Button variant="outline" render={<Link href="/next/reading"/>}>继续复核</Button></FrameFooter></Frame></DemoSection>}
const tableRows=[{name:'二次方程的实数根',time:8,score:98.5,status:'已复核'},{name:'函数的单调性',time:12,score:92.0,status:'待复核'},{name:'导数与极值',time:16,score:95.75,status:'待复核'},{name:'数列求和',time:10,score:87.5,status:'已复核'}]
export function TableDemo(){const[sort,setSort]=useState<'asc'|'desc'>('desc');const rows=[...tableRows].sort((a,b)=>sort==='asc'?a.score-b.score:b.score-a.score);return <DemoSection title="文字与数字列" description="数字右对齐并使用等宽数字；点击评分列切换排序。"><Table><TableCaption>教研材料示例数据</TableCaption><TableHeader><TableRow><TableHead>材料</TableHead><TableHead className="text-right">研读时长</TableHead><TableHead className="text-right" aria-sort={sort==='asc'?'ascending':'descending'}><Button variant="ghost" size="sm" onClick={()=>setSort(v=>v==='asc'?'desc':'asc')}>评分<ArrowUpDown/></Button></TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.name}><TableCell className="font-medium">{row.name}</TableCell><TableCell className="prism-numeric text-right">{row.time} 分钟</TableCell><TableCell className="prism-numeric text-right">{row.score.toFixed(2)}</TableCell><TableCell><Badge variant={row.status==='已复核'?'success':'outline'}>{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table></DemoSection>}
export function AccordionDemo(){return <DemoSection title="判别式说明"><Accordion className="max-w-xl" defaultValue={['positive']}><AccordionItem value="positive"><AccordionTrigger>判别式大于零</AccordionTrigger><AccordionPanel>方程有两个不相等的实数根。求根公式中的根号项大于零，因此加减两种取值不同。</AccordionPanel></AccordionItem><AccordionItem value="zero"><AccordionTrigger>判别式等于零</AccordionTrigger><AccordionPanel>方程有两个相等的实数根，根号项为零。</AccordionPanel></AccordionItem><AccordionItem value="negative"><AccordionTrigger>判别式小于零</AccordionTrigger><AccordionPanel>在实数范围内无法开平方，因此方程没有实数根。</AccordionPanel></AccordionItem></Accordion></DemoSection>}
export function CollapsibleDemo(){const[open,setOpen]=useState(false);return <DemoSection title="就地展开补充说明"><Collapsible open={open} onOpenChange={setOpen} className="max-w-xl"><CollapsibleTrigger render={<Button variant="outline"/>}>{open?'收起推导说明':'展开推导说明'}<ChevronDown className={open?'rotate-180':''}/></CollapsibleTrigger><CollapsiblePanel><p className="pt-4 text-base leading-8 text-foreground">先将方程两边同除以二次项系数，再配方。对两边开平方后，得到求根公式。每一步均保留等价条件。</p></CollapsiblePanel></Collapsible></DemoSection>}
export function KbdDemo(){return <DemoSection title="快捷键标注"><div className="flex flex-wrap items-center gap-3 text-sm"><span>切换导航</span><KbdGroup><Kbd>Ctrl</Kbd><span>+</span><Kbd>B</Kbd></KbdGroup><span className="text-muted-foreground">macOS 使用 ⌘ B</span></div></DemoSection>}
export function ScrollAreaDemo(){return <DemoSection title="有限高度内的材料清单"><ScrollArea className="h-64 max-w-md rounded-lg border" scrollbarGutter><div className="divide-y px-4">{Array.from({length:16},(_,i)=><div key={i} className="flex gap-3 py-3 text-sm"><FileText className="mt-0.5 size-4 shrink-0 text-muted-foreground"/><div><p>{['二次方程','函数的单调性','导数与极值','数列求和'][i%4]} · 材料 {i+1}</p><p className="mt-1 text-xs text-muted-foreground">教研材料 · 待复核</p></div></div>)}</div></ScrollArea></DemoSection>}
export function SeparatorDemo(){return <DemoSection title="仅在必要处区分内容"><div className="max-w-md space-y-4"><div><h3 className="font-medium">材料复核</h3><p className="mt-1 text-sm text-muted-foreground">先完成阅读，再提交修改。</p></div><Separator/><div className="flex h-5 items-center gap-4 text-sm"><span>正文</span><Separator orientation="vertical"/><span>元数据</span><Separator orientation="vertical"/><span>历史记录</span></div></div></DemoSection>}
export const contentDemos={avatar:AvatarDemo,badge:BadgeDemo,card:CardDemo,frame:FrameDemo,table:TableDemo,accordion:AccordionDemo,collapsible:CollapsibleDemo,kbd:KbdDemo,'scroll-area':ScrollAreaDemo,separator:SeparatorDemo}
