"use client"

import { useState,useRef,useEffect } from "react"
import { Info,Check,TriangleAlert,FileText,RefreshCw } from "lucide-react"
import { Button } from "@/components/coss/button"
import { Alert,AlertTitle,AlertDescription } from "@/components/coss/alert"
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyContent,EmptyMedia } from "@/components/coss/empty"
import { Progress,ProgressLabel,ProgressTrack,ProgressIndicator,ProgressValue } from "@/components/coss/progress"
import { Meter,MeterLabel,MeterTrack,MeterIndicator,MeterValue } from "@/components/coss/meter"
import { Skeleton } from "@/components/coss/skeleton"
import { Spinner } from "@/components/coss/spinner"
import { toastManager } from "@/components/coss/toast"
import { DemoSection,Feedback } from "@/components/prism-next/demo-parts"

export function AlertDemo(){return <DemoSection title="就地反馈"><div className="max-w-xl space-y-4"><Alert variant="info"><Info/><AlertTitle>材料尚未发布</AlertTitle><AlertDescription>当前修改仅影响草稿，保存后仍可继续编辑。</AlertDescription></Alert><Alert variant="success"><Check/><AlertTitle>复核完成</AlertTitle><AlertDescription>公式与示例结果一致。</AlertDescription></Alert><Alert variant="warning"><TriangleAlert/><AlertTitle>需要补充说明</AlertTitle><AlertDescription>请注明二次项系数不为零。</AlertDescription></Alert></div></DemoSection>}
export function EmptyDemo(){const[created,setCreated]=useState(false);return <DemoSection title="没有材料时">{created?<div className="space-y-4"><p className="flex items-center gap-2"><FileText className="size-4"/>新的教研材料</p><Button variant="outline" onClick={()=>setCreated(false)}>恢复空状态</Button></div>:<Empty><EmptyHeader><EmptyMedia><FileText className="size-8 text-muted-foreground"/></EmptyMedia><EmptyTitle>还没有教研材料</EmptyTitle><EmptyDescription>创建第一份材料，开始整理公式与推导。</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={()=>setCreated(true)}>创建示例材料</Button></EmptyContent></Empty>}</DemoSection>}
export function ProgressDemo(){const[value,setValue]=useState(40);return <DemoSection title="已知进度"><div className="max-w-md"><Progress value={value}><div className="flex justify-between"><ProgressLabel>材料复核</ProgressLabel><ProgressValue/></div><ProgressTrack><ProgressIndicator/></ProgressTrack></Progress><div className="mt-5 flex gap-2"><Button variant="outline" disabled={value===100} onClick={()=>setValue(n=>Math.min(100,n+20))}>完成一项</Button><Button variant="ghost" onClick={()=>setValue(0)}>重置</Button></div><Feedback>{value===100?'全部复核完成。':`已完成 ${value}%`}</Feedback></div></DemoSection>}
export function MeterDemo(){const[value,setValue]=useState(72);return <DemoSection title="范围内的当前数值"><div className="max-w-md"><Meter value={value} min={0} max={100}><div className="flex justify-between"><MeterLabel>示例材料完整度</MeterLabel><MeterValue/></div><MeterTrack><MeterIndicator/></MeterTrack></Meter><div className="mt-5 flex gap-2"><Button variant="outline" disabled={value>=100} onClick={()=>setValue(v=>Math.min(100,v+7))}>补充内容</Button><Button variant="ghost" onClick={()=>setValue(72)}>重置</Button></div></div></DemoSection>}
export function SkeletonDemo(){const[loading,setLoading]=useState(true);return <DemoSection title="加载前后保持相近结构"><div className="max-w-sm" aria-busy={loading}>{loading?<div className="space-y-3"><Skeleton className="h-6 w-3/4"/><Skeleton className="h-4 w-full"/><Skeleton className="h-4 w-5/6"/><span className="sr-only">正在加载材料内容</span></div>:<div className="space-y-2"><h3 className="font-semibold">二次方程的实数根</h3><p className="text-sm leading-6 text-muted-foreground">从判别式开始，理解求根公式及不同实数根的情况。</p></div>}<Button variant="outline" className="mt-6" onClick={()=>setLoading(v=>!v)}>{loading?'显示内容':'显示加载状态'}</Button></div></DemoSection>}
export function SpinnerDemo(){const[busy,setBusy]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);return <DemoSection title="随操作显示等待"><div className="flex flex-wrap items-center gap-5"><Button loading={busy} onClick={()=>{setBusy(true);timer.current=setTimeout(()=>setBusy(false),1200)}}>检查材料</Button><span className="flex items-center gap-2 text-sm" role="status">{busy&&<Spinner/>}{busy?'正在检查…':'可以开始检查'}</span></div></DemoSection>}
export function ToastDemo(){return <DemoSection title="短时操作结果" description="使用 coss 的 Toast 管理器、队列与关闭交互。"><div className="flex flex-wrap gap-3"><Button onClick={()=>toastManager.add({title:'修改已保存',description:'可以继续复核下一份材料。',type:'success'})}>保存成功</Button><Button variant="outline" onClick={()=>toastManager.add({title:'暂时无法保存',description:'你的修改仍保留在当前示例中。',type:'error'})}>错误反馈</Button><Button variant="outline" onClick={()=>toastManager.add({title:'已加入复核清单',type:'info'})}>普通通知</Button></div></DemoSection>}
export const feedbackDemos={alert:AlertDemo,empty:EmptyDemo,progress:ProgressDemo,meter:MeterDemo,skeleton:SkeletonDemo,spinner:SpinnerDemo,toast:ToastDemo}
