"use client"

import { useState } from "react"
import Link from "next/link"
import { Breadcrumb,BreadcrumbList,BreadcrumbItem,BreadcrumbLink,BreadcrumbSeparator,BreadcrumbPage } from "@/components/coss/breadcrumb"
import { Tabs,TabsList,TabsTab,TabsPanel } from "@/components/coss/tabs"
import { Pagination,PaginationContent,PaginationItem,PaginationLink,PaginationPrevious,PaginationNext } from "@/components/coss/pagination"
import { SidebarTrigger,useSidebar } from "@/components/coss/sidebar"
import { Button } from "@/components/coss/button"
import { DemoSection,Feedback } from "@/components/prism-next/demo-parts"

export function BreadcrumbDemo(){return <DemoSection title="当前位置"><Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink render={<Link href="/next"/>}>组件库</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator/><BreadcrumbItem><BreadcrumbLink render={<Link href="/next/reading"/>}>材料研读</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator/><BreadcrumbItem><BreadcrumbPage>二次方程的实数根</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb></DemoSection>}
export function TabsDemo(){return <><DemoSection title="分段式标签页"><Tabs defaultValue="content"><TabsList><TabsTab value="content">内容</TabsTab><TabsTab value="metadata">材料信息</TabsTab><TabsTab value="history">历史记录</TabsTab><TabsTab value="locked" disabled>已锁定</TabsTab></TabsList><TabsPanel value="content" className="py-5 text-read-body">以判别式判断实数根的情况，再使用求根公式。</TabsPanel><TabsPanel value="metadata" className="py-5 text-read-body">材料类型：例题讲解。预计研读：8 分钟。</TabsPanel><TabsPanel value="history" className="py-5 text-read-body">当前为初始示例版本，尚无修订记录。</TabsPanel></Tabs></DemoSection><DemoSection title="下划线标签页"><Tabs defaultValue="all"><TabsList variant="underline"><TabsTab value="all">全部材料</TabsTab><TabsTab value="pending">待复核</TabsTab><TabsTab value="done">已复核</TabsTab></TabsList><TabsPanel value="all" className="py-4 text-ui-body">4 份材料</TabsPanel><TabsPanel value="pending" className="py-4 text-ui-body">2 份材料需要复核</TabsPanel><TabsPanel value="done" className="py-4 text-ui-body">2 份材料已完成复核</TabsPanel></Tabs></DemoSection></>}
export function PaginationDemo(){const[page,setPage]=useState(1);const change=(next:number,e:React.MouseEvent)=>{e.preventDefault();setPage(Math.max(1,Math.min(4,next)))};return <DemoSection title="按页查看材料"><div className="mb-5 grid gap-2 text-ui-body">{[1,2,3].map(n=><p key={n} className="border-b py-2">材料 {(page-1)*3+n} · {['二次方程','函数性质','数列求和'][n-1]}</p>)}</div><Pagination><PaginationContent><PaginationItem><Button variant="ghost" aria-label="上一页" disabled={page===1} onClick={e=>change(page-1,e)}>上一页</Button></PaginationItem>{[1,2,3,4].map(n=><PaginationItem key={n}><PaginationLink href={'#page-'+n} isActive={page===n} aria-label={'第 '+n+' 页'} onClick={e=>change(n,e)}>{n}</PaginationLink></PaginationItem>)}<PaginationItem><Button variant="ghost" aria-label="下一页" disabled={page===4} onClick={e=>change(page+1,e)}>下一页</Button></PaginationItem></PaginationContent></Pagination><Feedback>第 {page} 页 / 共 4 页</Feedback></DemoSection>}
export function SidebarDemo(){const{open,isMobile,openMobile,toggleSidebar}=useSidebar();return <DemoSection title="当前页面的导航侧栏" description="本站导航直接使用同一个 coss Sidebar；窄屏切换为抽屉。"><Button variant="outline" onClick={toggleSidebar}>{(isMobile?openMobile:open)?'收起导航':'打开导航'}</Button><Feedback>可使用 Ctrl / ⌘ + B 切换。移动端关闭抽屉后，焦点回到触发按钮。</Feedback></DemoSection>}
export const navigationDemos={breadcrumb:BreadcrumbDemo,tabs:TabsDemo,pagination:PaginationDemo,sidebar:SidebarDemo}
