"use client"

import { useRef,useState } from "react"
import Link from "next/link"
import { MoreHorizontal,Copy,Archive,Info,Settings,FileText } from "lucide-react"
import { Button } from "@/components/coss/button"
import { Input } from "@/components/coss/input"
import { Textarea } from "@/components/coss/textarea"
import { Label } from "@/components/coss/label"
import { Menu,MenuTrigger,MenuPopup,MenuItem,MenuSeparator,MenuGroupLabel,MenuGroup } from "@/components/coss/menu"
import { ContextMenu,ContextMenuTrigger,ContextMenuPopup,ContextMenuItem,ContextMenuSeparator } from "@/components/coss/context-menu"
import { Dialog,DialogTrigger,DialogPopup,DialogHeader,DialogTitle,DialogDescription,DialogPanel,DialogFooter,DialogClose } from "@/components/coss/dialog"
import { AlertDialog,AlertDialogTrigger,AlertDialogPopup,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogClose } from "@/components/coss/alert-dialog"
import { Sheet,SheetTrigger,SheetPopup,SheetHeader,SheetTitle,SheetDescription,SheetPanel,SheetFooter,SheetClose } from "@/components/coss/sheet"
import { Drawer,DrawerTrigger,DrawerPopup,DrawerHeader,DrawerTitle,DrawerDescription,DrawerPanel,DrawerFooter,DrawerClose } from "@/components/coss/drawer"
import { Popover,PopoverTrigger,PopoverPopup,PopoverTitle,PopoverDescription,PopoverClose } from "@/components/coss/popover"
import { PreviewCard,PreviewCardTrigger,PreviewCardPopup } from "@/components/coss/preview-card"
import { Tooltip,TooltipTrigger,TooltipPopup } from "@/components/coss/tooltip"
import { DemoSection,Feedback,MaterialSelect,Labeled } from "@/components/prism-next/demo-parts"

export function MenuDemo(){const[message,setMessage]=useState('');return <DemoSection title="材料操作菜单"><Menu><MenuTrigger render={<Button variant="outline"/>}>材料操作<MoreHorizontal/></MenuTrigger><MenuPopup><MenuGroup><MenuGroupLabel>二次方程的实数根</MenuGroupLabel><MenuItem onClick={()=>setMessage('已创建当前材料的示例副本。')}><Copy/>创建副本</MenuItem><MenuItem onClick={()=>setMessage('已加入教研清单。')}><FileText/>加入清单</MenuItem><MenuSeparator/><MenuItem onClick={()=>setMessage('示例材料已归档。')}><Archive/>归档材料</MenuItem><MenuItem disabled>发布到全校</MenuItem></MenuGroup></MenuPopup></Menu><Feedback>{message||'点击展开菜单，使用方向键选择操作。'}</Feedback></DemoSection>}
export function ContextMenuDemo(){const[message,setMessage]=useState('');return <DemoSection title="右键菜单"><ContextMenu><ContextMenuTrigger className="flex min-h-36 max-w-lg items-center justify-center rounded-lg border border-dashed bg-muted/40 text-ui-hint text-muted-foreground">在这份材料上点击右键</ContextMenuTrigger><ContextMenuPopup><ContextMenuItem onClick={()=>setMessage('已标记为待复核。')}>标记为待复核</ContextMenuItem><ContextMenuItem onClick={()=>setMessage('已创建示例副本。')}>创建副本</ContextMenuItem><ContextMenuSeparator/><ContextMenuItem onClick={()=>setMessage('已移出当前清单。')}>移出清单</ContextMenuItem></ContextMenuPopup></ContextMenu><div className="mt-4"><Menu><MenuTrigger render={<Button variant="outline"/>}>材料操作<MoreHorizontal/></MenuTrigger><MenuPopup><MenuItem onClick={()=>setMessage('已标记为待复核。')}>标记为待复核</MenuItem><MenuItem onClick={()=>setMessage('已创建示例副本。')}>创建副本</MenuItem><MenuItem onClick={()=>setMessage('已移出当前清单。')}>移出清单</MenuItem></MenuPopup></Menu></div><Feedback>{message||'右键、键盘与触屏可通过材料操作菜单完成同样的操作。'}</Feedback></DemoSection>}
export function DialogDemo(){const[open,setOpen]=useState(false),[title,setTitle]=useState('二次方程的实数根'),[draft,setDraft]=useState(title),[kind,setKind]=useState('example'),[draftKind,setDraftKind]=useState(kind),[error,setError]=useState('');return <DemoSection title="编辑材料信息" description="在对话框内打开 Select，检查嵌套浮层与当前主题。"><Dialog open={open} onOpenChange={v=>{setOpen(v);if(v){setDraft(title);setDraftKind(kind);setError('')}}}><DialogTrigger render={<Button variant="outline"/>}>编辑材料</DialogTrigger><DialogPopup closeProps={{'aria-label':'关闭对话框'}}><DialogHeader><DialogTitle>编辑材料</DialogTitle><DialogDescription>修改标题与材料类型。</DialogDescription></DialogHeader><DialogPanel><div className="space-y-5"><Labeled label="材料标题" id="dialog-title-input"><Input id="dialog-title-input" value={draft} onChange={e=>{setDraft(e.target.value);setError('')}} aria-invalid={!!error} aria-describedby="dialog-title-error"/></Labeled>{error&&<p id="dialog-title-error" role="alert" className="text-ui-hint text-destructive-foreground">{error}</p>}<div className="max-w-48"><Labeled label="材料类型" id="dialog-kind"><MaterialSelect id="dialog-kind" value={draftKind} onChange={setDraftKind}/></Labeled></div></div></DialogPanel><DialogFooter><DialogClose render={<Button variant="ghost"/>}>取消</DialogClose><Button onClick={()=>{if(!draft.trim()){setError('请输入材料标题。');return}setTitle(draft.trim());setKind(draftKind);setOpen(false)}}>保存修改</Button></DialogFooter></DialogPopup></Dialog><Feedback>当前材料：{title}</Feedback></DemoSection>}
export function AlertDialogDemo(){const[archived,setArchived]=useState(false);const restoreRef=useRef<HTMLButtonElement>(null);return <DemoSection title="明确对象与影响"><AlertDialog><AlertDialogTrigger render={<Button variant="destructive-outline" disabled={archived}/>}>归档这份材料</AlertDialogTrigger><AlertDialogPopup finalFocus={archived?restoreRef:undefined}><AlertDialogHeader><AlertDialogTitle>归档「二次方程的实数根」？</AlertDialogTitle><AlertDialogDescription>归档后将移出当前复核清单。此操作仅影响本页示例，可以恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogClose render={<Button variant="ghost"/>}>取消</AlertDialogClose><AlertDialogClose render={<Button variant="destructive-outline"/>} onClick={()=>setArchived(true)}>确认归档</AlertDialogClose></AlertDialogFooter></AlertDialogPopup></AlertDialog><Feedback>{archived?'材料已归档。':'材料仍在当前复核清单中。'}</Feedback>{archived&&<Button ref={restoreRef} variant="outline" onClick={()=>setArchived(false)}>恢复材料</Button>}</DemoSection>}
export function SheetDemo(){const[note,setNote]=useState('请补充判别式等于零的例子。');return <DemoSection title="伴随式详情面板"><Sheet><SheetTrigger render={<Button variant="outline"/>}>查看修订备注</SheetTrigger><SheetPopup><SheetHeader><SheetTitle>修订备注</SheetTitle><SheetDescription>二次方程的实数根</SheetDescription></SheetHeader><SheetPanel><Labeled label="备注内容" id="sheet-note"><Textarea id="sheet-note" value={note} onChange={e=>setNote(e.target.value)}/></Labeled><p className="mt-3 text-ui-hint text-muted-foreground">修改在当前示例中即时保留。</p></SheetPanel><SheetFooter><SheetClose render={<Button/>}>完成</SheetClose></SheetFooter></SheetPopup></Sheet><Feedback>{note||'暂无备注。'}</Feedback></DemoSection>}
export function DrawerDemo(){return <DemoSection title="底部抽屉"><Drawer><DrawerTrigger render={<Button variant="outline"/>}>查看任务摘要</DrawerTrigger><DrawerPopup><DrawerHeader><DrawerTitle>本次材料复核</DrawerTitle><DrawerDescription>二次方程的实数根</DrawerDescription></DrawerHeader><DrawerPanel><div className="mx-auto max-w-lg space-y-3 py-2 text-read-body"><p>公式与例题计算结果一致。</p><p>建议增加判别式等于零的例子，并保留 a ≠ 0 的前提。</p></div></DrawerPanel><DrawerFooter><DrawerClose render={<Button/>}>完成阅读</DrawerClose></DrawerFooter></DrawerPopup></Drawer></DemoSection>}
export function PopoverDemo(){const[value,setValue]=useState('example');return <DemoSection title="就近展开短设置"><Popover><PopoverTrigger render={<Button variant="outline"/>}><Settings/>材料设置</PopoverTrigger><PopoverPopup><PopoverTitle>材料类型</PopoverTitle><PopoverDescription>选择当前材料的分类。</PopoverDescription><div className="mt-4 w-48"><Labeled label="类型" id="popover-kind"><MaterialSelect id="popover-kind" value={value} onChange={setValue}/></Labeled></div><PopoverClose render={<Button className="mt-4" variant="outline"/>}>完成</PopoverClose></PopoverPopup></Popover><Feedback>当前类型：{{example:'例题讲解',concept:'知识梳理',practice:'练习解析'}[value]}</Feedback></DemoSection>}
export function PreviewCardDemo(){return <DemoSection title="链接内容预览"><PreviewCard><PreviewCardTrigger href="/next/reading" className="text-(--link)">二次方程的实数根</PreviewCardTrigger><PreviewCardPopup><div><h3 className="font-semibold">二次方程的实数根</h3><p className="mt-2 leading-6 text-muted-foreground">数学 · 例题讲解 · 预计 8 分钟。包含判别式、求根公式与具体算例。</p></div></PreviewCardPopup></PreviewCard></DemoSection>}
export function TooltipDemo(){return <DemoSection title="图标的补充说明"><div className="flex gap-4"><Tooltip><TooltipTrigger render={<Button variant="outline" size="icon" aria-label="材料复核说明"/>}><Info/></TooltipTrigger><TooltipPopup>先核对公式前提，再检查例题结果。</TooltipPopup></Tooltip><Tooltip><TooltipTrigger render={<Button variant="outline"/>}>键盘也能访问</TooltipTrigger><TooltipPopup>按 Tab 聚焦这里即可阅读说明。</TooltipPopup></Tooltip></div></DemoSection>}
export const overlayDemos={menu:MenuDemo,'context-menu':ContextMenuDemo,dialog:DialogDemo,'alert-dialog':AlertDialogDemo,sheet:SheetDemo,drawer:DrawerDemo,popover:PopoverDemo,'preview-card':PreviewCardDemo,tooltip:TooltipDemo}
