"use client"
import { useRef, useState } from "react"
import { ArrowUp, ArrowDown, RotateCw, Scan } from "lucide-react"
import { Toolbar, ToolbarButton, ToolbarGroup, ToolbarSeparator } from "@/components/coss/toolbar"
import { Button } from "../button"
import { PaperPreview, PaperPreviewSurface, type PaperPreviewPage, type PaperPreviewRotation, type PaperPreviewZoom, type PaperPreviewLocation } from "../paper-preview"
import { DemoSection } from "../demo-parts"
import { ReviewDemoThemes, reviewFormula } from "./review-workspace-fixtures"
const imageUrl = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="820"><rect width="600" height="820" fill="white"/><path d="M40 90H560M40 120H560M40 360H560M40 720H560" stroke="black"/></svg>')}`
export const continuousPreviewPages: PaperPreviewPage[] = [{ id: 'full', dimensions: { width: 600, height: 820 }, imageUrl, alt: '完整扫描纸', regions: [{ id: 'answer', label: '完整推导过程与参数条件', rect: [10,20,80,25] }] }, { id: 'crop', dimensions: { width: 600, height: 260 }, alt: '裁切作答未提供' }]
export function ContinuousPreviewFixture() {
  const viewportRef = useRef<HTMLDivElement>(null), toolbarRef = useRef<HTMLDivElement>(null)
  const [zoom, setZoom] = useState<PaperPreviewZoom>('width'), [rotations, setRotations] = useState<Record<string, PaperPreviewRotation>>({}), [page, setPage] = useState(0), [selected, setSelected] = useState('answer'), [location, setLocation] = useState<PaperPreviewLocation>()
  function locate(index: number) { setLocation(previous => ({ pageId: continuousPreviewPages[index].id, request: (previous?.request ?? 0) + 1 })) }
  return <div className="grid h-[560px]"><PaperPreviewSurface viewportRef={viewportRef} toolbarRef={toolbarRef} toolbar={<Toolbar ref={toolbarRef} orientation="vertical" aria-label="试卷工具" className="d1-tools surface-floating rounded-l-none rounded-r-xl flex-col items-center"><ToolbarGroup className="flex-col"><ToolbarButton render={<Button variant="ghost" size="icon" />} aria-label="上一纸" disabled={page === 0} onClick={() => locate(page - 1)}><ArrowUp /></ToolbarButton><output className="text-ui-meta">{page + 1} / 2</output><ToolbarButton render={<Button variant="ghost" size="icon" />} aria-label="下一纸" disabled={page === 1} onClick={() => locate(page + 1)}><ArrowDown /></ToolbarButton></ToolbarGroup><ToolbarSeparator orientation="horizontal" /><ToolbarGroup className="flex-col"><ToolbarButton render={<Button variant="ghost" size="icon" />} aria-label={zoom === 'width' ? '适合页面' : '适合宽度'} onClick={() => setZoom(zoom === 'width' ? 'page' : 'width')}><Scan /></ToolbarButton><ToolbarButton render={<Button variant="ghost" size="icon" />} aria-label="旋转当前纸" onClick={() => { const id = continuousPreviewPages[page].id; setRotations(previous => ({ ...previous, [id]: ((previous[id] ?? 0) + 90) % 360 as PaperPreviewRotation })) }}><RotateCw /></ToolbarButton></ToolbarGroup></Toolbar>}>
    <PaperPreview layout="continuous" pages={continuousPreviewPages} zoom={zoom} onZoomChange={setZoom} rotation={rotations} selectedRegionId={selected} onRegionSelect={(_, id) => { setSelected(id); setLocation(previous => ({ regionId: id, request: (previous?.request ?? 0) + 1 })) }} continuous={{ viewportRef, onVisiblePage: setPage, location, spotlight: true, gap: 16, beforeContent: <section className="space-y-3 bg-card p-4 text-ui-body"><h3 className="text-block-title">题目内容</h3><p>请完整核对参数条件、推导过程与最终结论。</p>{reviewFormula}<Button variant="outline" onClick={() => setLocation(previous => ({ regionId: 'answer', request: (previous?.request ?? 0) + 1 }))}>定位作答区域</Button></section>, renderPageHeader: (_, index) => <header className="p-2 text-ui-meta">第 {index + 1} 份作答 · 外部身份信息</header> }} />
  </PaperPreviewSurface></div>
}
export function ContinuousPaperPreviewDemo() { return <DemoSection title="连续纸张 · 侧签与纸外内容" description="独立宽高、旋转与可见纸；使用 Ctrl/⌘ 滚轮或双指缩放、拖动平移，侧签跟随纸边。"><ReviewDemoThemes>{() => <ContinuousPreviewFixture />}</ReviewDemoThemes></DemoSection> }
