"use client"
import {useState} from 'react'
import {Button} from '../button'
import {Badge} from '@/components/coss/badge'
import {Select,SelectTrigger,SelectValue,SelectPopup,SelectItem} from '@/components/coss/select'
import {useId} from 'react'
import {QuestionAnalysisCard,QuestionAnalysisSummary} from '../question-analysis-card'
import {DemoSection} from '../demo-parts'
import {ReviewDemoThemes,reviewFormula} from './review-workspace-fixtures'
import {analysisQuestion,analysisKnowledge,analysisStudents} from './question-analysis-fixtures'
export function QuestionAnalysisCardFixture(){const id=useId(),[kind,setKind]=useState('解答题'),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('loss'),[marked,setMarked]=useState<string[]>([]),[notice,setNotice]=useState('');const question={...analysisQuestion,type:kind,category:kind==='解答题'?'subjective' as const:'objective' as const,record:{...analysisQuestion.record,kind,options:kind==='选择题'?[{id:'A',content:<>满足等量关系 {reviewFormula}</>},{id:'B',content:'未核对必要条件'}]:undefined,optionColumns:1 as const}};return <div className="space-y-3"><label htmlFor={id} className="text-ui-action">题型</label><Select value={kind} onValueChange={v=>{if(v)setKind(v)}}><SelectTrigger id={id}><SelectValue/></SelectTrigger><SelectPopup>{['解答题','选择题','填空题'].map(k=><SelectItem key={k} value={k}>{k}</SelectItem>)}</SelectPopup></Select><QuestionAnalysisSummary><Button variant="ghost" className="h-auto sm:h-auto whitespace-normal text-left" onClick={()=>setNotice('已请求：完整题目')}><span className="text-ui-body">第 17 题 · 参数约束关系</span> <Badge variant="outline">节选</Badge></Button></QuestionAnalysisSummary><Button variant="outline" onClick={()=>setMarked(['p2'])}>定位评分点证据</Button><QuestionAnalysisCard key={kind} question={question} related={analysisKnowledge} selected={selected} onSelect={setSelected} onIncludeCorrect={()=>setFilter('all')} filter={filter} markedPoints={marked} onKnowledge={id=>setNotice(`已请求：${id}`)} options={[{label:'A',count:1,percent:50,ratio:50,high:1,low:0,correct:true,students:[analysisStudents[1]]},{label:'B',count:1,percent:50,ratio:50,high:0,low:1,correct:false,distractor:true,students:[analysisStudents[0]]}]} groups={kind==='填空题'?{groups:{errors:[{label:<>错误答案 {reviewFormula}</>,students:[analysisStudents[0]]}],correct:[analysisStudents[1]],correctLabel:'答对'},selected,onSelect:setSelected,onIncludeCorrect:()=>setFilter('all'),filter}:undefined}/><p role="status" className="text-ui-hint">{notice}</p></div>}
export function QuestionAnalysisCardDemo(){return <DemoSection title="数字题目 · 统计与三页签详情" description="题面只由 QuestionContent 以 ui 字号渲染；公式、名单和证据与扫描变换分离。"><ReviewDemoThemes>{()=> <QuestionAnalysisCardFixture/>}</ReviewDemoThemes></DemoSection>}
