"use client"
import {useState} from 'react'
import {Button} from '../button'
import {Badge} from '@/components/coss/badge'
import {Select,SelectTrigger,SelectValue,SelectPopup,SelectItem} from '@/components/coss/select'
import {useId} from 'react'
import {QuestionAnalysisCard,QuestionAnalysisSummary,type AnalysisDetailFields} from '../question-analysis-card'
import {DemoSection} from '../demo-parts'
import {ReviewDemoThemes,reviewFormula} from './review-workspace-fixtures'
import {analysisQuestion,analysisKnowledge,analysisStudents} from './question-analysis-fixtures'
export function QuestionAnalysisCardFixture(){const id=useId(),[kind,setKind]=useState('解答题'),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('loss'),[marked,setMarked]=useState<string[]>([]),[notice,setNotice]=useState('');const question={...analysisQuestion,type:kind,category:kind==='解答题'?'subjective' as const:'objective' as const,record:{...analysisQuestion.record,kind,options:kind==='选择题'?[{id:'A',content:<>满足等量关系 {reviewFormula}</>},{id:'B',content:'未核对必要条件'}]:undefined,optionColumns:1 as const}};return <div className="space-y-3"><label htmlFor={id} className="text-ui-action">题型</label><Select value={kind} onValueChange={v=>{if(v)setKind(v)}}><SelectTrigger id={id}><SelectValue/></SelectTrigger><SelectPopup>{['解答题','选择题','填空题'].map(k=><SelectItem key={k} value={k}>{k}</SelectItem>)}</SelectPopup></Select><QuestionAnalysisSummary><Button variant="ghost" className="h-auto sm:h-auto whitespace-normal text-left" onClick={()=>setNotice('已请求：完整题目')}><span className="text-ui-body">第 17 题 · 参数约束关系</span> <Badge variant="outline">节选</Badge></Button></QuestionAnalysisSummary><Button variant="outline" onClick={()=>setMarked(['p2'])}>定位评分点证据</Button><QuestionAnalysisCard key={kind} question={question} {...completeDetailFields} related={analysisKnowledge} selected={selected} onSelect={setSelected} onIncludeCorrect={()=>setFilter('all')} filter={filter} markedPoints={marked} onKnowledge={id=>setNotice(`已请求：${id}`)} options={[{label:'A',count:1,percent:50,ratio:50,high:1,low:0,correct:true,students:[analysisStudents[1]]},{label:'B',count:1,percent:50,ratio:50,high:0,low:1,correct:false,distractor:true,students:[analysisStudents[0]]}]} groups={kind==='填空题'?{groups:{errors:[{label:<>错误答案 {reviewFormula}</>,students:[analysisStudents[0]]}],correct:[analysisStudents[1]],correctLabel:'答对'},selected,onSelect:setSelected,onIncludeCorrect:()=>setFilter('all'),filter}:undefined}/><p role="status" className="text-ui-hint">{notice}</p></div>}
export function QuestionAnalysisCardDemo(){return <><DemoSection title="数字题目 · 统计与三页签详情" description="题面只由 QuestionContent 以 ui 字号渲染；公式、名单和证据与扫描变换分离。"><ReviewDemoThemes>{()=> <QuestionAnalysisCardFixture/>}</ReviewDemoThemes></DemoSection><DemoSection title="数据不全" description="两列原题带统计时单列显示；零人数无展开按钮；选项统计缺失可切换为答错 / 答对名单。"><ReviewDemoThemes>{()=> <QuestionAnalysisIncompleteFixture/>}</ReviewDemoThemes></DemoSection></>}

const completeDetailFields:AnalysisDetailFields={
 teaching:[{label:'核心知识点',value:analysisKnowledge[0].name},{label:'教材与章节',value:'圆锥曲线与方程'},{label:'认知要求',value:'论证与推导'}],
 archive:[{label:'题目编号',value:analysisQuestion.id},{label:'题型',value:'解答题'},{label:'分值',value:'12 分'},{label:'来源',value:'组件评审夹具'},{label:'版本',value:'示例 v1'},{label:'可用状态',value:'待核对'}],
}
export function QuestionAnalysisIncompleteFixture(){
 const [grouped,setGrouped]=useState(false),[selected,setSelected]=useState<string|null>(null),[filter,setFilter]=useState('loss')
 const question={...analysisQuestion,points:[],type:'选择题',category:'objective' as const,record:{...analysisQuestion.record,kind:'选择题',optionColumns:2 as const,options:[{id:'A',content:<>满足完整条件与等量关系 {reviewFormula}</>},{id:'B',content:'缺少必要的参数取值条件'},{id:'C',content:'尚无学生选择此选项'}]}}
 const handlers={selected,onSelect:setSelected,onIncludeCorrect:()=>setFilter('all'),filter}
 return <div className="space-y-4"><Button variant="outline" onClick={()=>setGrouped(!grouped)}>{grouped?'查看部分选项统计':'选项统计未提供'}</Button><QuestionAnalysisCard question={question} related={[]} markedPoints={[]} onKnowledge={()=>{}} {...handlers} pointsEmptyText="未提供" teaching={[{label:'核心知识点',emptyText:'本题尚未关联知识点'},{label:'教材与章节',emptyText:'教材章节未提供'}]} archive={[{label:'题目编号',value:'real-question-17'},{label:'题型',value:'选择题'},{label:'分值',value:'12 分'},{label:'来源',value:'未提供'},{label:'版本',value:'未提供'},{label:'可用状态',value:'未提供'}]} options={grouped?undefined:[{label:'A',count:1,percent:50,ratio:50,correct:true,students:[analysisStudents[1]]},{label:'B',count:1,percent:50,ratio:50,highLow:{high:0},correct:false,students:[analysisStudents[0]]},{label:'C',count:0,percent:0,ratio:0,correct:false,students:[]}]} groups={grouped?{...handlers,description:'选项作答未提供',groups:{errors:[{label:'答错',students:[analysisStudents[0]]}],correct:[analysisStudents[1]],correctLabel:'答对'}}:undefined}/></div>
}
