"use client"
import {useId,useRef,useState} from 'react'
import {Separator} from '@/components/coss/separator'
import {StudentControlBar,StudentControlBarRow,StudentControlHome,StudentControlFilters,StudentControlSwitcher,StudentControlScale} from '../student-control-bar'
import {DemoSection} from '../demo-parts'
import {ReviewDemoThemes,reviewFormula} from './review-workspace-fixtures'
import {analysisStudents} from './question-analysis-fixtures'
export function StudentControlBarFixture(){const id=useId(),trigger=useRef<HTMLButtonElement>(null),[selected,setSelected]=useState<string|null>(null),[open,setOpen]=useState(false),[filter,setFilter]=useState('all'),[notice,setNotice]=useState('');const items=analysisStudents.filter(i=>filter==='all'||i.id==='a');return <><div className="relative h-32"><StudentControlBar style={{left:0,maxWidth:'100%'}}><StudentControlBarRow><StudentControlHome active={!selected} onHome={()=>setNotice('已请求：回到题目')}/><Separator orientation="vertical"/><StudentControlFilters value={filter} onValueChange={setFilter} items={[{value:'loss',label:'失分',count:1},{value:'all',label:'全部',count:2}]}/><Separator orientation="vertical"/><StudentControlSwitcher items={items} current={items.find(i=>i.id===selected)??null} groups={['待复核','已确认'].map(value=>({value,items:items.filter(i=>i.group===value)}))} max={12} open={open} onOpenChange={setOpen} onSelect={id=>{setSelected(id);setOpen(false)}} triggerRef={trigger} searchId={id}/></StudentControlBarRow><StudentControlScale items={items.map(i=>({id:i.id,tone:i.tickTone,tooltip:<>{i.name} · {i.scoreText} · {reviewFormula}</>}))} selected={selected} summary={filter==='all'?'2 位学生：满分 1、部分 1、零分 0':'1 位学生：满分 0、部分 1、零分 0'} onSelect={setSelected}/></StudentControlBar></div><p role="status" className="text-ui-hint">{notice||'标准控件保持尺寸，窄容器内横向滚动。'}</p></>}
export function StudentControlBarDemo(){return <DemoSection title="学生控制条 · 筛选、切换与全班刻度" description="身份和分布是外部事实；刻度为鼠标辅助，键盘使用切换与搜索。"><ReviewDemoThemes>{()=> <StudentControlBarFixture/>}</ReviewDemoThemes></DemoSection>}
